#!/usr/bin/env python3
"""
lock_it_down.py - one-shot dev -> locked-down transition flasher for PolyCast5.

Writes the locked-down build (POLYCAST5_SECURE_RELEASE=1 in CMakeLists.txt) onto
a device that is already running dev-mode flash encryption, as ciphertext, via
the ROM's download-mode encryption. This is the "Path B" companion to
www.polycast5.com/blogs/docs/lock-it-down - use plain `idf.py flash` for
factory-fresh chips instead.

How it works, start to finish:
  1. Build checks      - refuses anything that is not a signed, release-mode,
                         bootloader-included build (nothing read off the wire yet).
  2. Plan building     - offsets/images come from build/flasher_args.json
                         (regenerated by every build) and every entry is
                         cross-checked against partitions.csv, so partition
                         layout changes are picked up automatically.
  3. Device checks     - the transition is only possible from exactly one
                         state: dev-mode flash encryption active, secure boot
                         not yet enabled, full ROM download mode. Anything
                         else gets a specific explanation, not a brick.
  4. Final gate        - the full plan is shown; you must type 'LOCK'.
  5. Flash             - one esptool write-flash: the security images are
                         encrypted with the device's own eFuse key (via
                         --encrypt-files) while the assets image is written
                         plaintext, so the whole layout matches after lockdown.
  6. First boot        - the signed bootloader enables Secure Boot v2 and the
                         firmware burns the remaining release eFuses, then
                         restarts. Boot 2 is a normal locked-down boot.

NVS settings and pairing data are never touched - user data survives the
transition. The assets filesystem IS re-flashed (plaintext) so it always
matches the locked-in app and partition table, even if the layout moved.

THE FIRST BOOT AFTER THIS FLASH PERMANENTLY BURNS EFUSES. Read the guide first.

Usage:
    python lock_it_down.py [-p PORT] [--dry-run] [--yes] [--build-dir DIR]
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# Reuse the shared helpers (colors, esptool invocation, partition parsing, the
# encrypt/plaintext decision table) so both flashers agree on the rules.
from flash import (ROOT, Partition, load_partitions, should_encrypt,
                   esptool_cmd, run, die, autodetect_port,
                   green, red, yellow, cyan, gray, bold, human_size, parse_num)

CHIP = "esp32c5"

# Set True once the encrypted write begins. Before that, an interrupt is a
# clean abort; after it, a partial (irreversible) write may have landed.
_write_started = False


# ===========================================================================
# Build-side checks. Everything in this section runs before a device is even
# needed - a wrong build must die here, not on the wire.
# ===========================================================================
def load_json(path: Path, hint: str) -> dict:
    if not path.exists():
        die(f"{path} not found.", hint)
    try:
        return json.loads(path.read_text())
    except Exception as e:
        die(f"could not parse {path}: {e}")


def check_locked_profile(cfg: dict) -> None:
    """Refuse anything that is not a signed, release-mode build.

    cfg is build/config/sdkconfig.json - the resolved Kconfig of the build
    actually sitting in build/, so this reflects what WILL be flashed, not
    what CMakeLists.txt currently says."""
    # Dev profile? Then this is the wrong tool entirely.
    if not cfg.get("SECURE_FLASH_ENCRYPTION_MODE_RELEASE", False):
        die("this build is the DEV profile (flash encryption in development mode).",
            "Set POLYCAST5_SECURE_RELEASE to 1 in CMakeLists.txt, then:",
            "  idf.py fullclean && idf.py build",
            "For normal dev flashing use flash.py / idf.py flash instead.")
    # Release-mode FE without secure boot would seal the device while leaving
    # it able to boot anyone's code - never allow that combination.
    if not cfg.get("SECURE_BOOT", False):
        die("this build has release-mode flash encryption but Secure Boot is OFF.",
            "Locking a device without secure boot is unsupported - it would be",
            "sealed but not secured. Check sdkconfig.defaults.secure was applied",
            "(delete sdkconfig.secure and rebuild if you edited it).")
    # Unsigned images would fail the bootloader's signature check on boot 2,
    # after the eFuses are already burned - i.e. a bricked device.
    if not cfg.get("SECURE_BOOT_BUILD_SIGNED_BINARIES", False):
        die("this build does not sign its binaries at build time.",
            "The bootloader/app in build/ may be unsigned - flashing them would",
            "leave the device unbootable once secure boot is enabled.")
    # With secure boot on, IDF only includes the bootloader in the flash set
    # (and flasher_args.json) when this option is set. Without it we would
    # flash everything EXCEPT the one image that performs the lockdown.
    if not cfg.get("SECURE_BOOT_FLASH_BOOTLOADER_DEFAULT", False):
        die("this build excludes the signed bootloader from its flash set.",
            "CONFIG_SECURE_BOOT_FLASH_BOOTLOADER_DEFAULT=y is missing, so the",
            "transition would never install the eFuse-burning bootloader.",
            "Check sdkconfig.defaults.secure was applied, then rebuild.")
    # Load-bearing for THIS (upgrade) path specifically: an already-encrypted
    # device has XTS_DPA_PSEUDO_LEVEL=0, and without this option esp_security_init
    # write-protects that eFuse group before app_main runs - so main.c could never
    # burn the DPA level and release-mode verification would fail on every boot.
    # It only resolves to y in the sdkconfig when SECURE_BOOT_INSECURE=y also
    # unhides its menu, so this check catches a stale/hand-edited sdkconfig.secure
    # that dropped either symbol. (Fresh chips are immune - their bootloader burns
    # the level to 1 on first boot - but this script is the dev->release tool.)
    if not cfg.get("SECURE_BOOT_SKIP_WRITE_PROTECTION_SCA", False):
        die("this build is missing CONFIG_SECURE_BOOT_SKIP_WRITE_PROTECTION_SCA.",
            "Without it, the DPA-protection eFuse gets write-protected at 0 before",
            "the firmware can set it, and the release-mode transition never completes",
            "on an already-encrypted device. Ensure sdkconfig.defaults.secure was",
            "applied (it needs both SECURE_BOOT_INSECURE=y and this option); delete",
            "sdkconfig.secure and rebuild if you edited the overlay.")


def build_plan(build_dir: Path, fargs: dict, cfg: dict,
               parts: dict[int, Partition]) -> tuple[list[dict], list[dict]]:
    """Return (writes, skips). Every image the build produced is planned as a
    write - encrypted for the security/app images, plaintext for firmware-owned
    data like assets - so the locked-in layout is always self-consistent. Nothing
    outside the partition table is written, and NVS / nvs_keys are always rejected
    so user data is preserved. (skips is retained for display; normally empty.)"""
    writes: list[dict] = []
    skips: list[dict] = []
    seen: set[int] = set()
    pt_offset = int(cfg.get("PARTITION_TABLE_OFFSET", 0))

    def add(label: str, entry: dict | None, expect) -> None:
        # One named image (bootloader / partition table / otadata / app) from
        # flasher_args.json. `expect` validates the target partition (None =
        # no partition: bootloader and the table itself live below the table).
        # All four are REQUIRED - a build that omits one (e.g. the signed
        # bootloader) must never be half-flashed as a "successful" transition.
        if entry is None:
            die(f"{label} image is missing from flasher_args.json.",
                "The locked build must produce bootloader, partition table,",
                "otadata, and app images - stale or mis-configured build?",
                "Run `idf.py fullclean && idf.py build` and retry.")
        off = parse_num(entry["offset"])
        path = build_dir / entry["file"]
        if not path.exists():
            die(f"{label} image missing: {path}", "Run `idf.py build` first.")
        # Cross-check the flasher_args offset against partitions.csv - this is
        # what makes the script safe across partition-table changes: a stale
        # build and an edited table cannot silently disagree.
        part = parts.get(off)
        err = expect(off, part)
        if err:
            die(f"{label}: {err}",
                "flasher_args.json and partitions.csv disagree - stale build?",
                "Run `idf.py fullclean && idf.py build` and retry.")
        # The ROM encrypts in 16-byte XTS blocks; unaligned writes are impossible.
        if off % 16:
            die(f"{label}: offset {off:#x} is not 16-byte aligned; "
                "the ROM cannot encrypt-write it.")
        size = path.stat().st_size
        # The bootloader has no partitions.csv entry; its budget ends at the table.
        limit = part.size if part else (pt_offset - off if off < pt_offset else None)
        if limit is not None and size > limit:
            die(f"{label}: {path.name} ({human_size(size)}) exceeds its "
                f"partition ({human_size(limit)}).")
        writes.append({"label": label, "offset": off, "path": path, "size": size,
                       "encrypt": True})
        seen.add(off)

    add("bootloader", fargs.get("bootloader"),
        lambda off, p: None if p is None and off < pt_offset else
        "expected to sit below the partition table, outside any partition")
    add("partition table", fargs.get("partition-table"),
        lambda off, p: None if p is None and off == pt_offset else
        f"offset {off:#x} != CONFIG_PARTITION_TABLE_OFFSET {pt_offset:#x}")
    add("otadata", fargs.get("otadata"),
        lambda off, p: None if p and p.ptype == "data" and p.subtype == "ota" else
        "target is not the data/ota (otadata) partition")
    add("app", fargs.get("app"),
        lambda off, p: None if p and p.ptype == "app" else
        "target is not an app partition")

    # Anything else the build wants flashed (e.g. the assets LittleFS image):
    # decide encrypt-vs-plaintext by the same rules flash.py uses, and re-flash it
    # either way so the app, partition table, and assets we lock in always agree.
    for off_s, rel in fargs.get("flash_files", {}).items():
        off = parse_num(off_s)
        if off in seen:
            continue  # already planned as one of the four named images
        part = parts.get(off)
        if part is None:
            # An image aimed at flash we can't account for is never written.
            die(f"build wants to flash {rel} at {off:#x}, which is not in "
                "partitions.csv.", "Refusing to write outside the partition table.")
        # Never overwrite the device's NVS or its encryption keys - doing so
        # would orphan every stored setting. The normal build emits no such
        # image; this keeps user data structurally out of the plan.
        if part.subtype in ("nvs", "nvs_keys"):
            die(f"build wants to flash {rel} onto the '{part.name}' "
                f"({part.subtype}) partition.",
                "Refusing - this would destroy the device's saved settings/keys.",
                "The transition must preserve NVS; rebuild without this image.")
        path = build_dir / rel
        if not path.exists():
            die(f"image missing: {path}")
        size = path.stat().st_size
        if size > part.size:
            die(f"'{part.name}': {path.name} ({human_size(size)}) exceeds its "
                f"partition ({human_size(part.size)}).")
        encrypt = should_encrypt(True, part)
        if encrypt and off % 16:
            # The ROM encrypts in 16-byte XTS blocks; unaligned writes are impossible.
            die(f"'{part.name}': offset {off:#x} is not 16-byte aligned; "
                "the ROM cannot encrypt-write it.")
        # Firmware-owned partitions (assets LittleFS, a second app, etc.) are
        # always re-flashed. A plaintext one (assets) is re-flashed plaintext so a
        # moved layout or a changed bundle can't orphan the filesystem after the
        # irreversible lockdown; NVS/nvs_keys were rejected above, so user data is
        # still never touched.
        writes.append({"label": f"{part.name} ({part.subtype})", "offset": off,
                       "path": path, "size": size, "encrypt": encrypt})
    return writes, skips


# ===========================================================================
# Device-side checks. The transition is only possible from exactly one state:
# dev-mode flash encryption active, secure boot not yet enabled, full ROM
# download mode. Anything else gets a specific explanation, not a brick.
# ===========================================================================
def check_device_state(port: str) -> None:
    # after="hard-reset" on every probe so that ANY early exit (a failed
    # probe, a declined confirmation) leaves the device running its current
    # firmware, not stranded in the download stub. The final write re-enters
    # the bootloader itself via default-reset, so the extra app boots between
    # steps cost nothing. (This mirrors flash.py's deliberate choice.)
    proc = run(esptool_cmd(port, CHIP, "default-reset", "hard-reset",
                           "get-security-info"), capture=True, fatal=False)
    if proc is None:
        die("couldn't read the device's security info.",
            "Is the device connected and the right port selected?",
            "Close any open idf.py monitor / serial terminal holding the port.",
            "Run this from an ESP-IDF terminal (so `python -m esptool` is available).")
    out = proc.stdout or ""

    # Secure Download Mode = the lockdown already started (its eFuse burns on
    # the signed bootloader's first boot). Encrypted USB writes are impossible
    # from here. Detection: the security-info Flags word (bit 2 =
    # SECURE_DOWNLOAD_ENABLE) is authoritative; the esptool connect-banner
    # string is a belt-and-braces fallback.
    m = re.search(r"Flags:\s*(0x[0-9a-fA-F]+)", out)
    sdm_flag = bool(int(m.group(1), 16) & (1 << 2)) if m else False
    if sdm_flag or re.search(r"Secure Download Mode", out, re.I):
        die("this device is already in Secure Download Mode.",
            "Encrypted USB writes are no longer possible on it. If lockdown was",
            "interrupted, power-cycle and let the firmware finish; otherwise this",
            "unit can only be updated over OTA.")
    # Secure boot already on = the transition already happened. (The regex
    # cannot match the healthy 'Secure Boot: Disabled' line.)
    if re.search(r"Secure Boot:\s*Enabled", out, re.I):
        die("secure boot is already enabled on this device.",
            "The transition has already happened (or is mid-way - power-cycle and",
            "watch the console). Serial re-flash is no longer possible.")
    # No flash encryption = a fresh chip; that is Path A, not this script.
    m = re.search(r"Flash[ _]Encryption:\s*(Enabled|Disabled)", out, re.I)
    if not m:
        # Fail closed: if we can't classify the device, we don't touch it.
        die("couldn't parse the device's flash-encryption state.", out.strip()[-400:])
    if m.group(1).lower() != "enabled":
        die("flash encryption is NOT active on this device (fresh chip?).",
            "This script is only for devices already running dev-mode flash",
            "encryption. For a fresh chip just use:  idf.py -p PORT flash")

    # Best effort: confirm the ROM can still encrypt on our behalf
    # (DIS_DOWNLOAD_MANUAL_ENCRYPT unburned - true for every dev-profile
    # PolyCast5). esptool re-checks this itself before writing, so a parse
    # failure here is a warning, not a stop.
    proc = run([sys.executable, "-m", "espefuse", "--chip", CHIP, "-p", port,
                "--before", "default-reset", "--after", "hard-reset",
                "summary", "DIS_DOWNLOAD_MANUAL_ENCRYPT"],
               capture=True, fatal=False)
    m = re.search(r"DIS_DOWNLOAD_MANUAL_ENCRYPT.*?=\s*(True|False)",
                  (proc.stdout or "") if proc else "", re.S)
    if m and m.group(1) == "True":
        die("DIS_DOWNLOAD_MANUAL_ENCRYPT is burned on this device.",
            "The ROM can no longer encrypt images during download, so the serial",
            "transition path is closed. This unit can only be updated over OTA.")
    if not m:
        print(yellow("Couldn't confirm DIS_DOWNLOAD_MANUAL_ENCRYPT (espefuse "
                     "parse failed); esptool will still refuse if it is burned."))


# ===========================================================================
# Confirmation prompt. A single gate for a one-way operation: 'LOCK' at the end,
# with the full plan on screen. Requires a real terminal; --yes skips it.
# ===========================================================================
def require_tty() -> None:
    if not sys.stdin or not sys.stdin.isatty():
        die("refusing to run without confirmation in a non-interactive shell.",
            "Re-run with --yes if you really mean it.")


# ===========================================================================
# Main.
# ===========================================================================
def main() -> int:
    ap = argparse.ArgumentParser(
        description="Flash the locked-down build onto a dev-mode PolyCast5 "
                    "(encrypted serial transition). One-way: first boot burns eFuses.")
    ap.add_argument("-p", "--port", help="serial port (default: autodetect)")
    ap.add_argument("--dry-run", action="store_true",
                    help="show the flash plan and exit; no device access")
    ap.add_argument("--yes", action="store_true",
                    help="skip the interactive confirmation")
    ap.add_argument("--build-dir", type=Path, default=ROOT / "build",
                    help="build directory (default: ./build)")
    args = ap.parse_args()

    # ---- build-side validation (steps 1-2: no device involved yet) ----
    build_dir = args.build_dir
    cfg = load_json(build_dir / "config" / "sdkconfig.json",
                    "Build the locked profile first: idf.py build")
    check_locked_profile(cfg)

    fargs = load_json(build_dir / "flasher_args.json",
                      "Build the project first: idf.py build")
    parts = load_partitions()
    if not parts:
        die("partitions.csv not found or empty - cannot cross-check offsets.")

    writes, skips = build_plan(build_dir, fargs, cfg, parts)

    # ---- show the plan ----
    print(bold("\nTransition plan (dev -> locked down):"))
    for w in writes:
        off_hex = f"{w['offset']:#09x}"
        kind = green('encrypted write') if w.get("encrypt", True) else cyan('plaintext write')
        print(f"  {cyan(off_hex)}  {w['path'].name:<28} "
              f"{human_size(w['size']):>10}  {kind}")
    for s in skips:
        print(f"  {'':9}  {s['label']:<40} {gray('skipped: ' + s['reason'])}")
    print(yellow("\n  NVS settings and pairing data survive; assets are re-flashed to match."))
    print(red(bold("  The FIRST BOOT after this flash permanently burns eFuses.")))
    print(red("  Do not cut power. USB re-flashing is disabled forever afterward."))
    print(yellow("  Confirm your secure_boot_signing_key.pem is backed up offline -"))
    print(yellow("  losing it means this device can never be updated again.\n"))

    if args.dry_run:
        print(gray("Dry run - no device was touched."))
        return 0

    # ---- device-side validation (step 3) ----
    port = args.port or autodetect_port()
    check_device_state(port)

    # Final gate: last chance, with the full plan and device state known-good.
    if not args.yes:
        require_tty()
        reply = input(bold("Type LOCK to flash (anything else aborts): ")).strip()
        if reply != "LOCK":
            print("Aborted - nothing was written.")
            return 1

    # ---- the encrypted write (step 5) ----
    # No --flash-mode/--flash-freq/--flash-size args: 'keep' (the default)
    # writes the build-signed images verbatim. Letting esptool re-patch the
    # bootloader header would risk invalidating its secure-boot signature.
    # Plaintext files (assets) are positional; encrypted files (bootloader, table,
    # otadata, app) go under --encrypt-files. One write-flash, so everything lands
    # in a single session before the lockdown first boot -- no reset in between.
    enc_pairs: list[str] = []
    plain_pairs: list[str] = []
    for w in writes:
        pair = [f"{w['offset']:#x}", str(w["path"])]
        (enc_pairs if w.get("encrypt", True) else plain_pairs).extend(pair)
    if plain_pairs:
        wf_args = ["write-flash", *plain_pairs, "--encrypt-files", *enc_pairs]
    else:
        wf_args = ["write-flash", "--encrypt", *enc_pairs]
    # From here on a Ctrl-C could interrupt a partial, irreversible write, so
    # the __main__ handler must stop claiming "nothing was written".
    global _write_started
    _write_started = True
    proc = run(esptool_cmd(port, CHIP, "default-reset", "hard-reset", *wf_args), fatal=False)
    if proc is None:
        # eFuses burn only once the device boots a COMPLETE, validly-signed
        # image set - the bootloader batch-cancels every eFuse write unless a
        # signed app loads. So a partial/failed write leaves the chip
        # unbootable, not locked; a write that actually completed (esptool can
        # report failure on a teardown/port hiccup after the last image) is
        # already locking down. The console tells you which happened - don't
        # guess, and don't suggest `flash.py`, which now rebuilds the locked
        # profile and would just resume the lockdown.
        die("encrypted flash write failed or was interrupted.",
            "Power-cycle the device and check the console:",
            "  - lockdown log lines  -> the write completed, it IS locking down;",
            "  - boot error / nothing -> partial write, unbootable but NOT locked.",
            "To retry the lockdown: run this script again.",
            "To abandon it and return to dev firmware: set POLYCAST5_SECURE_RELEASE=0",
            "in CMakeLists.txt, then  idf.py fullclean && idf.py build && python flash.py --all")

    # ---- step 6: the device does the rest on its own ----
    print(green(bold("\nFlashed. The device is now booting the signed build:")))
    print("  boot 1: enables secure boot, finishes the release eFuses, restarts")
    print("  boot 2: normal locked-down boot")
    print("Watch it with:  idf.py -p " + port + " monitor")
    print("Success looks like:")
    print(gray("  I (....) MAIN: Flash encryption: release mode verified"))
    print(gray("  I (....) MAIN: Secure boot: enabled, release mode verified"))
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (KeyboardInterrupt, EOFError):
        if _write_started:
            # Ctrl-C landed during the flash write - a partial, irreversible
            # write may exist. Do NOT claim the device is untouched.
            print(red("\nInterrupted DURING the flash write - a partial write may have landed."))
            print("Power-cycle and check the console: lockdown log lines mean the write")
            print("completed. Re-run this script to retry, or revert to a dev build first")
            print("(POLYCAST5_SECURE_RELEASE=0, then idf.py fullclean && idf.py build).")
        else:
            # Interrupt at a prompt / during a probe - nothing was written yet.
            print("\nAborted - nothing was written.")
        sys.exit(130)
