// AI analysis web portal HTML (single page)
const char *AI_ANALYSIS_PORTAL_HTML =
"<!doctype html>\n"
"<html lang=\"en\">\n"
"  <head>\n"
"    <meta charset=\"utf-8\" />\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
"    <title>PolyCast5 AI Packet Analysis</title>\n"

"    <style>\n"
"      :root {\n"
"        --bg: #060b18;\n"
"        --bg-panel: #0c1528;\n"
"        --border: #1a3068;\n"
"        --accent: #5ba3f5;\n"
"        --accent-dim: #0047ab;\n"
"        --accent-glow: rgba(0,71,171,0.25);\n"
"        --text: #d6dff0;\n"
"        --text-bright: #f0f4fa;\n"
"        --page-padding: 20px;\n"
"        --radius: 4px;\n"
"      }\n"

"      *, *::before, *::after { box-sizing: border-box; }\n"

"      body {\n"
"        font-family: 'Courier New', Courier, monospace;\n"
"        margin: 0;\n"
"        padding: var(--page-padding);\n"
"        background: var(--bg);\n"
"        color: var(--text);\n"
"        line-height: 1.45;\n"
"        max-width: 900px;\n"
"        margin: 0 auto;\n"
"        position: relative;\n"
"      }\n"

"      body::after {\n"
"        content: '';\n"
"        position: fixed;\n"
"        inset: 0;\n"
"        background: repeating-linear-gradient(\n"
"          0deg,\n"
"          transparent,\n"
"          transparent 2px,\n"
"          rgba(0,0,0,0.08) 2px,\n"
"          rgba(0,0,0,0.08) 4px\n"
"        );\n"
"        pointer-events: none;\n"
"        z-index: 9999;\n"
"      }\n"

"      h2 {\n"
"        color: var(--accent);\n"
"        text-transform: uppercase;\n"
"        letter-spacing: 3px;\n"
"        font-size: 1.3em;\n"
"        border-bottom: 2px solid var(--accent-dim);\n"
"        padding-bottom: 10px;\n"
"        text-shadow: 0 0 10px rgba(91,163,245,0.4);\n"
"      }\n"

"      p {\n"
"        font-size: 0.85em;\n"
"        margin: 8px 0;\n"
"      }\n"

"      .small-note {\n"
"        opacity: 0.75;\n"
"        font-size: 0.8em;\n"
"      }\n"

"      #out {\n"
"        background: var(--bg);\n"
"        color: var(--text-bright);\n"
"        padding: 16px;\n"
"        border-radius: var(--radius);\n"
"        border: 1px solid var(--border);\n"
"        overflow: auto;\n"
"        margin-top: 16px;\n"
"        font-size: 0.9em;\n"
"        line-height: 1.5;\n"
"      }\n"

"      #out pre {\n"
"        background: var(--bg);\n"
"        color: var(--text-bright);\n"
"        padding: 12px;\n"
"        border: 1px solid var(--border);\n"
"        border-radius: var(--radius);\n"
"        overflow: auto;\n"
"      }\n"

"      #out code {\n"
"        background: var(--bg);\n"
"        color: var(--accent);\n"
"        padding: 2px 5px;\n"
"        border-radius: 3px;\n"
"        font-family: inherit;\n"
"      }\n"

"      #out pre code {\n"
"        background: none;\n"
"        color: var(--text-bright);\n"
"        padding: 0;\n"
"      }\n"

"      #out a {\n"
"        color: var(--accent);\n"
"        text-decoration: none;\n"
"        border-bottom: 1px dashed var(--accent-dim);\n"
"      }\n"

"      #out h1, #out h2, #out h3 {\n"
"        color: var(--accent);\n"
"        margin: 16px 0 8px;\n"
"        text-transform: none;\n"
"        letter-spacing: normal;\n"
"        border: none;\n"
"        padding: 0;\n"
"        text-shadow: none;\n"
"      }\n"

"      #out h1 { font-size: 1.2em; }\n"
"      #out h2 { font-size: 1.1em; }\n"
"      #out h3 { font-size: 1em; }\n"

"      #out ul {\n"
"        margin: 8px 0 8px 20px;\n"
"      }\n"

"      #out table {\n"
"        border-collapse: collapse;\n"
"        width: 100%;\n"
"        margin: 12px 0;\n"
"      }\n"

"      #out th, #out td {\n"
"        border: 1px solid var(--border);\n"
"        padding: 6px 10px;\n"
"        vertical-align: top;\n"
"      }\n"

"      #out th {\n"
"        background: var(--bg);\n"
"        color: var(--accent);\n"
"        font-weight: 600;\n"
"      }\n"

"      ::selection {\n"
"        background: var(--accent);\n"
"        color: var(--bg);\n"
"      }\n"

"      ::-webkit-scrollbar { width: 6px; height: 6px; }\n"
"      ::-webkit-scrollbar-track { background: var(--bg); }\n"
"      ::-webkit-scrollbar-thumb { background: var(--accent-dim); border-radius: 3px; }\n"
"    </style>\n"
"  </head>\n"

"  <body>\n"
"    <h2>PolyCast5 AI Packet Analysis</h2>\n"
"    <p class=\"small-note\">This page shows an AI analysis of the 802.11 packets captured.</p>\n"
"    <p class=\"small-note\">\n"
"      For your reference, packets captured can be of type:\n"
"      MGMT, CTRL, DATA, MISC, DATA_MPDU, or DATA_AMPDU.\n"
"    </p>\n"
"    <p class=\"small-note\">Please verify important information.</p>\n"
"    <div id=\"out\">Loading...</div>\n"

"    <script>\n"
"      // -------------------------------\n"
"      // HTML escaping\n"
"      // -------------------------------\n"
"      function escHtml(s) {\n"
"        return (s || '')\n"
"          .replace(/&/g, '&amp;')\n"
"          .replace(/</g, '&lt;')\n"
"          .replace(/>/g, '&gt;')\n"
"          .replace(/\"/g, '&quot;')\n"
"          .replace(/'/g, '&#39;');\n"
"      }\n"

"      // -------------------------------\n"
"      // Inline markdown formatting\n"
"      // -------------------------------\n"
"      function fmtInline(s) {\n"
"        return s\n"
"          .replace(/\\*\\*(.+?)\\*\\*/g, '<strong>$1</strong>')\n"
"          .replace(/\\*(.+?)\\*/g, '<em>$1</em>')\n"
"          .replace(/`([^`]+?)`/g, '<code>$1</code>');\n"
"      }\n"

"      // -------------------------------\n"
"      // Table helpers\n"
"      // -------------------------------\n"
"      function isTableSep(line) {\n"
"        var t = (line || '').trim();\n"
"        if (!t) return false;\n"
"        return /^\\|?\\s*:?-+:?\\s*(\\|\\s*:?-+:?\\s*)+\\|?$/.test(t);\n"
"      }\n"

"      function splitTableRow(line) {\n"
"        var t = (line || '').trim();\n"
"        if (t.startsWith('|')) t = t.slice(1);\n"
"        if (t.endsWith('|')) t = t.slice(0, -1);\n"
"        return t.split('|').map(function(c) { return c.trim(); });\n"
"      }\n"

"      function looksLikeTableRow(line) {\n"
"        var t = (line || '').trim();\n"
"        return t.includes('|') && t.replace(/\\|/g, '').trim().length > 0;\n"
"      }\n"

"      // -------------------------------\n"
"      // Markdown renderer\n"
"      // -------------------------------\n"
"      function renderMd(md) {\n"
"        md = (md || '').replace(/\\r\\n/g, '\\n');\n"
"        var parts = md.split('```');\n"
"        var out = '';\n"

"        for (var i = 0; i < parts.length; i++) {\n"
"          // Odd parts are fenced code blocks\n"
"          if (i % 2 === 1) {\n"
"            out += '<pre><code>' + escHtml(parts[i]) + '</code></pre>';\n"
"            continue;\n"
"          }\n"

"          // Even parts are regular markdown\n"
"          var s = escHtml(parts[i]);\n"
"          var lines = s.split('\\n');\n"
"          var inList = false;\n"

"          for (var li = 0; li < lines.length; li++) {\n"
"            var line = lines[li];\n"

"            // Table detection: current line has pipes and next line is a separator\n"
"            if (looksLikeTableRow(line) && (li + 1 < lines.length) && isTableSep(lines[li + 1])) {\n"
"              if (inList) { out += '</ul>'; inList = false; }\n"
"              var head = splitTableRow(line);\n"
"              li++;\n"
"              out += '<table><thead><tr>';\n"

"              for (var c = 0; c < head.length; c++) {\n"
"                out += '<th>' + fmtInline(head[c]) + '</th>';\n"
"              }\n"
"              out += '</tr></thead><tbody>';\n"

"              for (li = li + 1; li < lines.length; li++) {\n"
"                var rline = lines[li];\n"
"                if (!looksLikeTableRow(rline) || rline.trim() === '') { li--; break; }\n"
"                var row = splitTableRow(rline);\n"
"                out += '<tr>';\n"

"                for (var rc = 0; rc < row.length; rc++) {\n"
"                  out += '<td>' + fmtInline(row[rc]) + '</td>';\n"
"                }\n"
"                out += '</tr>';\n"
"              }\n"

"              out += '</tbody></table>';\n"
"              continue;\n"
"            }\n"

"            // List items\n"
"            if (/^\\s*[-*]\\s+/.test(line)) {\n"
"              if (!inList) { out += '<ul>'; inList = true; }\n"
"              line = line.replace(/^\\s*[-*]\\s+/, '');\n"
"            } else {\n"
"              if (inList) { out += '</ul>'; inList = false; }\n"
"            }\n"

"            if (inList) {\n"
"              out += '<li>' + fmtInline(line) + '</li>';\n"
"              continue;\n"
"            }\n"

"            // Headings\n"
"            if (/^###\\s+/.test(line)) { out += '<h3>' + line.replace(/^###\\s+/, '') + '</h3>'; continue; }\n"
"            if (/^##\\s+/.test(line)) { out += '<h2>' + line.replace(/^##\\s+/, '') + '</h2>'; continue; }\n"
"            if (/^#\\s+/.test(line)) { out += '<h1>' + line.replace(/^#\\s+/, '') + '</h1>'; continue; }\n"

"            // Regular text or blank line\n"
"            line = fmtInline(line);\n"
"            if (line.trim() === '') { out += '<br>'; }\n"
"            else { out += '<div>' + line + '</div>'; }\n"
"          }\n"

"          if (inList) { out += '</ul>'; }\n"
"        }\n"

"        return out;\n"
"      }\n"

"      // -------------------------------\n"
"      // Fetch and render\n"
"      // -------------------------------\n"
"      async function load() {\n"
"        var el = document.getElementById('out');\n"

"        try {\n"
"          var r = await fetch('/api/result');\n"
"          if (!r.ok) { el.textContent = 'HTTP ' + r.status; return; }\n"

"          var j = await r.json();\n"
"          if (!j.has_result) { el.textContent = 'No result available.'; return; }\n"

"          el.innerHTML = renderMd(j.md || '');\n"
"        } catch (e) {\n"
"          el.textContent = 'Load failed';\n"
"        }\n"
"      }\n"

"      load();\n"
"    </script>\n"
"  </body>\n"
"</html>\n"
;
