// AI web portal HTML (single page)
const char *AI_PORTAL_HTML =
"<!doctype html><meta charset=utf-8>\n"
"<meta name=viewport content='width=device-width,initial-scale=1'>\n"
"<title>PolyCast5 AI Portal</title>\n"
"<style>"
"body{font-family:system-ui,Arial,sans-serif;margin:16px;max-width:640px}"
"label{display:block;margin:8px 0 4px}"
"input,textarea{width:100%;font-size:16px;padding:8px}"
"textarea{height:240px;font-family:ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace;font-size:13px}"
"</style>\n"

"<h2>PolyCast5 AI Portal</h2>\n"
"<p>Paste your <b>Grok (xAI)</b> API key below and click save. (Typically starts with <code>xai-</code>)</p>\n"
"<p>If you don't have an API key, visit <a href='https://console.x.ai'>console.x.ai</a> to get one for cheap ($5). "
"Simply click the link, then go to 'Create an API key', name the key (e.g. 'PolyCast5'), and click 'Create API key'.</p>\n"
"<p><small>For security, the key is not displayed after saving.</small></p>\n"

"<label>Grok API key</label><input id=key placeholder='xai-...'>\n"
"<p><button id=save_key>Save key</button> <span id=msg_key></span></p>\n"

"<p>Below are the default AI system prompts used across various PolyCast5 applications. Feel free to edit them to tweak responses, create custom commands, or anything else!</p>\n"

"<label>AI Keyboard System Prompt:</label><textarea id=ai_keyboard_prompt></textarea>\n"
"<p><button id=save_ai_keyboard_prompt>Save prompt</button> <span id=msg_prompt></span></p>\n"

"<label>AI Packet Analysis System Prompt:</label><textarea id=pkt_analysis_prompt></textarea>\n"
"<p><button id=save_prompt_pkt_analysis>Save prompt</button> <span id=msg_pkt_analysis_prompt></span></p>\n"

"<script>\n"
"async function load(){\n"
"  let r=await fetch('/api/key');\n"
"  if(r.ok){\n"
"    let j=await r.json();\n"
"    document.getElementById('key').value='';\n"
"    document.getElementById('msg_key').textContent=j.has_key?('Saved (hint: '+(j.key_hint||'')+')'):'No key saved';\n"
"  }\n"
"  let p=await fetch('/api/ai_keyboard_prompt');\n"
"  if(p.ok){\n"
"    let j=await p.json();\n"
"    document.getElementById('ai_keyboard_prompt').value=j.prompt||'';\n"
"  }\n"
"  let pr=await fetch('/api/pkt_analysis_prompt');\n"
"  if(pr.ok){\n"
"    let j=await pr.json();\n"
"    document.getElementById('pkt_analysis_prompt').value=j.prompt||'';\n"
"  }\n"
"}\n"

"async function save_key(){\n"
"  let api_key=document.getElementById('key').value.trim();\n"
"  if(!api_key){document.getElementById('msg_key').textContent='Enter a key';return;}\n"
"  let rk=await fetch('/api/key',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({api_key})});\n"
"  document.getElementById('key').value='';\n"
"  document.getElementById('msg_key').textContent=rk.ok?'Saved!':'Save failed';\n"
"}\n"

"async function save_ai_keyboard_prompt(){\n"
"  let prompt=document.getElementById('ai_keyboard_prompt').value;\n"
"  let rp=await fetch('/api/ai_keyboard_prompt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt})});\n"
"  document.getElementById('msg_prompt').textContent=rp.ok?'Saved!':'Save failed';\n"
"}\n"

"async function save_prompt_pkt_analysis(){\n"
"  let prompt=document.getElementById('pkt_analysis_prompt').value;\n"
"  let rp=await fetch('/api/pkt_analysis_prompt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt})});\n"
"  document.getElementById('msg_pkt_analysis_prompt').textContent=rp.ok?'Saved!':'Save failed';\n"
"}\n"

"document.getElementById('save_key').onclick=save_key;\n"
"document.getElementById('save_ai_keyboard_prompt').onclick=save_ai_keyboard_prompt;\n"
"document.getElementById('save_prompt_pkt_analysis').onclick=save_prompt_pkt_analysis;\n"
"load();\n"
"</script>";
