// AI web portal HTML (single page)
const char *AI_PORTAL_HTML =
"<!doctype html>\n"
"<html lang=\"en\">\n"
"  <head>\n"
"    <meta charset=\"utf-8\" />\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
"    <title>PolyCast5 AI Portal</title>\n"

"    <style>\n"
"      :root {\n"
"        --bg: #060b18;\n"
"        --bg-panel: #0c1528;\n"
"        --border: #1a3068;\n"
"        --accent: #5ba3f5;\n"
"        --accent-dim: #0047ab;\n"
"        --accent-glow: rgba(0,71,171,0.25);\n"
"        --text: #d6dff0;\n"
"        --text-bright: #f0f4fa;\n"
"        --success: #3ddc84;\n"
"        --page-padding: 20px;\n"
"        --label-gap-top: 12px;\n"
"        --label-gap-bottom: 5px;\n"
"        --radius: 4px;\n"
"      }\n"

"      *, *::before, *::after { box-sizing: border-box; }\n"

"      body {\n"
"        font-family: 'Courier New', Courier, monospace;\n"
"        margin: 0;\n"
"        padding: var(--page-padding);\n"
"        background: var(--bg);\n"
"        color: var(--text);\n"
"        line-height: 1.45;\n"
"        max-width: 640px;\n"
"        margin: 0 auto;\n"
"        position: relative;\n"
"      }\n"

"      body::after {\n"
"        content: '';\n"
"        position: fixed;\n"
"        inset: 0;\n"
"        background: repeating-linear-gradient(\n"
"          0deg,\n"
"          transparent,\n"
"          transparent 2px,\n"
"          rgba(0,0,0,0.08) 2px,\n"
"          rgba(0,0,0,0.08) 4px\n"
"        );\n"
"        pointer-events: none;\n"
"        z-index: 9999;\n"
"      }\n"

"      h2 {\n"
"        color: var(--accent);\n"
"        text-transform: uppercase;\n"
"        letter-spacing: 3px;\n"
"        font-size: 1.3em;\n"
"        border-bottom: 2px solid var(--accent-dim);\n"
"        padding-bottom: 10px;\n"
"        text-shadow: 0 0 10px rgba(91,163,245,0.4);\n"
"      }\n"

"      p {\n"
"        font-size: 0.85em;\n"
"        margin: 8px 0;\n"
"      }\n"

"      .small-note {\n"
"        opacity: 0.75;\n"
"        font-size: 0.8em;\n"
"      }\n"

"      a {\n"
"        color: var(--accent);\n"
"        text-decoration: none;\n"
"        border-bottom: 1px dashed var(--accent-dim);\n"
"      }\n"

"      a:hover {\n"
"        color: var(--text-bright);\n"
"      }\n"

"      code {\n"
"        font-family: inherit;\n"
"        background: var(--bg-panel);\n"
"        color: var(--accent);\n"
"        border: 1px solid var(--border);\n"
"        border-radius: 3px;\n"
"        padding: 1px 6px;\n"
"        font-size: 0.95em;\n"
"      }\n"

"      label {\n"
"        display: block;\n"
"        margin: var(--label-gap-top) 0 var(--label-gap-bottom);\n"
"        font-weight: 600;\n"
"        color: var(--accent);\n"
"        text-transform: uppercase;\n"
"        font-size: 0.8em;\n"
"        letter-spacing: 1px;\n"
"      }\n"

"      input, textarea {\n"
"        width: 100%;\n"
"        font: inherit;\n"
"        font-size: 0.9em;\n"
"        background: var(--bg);\n"
"        color: var(--text-bright);\n"
"        border: 1px solid var(--border);\n"
"        border-radius: var(--radius);\n"
"        padding: 8px 10px;\n"
"        outline: none;\n"
"        transition: border-color 0.2s, box-shadow 0.2s;\n"
"      }\n"

"      input:focus, textarea:focus {\n"
"        border-color: var(--accent);\n"
"        box-shadow: 0 0 8px var(--accent-glow), inset 0 0 4px var(--accent-glow);\n"
"      }\n"

"      textarea {\n"
"        height: 240px;\n"
"        resize: vertical;\n"
"      }\n"

"      button {\n"
"        font: inherit;\n"
"        font-size: 0.85em;\n"
"        text-transform: uppercase;\n"
"        letter-spacing: 1px;\n"
"        background: var(--bg-panel);\n"
"        color: var(--accent);\n"
"        border: 1px solid var(--accent-dim);\n"
"        border-radius: var(--radius);\n"
"        padding: 8px 16px;\n"
"        cursor: pointer;\n"
"        transition: all 0.15s;\n"
"      }\n"

"      button:hover {\n"
"        background: var(--accent-dim);\n"
"        color: var(--bg);\n"
"        box-shadow: 0 0 12px var(--accent-glow);\n"
"      }\n"

"      button:active {\n"
"        transform: scale(0.97);\n"
"      }\n"

"      .status {\n"
"        margin-left: 6px;\n"
"        font-weight: 600;\n"
"        color: var(--success);\n"
"        font-size: 0.85em;\n"
"        text-shadow: 0 0 6px rgba(61,220,132,0.3);\n"
"      }\n"

"      hr {\n"
"        border: none;\n"
"        border-top: 1px solid var(--border);\n"
"        margin: 22px 0;\n"
"        box-shadow: 0 1px 0 var(--accent-glow);\n"
"      }\n"

"      ::selection {\n"
"        background: var(--accent);\n"
"        color: var(--bg);\n"
"      }\n"

"      ::-webkit-scrollbar { width: 6px; height: 6px; }\n"
"      ::-webkit-scrollbar-track { background: var(--bg); }\n"
"      ::-webkit-scrollbar-thumb { background: var(--accent-dim); border-radius: 3px; }\n"
"    </style>\n"
"  </head>\n"

"  <body>\n"
"    <h2>PolyCast5 AI Portal</h2>\n"

"    <p>\n"
"      Paste your <strong>Grok (xAI)</strong> API key below and click save.\n"
"      (Typically starts with <code>xai-</code>)\n"
"    </p>\n"
"    <p>\n"
"      If you don't have an API key, visit\n"
"      <a href=\"https://polycast5.com/blogs/docs/ai-keyboard\" target=\"_blank\" rel=\"noopener noreferrer\">polycast5.com/blogs/docs/ai-keyboard</a>\n"
"      for a tutorial on how to get one for cheap ($5). <i>Note: You will need to reconnect to your actual Wi-Fi network first to access the website link.</i>\n"
"    </p>\n"
"    <p class=\"small-note\">For security, the key is not displayed after saving.</p>\n"

"    <div>\n"
"      <label for=\"key\">Grok API key</label>\n"
"      <input id=\"key\" placeholder=\"xai-...\" />\n"
"    </div>\n"
"    <p><button id=\"save_key\" type=\"button\">Save key</button> <span id=\"msg_key\" class=\"status\"></span></p>\n"

"    <hr />\n"

"    <p>\n"
"      Below are the default AI system prompts used across various PolyCast5 applications.\n"
"      Feel free to edit them to tweak responses, create custom commands, or anything else!\n"
"    </p>\n"

"    <div>\n"
"      <label for=\"ai_keyboard_prompt\">AI Keyboard System Prompt</label>\n"
"      <textarea id=\"ai_keyboard_prompt\"></textarea>\n"
"    </div>\n"
"    <p><button id=\"save_ai_keyboard_prompt\" type=\"button\">Save prompt</button> <span id=\"msg_prompt\" class=\"status\"></span></p>\n"

"    <div>\n"
"      <label for=\"pkt_analysis_prompt\">AI Packet Analysis System Prompt</label>\n"
"      <textarea id=\"pkt_analysis_prompt\"></textarea>\n"
"    </div>\n"
"    <p><button id=\"save_prompt_pkt_analysis\" type=\"button\">Save prompt</button> <span id=\"msg_pkt_analysis_prompt\" class=\"status\"></span></p>\n"

"    <script>\n"
"      // -------------------------------\n"
"      // Load existing values\n"
"      // -------------------------------\n"
"      async function load() {\n"
"        try {\n"
"          var r = await fetch('/api/key');\n"
"          if (r.ok) {\n"
"            var j = await r.json();\n"
"            document.getElementById('key').value = '';\n"
"            document.getElementById('msg_key').textContent =\n"
"              j.has_key ? ('Saved (hint: ' + (j.key_hint || '') + ')') : 'No key saved';\n"
"          }\n"
"        } catch (e) { console.error(e); }\n"

"        try {\n"
"          var p = await fetch('/api/ai_keyboard_prompt');\n"
"          if (p.ok) {\n"
"            var jp = await p.json();\n"
"            document.getElementById('ai_keyboard_prompt').value = jp.prompt || '';\n"
"          }\n"
"        } catch (e) { console.error(e); }\n"

"        try {\n"
"          var pr = await fetch('/api/pkt_analysis_prompt');\n"
"          if (pr.ok) {\n"
"            var jpr = await pr.json();\n"
"            document.getElementById('pkt_analysis_prompt').value = jpr.prompt || '';\n"
"          }\n"
"        } catch (e) { console.error(e); }\n"
"      }\n"

"      // -------------------------------\n"
"      // Save handlers\n"
"      // -------------------------------\n"
"      async function saveKey() {\n"
"        var apiKey = document.getElementById('key').value.trim();\n"
"        var msg = document.getElementById('msg_key');\n"

"        if (!apiKey) {\n"
"          msg.textContent = 'Enter a key';\n"
"          return;\n"
"        }\n"

"        try {\n"
"          var r = await fetch('/api/key', {\n"
"            method: 'POST',\n"
"            headers: { 'Content-Type': 'application/json' },\n"
"            body: JSON.stringify({ api_key: apiKey })\n"
"          });\n"
"          document.getElementById('key').value = '';\n"
"          msg.textContent = r.ok ? 'Saved!' : 'Save failed';\n"
"        } catch (e) {\n"
"          msg.textContent = 'Save failed';\n"
"        }\n"
"      }\n"

"      async function saveAiKeyboardPrompt() {\n"
"        var prompt = document.getElementById('ai_keyboard_prompt').value;\n"
"        var msg = document.getElementById('msg_prompt');\n"

"        try {\n"
"          var r = await fetch('/api/ai_keyboard_prompt', {\n"
"            method: 'POST',\n"
"            headers: { 'Content-Type': 'application/json' },\n"
"            body: JSON.stringify({ prompt: prompt })\n"
"          });\n"
"          msg.textContent = r.ok ? 'Saved!' : 'Save failed';\n"
"        } catch (e) {\n"
"          msg.textContent = 'Save failed';\n"
"        }\n"
"      }\n"

"      async function savePktAnalysisPrompt() {\n"
"        var prompt = document.getElementById('pkt_analysis_prompt').value;\n"
"        var msg = document.getElementById('msg_pkt_analysis_prompt');\n"

"        try {\n"
"          var r = await fetch('/api/pkt_analysis_prompt', {\n"
"            method: 'POST',\n"
"            headers: { 'Content-Type': 'application/json' },\n"
"            body: JSON.stringify({ prompt: prompt })\n"
"          });\n"
"          msg.textContent = r.ok ? 'Saved!' : 'Save failed';\n"
"        } catch (e) {\n"
"          msg.textContent = 'Save failed';\n"
"        }\n"
"      }\n"

"      // -------------------------------\n"
"      // Event wiring\n"
"      // -------------------------------\n"
"      document.getElementById('save_key').addEventListener('click', saveKey);\n"
"      document.getElementById('save_ai_keyboard_prompt').addEventListener('click', saveAiKeyboardPrompt);\n"
"      document.getElementById('save_prompt_pkt_analysis').addEventListener('click', savePktAnalysisPrompt);\n"
"      load();\n"
"    </script>\n"
"  </body>\n"
"</html>\n"
;
