// AI web portal HTML (single page)
const char *AI_PORTAL_HTML =
"<!doctype html>\n"
"<html lang=\"en\">\n"
"  <head>\n"
"    <meta charset=\"utf-8\" />\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
"    <title>PolyCast5 AI Portal</title>\n"

"    <style>\n"
"      :root {\n"
"        --bg: #060b18;\n"
"        --bg-panel: #0c1528;\n"
"        --border: #1a3068;\n"
"        --accent: #5ba3f5;\n"
"        --accent-dim: #0047ab;\n"
"        --accent-glow: rgba(0,71,171,0.25);\n"
"        --text: #d6dff0;\n"
"        --text-bright: #f0f4fa;\n"
"        --success: #3ddc84;\n"
"        --danger: #ff5d5d;\n"
"        --page-padding: 20px;\n"
"        --label-gap-top: 12px;\n"
"        --label-gap-bottom: 5px;\n"
"        --radius: 4px;\n"
"      }\n"

"      *, *::before, *::after { box-sizing: border-box; }\n"

"      body {\n"
"        font-family: 'Courier New', Courier, monospace;\n"
"        margin: 0;\n"
"        padding: var(--page-padding);\n"
"        background: var(--bg);\n"
"        color: var(--text);\n"
"        line-height: 1.45;\n"
"        max-width: 640px;\n"
"        margin: 0 auto;\n"
"        position: relative;\n"
"      }\n"

"      body::after {\n"
"        content: '';\n"
"        position: fixed;\n"
"        inset: 0;\n"
"        background: repeating-linear-gradient(\n"
"          0deg,\n"
"          transparent,\n"
"          transparent 2px,\n"
"          rgba(0,0,0,0.08) 2px,\n"
"          rgba(0,0,0,0.08) 4px\n"
"        );\n"
"        pointer-events: none;\n"
"        z-index: 9999;\n"
"      }\n"

"      h2 {\n"
"        color: var(--accent);\n"
"        text-transform: uppercase;\n"
"        letter-spacing: 3px;\n"
"        font-size: 1.3em;\n"
"        border-bottom: 2px solid var(--accent-dim);\n"
"        padding-bottom: 10px;\n"
"        text-shadow: 0 0 10px rgba(91,163,245,0.4);\n"
"      }\n"

"      p {\n"
"        font-size: 0.85em;\n"
"        margin: 8px 0;\n"
"      }\n"

"      .small-note {\n"
"        opacity: 0.75;\n"
"        font-size: 0.8em;\n"
"      }\n"

"      a {\n"
"        color: var(--accent);\n"
"        text-decoration: none;\n"
"        border-bottom: 1px dashed var(--accent-dim);\n"
"      }\n"

"      a:hover {\n"
"        color: var(--text-bright);\n"
"      }\n"

"      code {\n"
"        font-family: inherit;\n"
"        background: var(--bg-panel);\n"
"        color: var(--accent);\n"
"        border: 1px solid var(--border);\n"
"        border-radius: 3px;\n"
"        padding: 1px 6px;\n"
"        font-size: 0.95em;\n"
"      }\n"

"      label {\n"
"        display: block;\n"
"        margin: var(--label-gap-top) 0 var(--label-gap-bottom);\n"
"        font-weight: 600;\n"
"        color: var(--accent);\n"
"        text-transform: uppercase;\n"
"        font-size: 0.8em;\n"
"        letter-spacing: 1px;\n"
"      }\n"

"      input, textarea, select {\n"
"        width: 100%;\n"
"        font: inherit;\n"
"        font-size: 0.9em;\n"
"        background: var(--bg);\n"
"        color: var(--text-bright);\n"
"        border: 1px solid var(--border);\n"
"        border-radius: var(--radius);\n"
"        padding: 8px 10px;\n"
"        outline: none;\n"
"        transition: border-color 0.2s, box-shadow 0.2s;\n"
"      }\n"

"      input:focus, textarea:focus, select:focus {\n"
"        border-color: var(--accent);\n"
"        box-shadow: 0 0 8px var(--accent-glow), inset 0 0 4px var(--accent-glow);\n"
"      }\n"

"      textarea {\n"
"        height: 240px;\n"
"        resize: vertical;\n"
"      }\n"

"      button {\n"
"        font: inherit;\n"
"        font-size: 0.85em;\n"
"        text-transform: uppercase;\n"
"        letter-spacing: 1px;\n"
"        background: var(--bg-panel);\n"
"        color: var(--accent);\n"
"        border: 1px solid var(--accent-dim);\n"
"        border-radius: var(--radius);\n"
"        padding: 8px 16px;\n"
"        cursor: pointer;\n"
"        transition: all 0.15s;\n"
"      }\n"

"      button:hover {\n"
"        background: var(--accent-dim);\n"
"        color: var(--bg);\n"
"        box-shadow: 0 0 12px var(--accent-glow);\n"
"      }\n"

"      button:active {\n"
"        transform: scale(0.97);\n"
"      }\n"

"      .status {\n"
"        margin-left: 6px;\n"
"        font-weight: 600;\n"
"        color: var(--success);\n"
"        font-size: 0.85em;\n"
"        text-shadow: 0 0 6px rgba(61,220,132,0.3);\n"
"      }\n"

"      .status.err {\n"
"        color: var(--danger);\n"
"        text-shadow: 0 0 6px rgba(255,93,93,0.3);\n"
"      }\n"

"      hr {\n"
"        border: none;\n"
"        border-top: 1px solid var(--border);\n"
"        margin: 22px 0;\n"
"        box-shadow: 0 1px 0 var(--accent-glow);\n"
"      }\n"

"      ::selection {\n"
"        background: var(--accent);\n"
"        color: var(--bg);\n"
"      }\n"

"      ::-webkit-scrollbar { width: 6px; height: 6px; }\n"
"      ::-webkit-scrollbar-track { background: var(--bg); }\n"
"      ::-webkit-scrollbar-thumb { background: var(--accent-dim); border-radius: 3px; }\n"
"    </style>\n"
"  </head>\n"

"  <body>\n"
"    <h2>PolyCast5 AI Portal</h2>\n"

"    <p>\n"
"      <strong>Welcome to the AI Portal!</strong>\n"
"    </p>\n"
"    <p>\n"
"      PolyCast5 uses xAI (Grok) by default, since it's low-cost and has built-in speech-to-text under the same API key. However, you can switch to another provider below if needed.\n"
"    </p>\n"
"    <p>\n"
"      If you don't have an API key, visit\n"
"      <a href=\"https://polycast5.com/blogs/docs/ai-keyboard\" target=\"_blank\" rel=\"noopener noreferrer\">polycast5.com/blogs/docs/ai-keyboard</a>\n"
"      for a tutorial on how to get one for cheap ($5), as well as use the various features of the AI Keyboard. <i>Note: You will need to reconnect to your actual Wi-Fi network first to access the website link.</i>\n"
"    </p>\n"
"    <p class=\"small-note\">For security, keys are not displayed after saving.</p>\n"

"    <div>\n"
"      <label for=\"provider\">Chat provider</label>\n"
"      <select id=\"provider\">\n"
"        <option value=\"0\">xAI (Grok)</option>\n"
"        <option value=\"1\">OpenAI</option>\n"
"        <option value=\"2\">Groq</option>\n"
"        <option value=\"3\">DeepSeek</option>\n"
"        <option value=\"4\">OpenRouter</option>\n"
"        <option value=\"5\">Custom / Local</option>\n"
"      </select>\n"
"    </div>\n"

"    <div id=\"cust_url_row\" style=\"display:none\">\n"
"      <label for=\"cust_url\">Custom endpoint URL</label>\n"
"      <input id=\"cust_url\" maxlength=\"255\" placeholder=\"http://192.168.1.50:11434/v1/chat/completions\" />\n"
"    </div>\n"

"    <div>\n"
"      <label for=\"model\">Model</label>\n"
"      <input id=\"model\" maxlength=\"95\" placeholder=\"grok-4.3\" />\n"
"    </div>\n"
"    <p class=\"small-note\">For fast real-time responses, choose a model with quick output. High-reasoning models are noticeably slower and not needed for this basic work.</p>\n"

"    <div>\n"
"      <label for=\"key\">API key</label>\n"
"      <input id=\"key\" maxlength=\"255\" placeholder=\"xai-... / sk-... (leave blank for keyless local)\" />\n"
"    </div>\n"
"    <p class=\"small-note\">Leave blank to keep the saved key. <a href=\"#\" id=\"clear_key\">Erase saved key</a></p>\n"

"    <div>\n"
"      <label style=\"text-transform:none;font-weight:400;letter-spacing:0\"><input type=\"checkbox\" id=\"stt_sep\" style=\"width:auto;margin-right:8px;vertical-align:middle\" />Use a different provider for speech-to-text</label>\n"
"    </div>\n"
"    <div id=\"stt_rows\" style=\"display:none\">\n"
"      <label for=\"stt_prov\">STT provider</label>\n"
"      <select id=\"stt_prov\">\n"
"        <option value=\"0\">xAI (Grok)</option>\n"
"        <option value=\"1\">OpenAI (Whisper)</option>\n"
"        <option value=\"2\">Groq (Whisper)</option>\n"
"      </select>\n"
"      <label for=\"stt_model\">STT model</label>\n"
"      <input id=\"stt_model\" maxlength=\"95\" placeholder=\"grok-stt\" />\n"
"      <label for=\"stt_key\">STT API key</label>\n"
"      <input id=\"stt_key\" maxlength=\"255\" placeholder=\"key for the STT provider\" />\n"
"      <p class=\"small-note\">A key is required when the STT provider differs from your chat provider; when they match, the chat key is used automatically. Leave blank to keep the saved STT key. <a href=\"#\" id=\"clear_stt_key\">Erase saved STT key</a></p>\n"
"    </div>\n"

"    <p><button id=\"save_provider\" type=\"button\">Save AI settings</button> <span id=\"msg_provider\" class=\"status\"></span></p>\n"

"    <hr />\n"

"    <p>\n"
"      Below are the default AI system prompts used across various PolyCast5 applications.\n"
"      Feel free to edit them to tweak responses, create custom commands, or anything else!\n"
"      <i>A tutorial is also <a href=\"https://polycast5.com/blogs/docs/customize-system-prompts-ai-keyboard\" target=\"_blank\" rel=\"noopener noreferrer\">available here.</a></i>\n"
"    </p>\n"

"    <div>\n"
"      <label for=\"ai_keyboard_prompt\">AI Keyboard System Prompt</label>\n"
"      <textarea id=\"ai_keyboard_prompt\"></textarea>\n"
"    </div>\n"
"    <p><button id=\"save_ai_keyboard_prompt\" type=\"button\">Save prompt</button> <span id=\"msg_prompt\" class=\"status\"></span></p>\n"

"    <div>\n"
"      <label for=\"pkt_analysis_prompt\">AI Packet Analysis System Prompt</label>\n"
"      <textarea id=\"pkt_analysis_prompt\"></textarea>\n"
"    </div>\n"
"    <p><button id=\"save_prompt_pkt_analysis\" type=\"button\">Save prompt</button> <span id=\"msg_pkt_analysis_prompt\" class=\"status\"></span></p>\n"

"    <script>\n"
"      var CHAT_MODELS = {0:'grok-4.3',1:'gpt-4o',2:'openai/gpt-oss-120b',3:'deepseek-v4-flash',4:'anthropic/claude-sonnet-4.5',5:''};\n"
"      var STT_MODELS = {0:'grok-stt',1:'whisper-1',2:'whisper-large-v3-turbo'};\n"
"      var NO_STT = {3:1,4:1,5:1}; // Chat-only providers (mirrors has_stt=false in ai_provider.c)\n"
"      var HAS_KEY = false; // Whether a primary API key is saved on the device (from /api/key)\n"

"      function setOk(msg, text) { msg.className = 'status'; msg.textContent = text; }\n"
"      function setErr(msg, text) { msg.className = 'status err'; msg.textContent = text; }\n"

"      function onProviderChange(prefillModel) {\n"
"        var idx = document.getElementById('provider').value;\n"
"        document.getElementById('cust_url_row').style.display = (idx === '5') ? 'block' : 'none';\n"
"        if (prefillModel) { document.getElementById('model').value = CHAT_MODELS[idx] || ''; }\n"
"      }\n"

"      function onSttToggle() {\n"
"        document.getElementById('stt_rows').style.display =\n"
"          document.getElementById('stt_sep').checked ? 'block' : 'none';\n"
"      }\n"

"      function onSttProvChange(prefillModel) {\n"
"        if (prefillModel) { document.getElementById('stt_model').value = STT_MODELS[document.getElementById('stt_prov').value] || ''; }\n"
"      }\n"

"      // -------------------------------\n"
"      // Load existing values\n"
"      // -------------------------------\n"
"      // Key + provider state only. A settings/key save refreshes THIS (not the prompt\n"
"      // textareas), so a save never clobbers unsaved prompt edits.\n"
"      async function loadSettings() {\n"
"        try {\n"
"          var r = await fetch('/api/key');\n"
"          if (r.ok) {\n"
"            var j = await r.json();\n"
"            HAS_KEY = !!j.has_key;\n"
"            document.getElementById('key').placeholder = j.has_key\n"
"              ? ('saved: ' + (j.key_hint || '') + ' (blank = keep)')\n"
"              : 'xai-... / sk-... (leave blank for keyless local)';\n"
"          }\n"
"        } catch (e) { console.error(e); }\n"

"        try {\n"
"          var rp = await fetch('/api/provider');\n"
"          if (rp.ok) {\n"
"            var jp = await rp.json();\n"
"            document.getElementById('provider').value = String(jp.chat_prov || 0);\n"
"            document.getElementById('model').value = jp.chat_model || CHAT_MODELS[jp.chat_prov || 0] || '';\n"
"            document.getElementById('cust_url').value = jp.cust_url || '';\n"
"            document.getElementById('stt_sep').checked = !!jp.stt_sep;\n"
"            document.getElementById('stt_prov').value = String(jp.stt_prov || 0);\n"
"            document.getElementById('stt_model').value = jp.stt_model || STT_MODELS[jp.stt_prov || 0] || '';\n"
"            document.getElementById('stt_key').placeholder = jp.has_stt_key\n"
"              ? ('saved: ' + (jp.stt_key_hint || '') + ' (blank = keep)')\n"
"              : 'key for the STT provider';\n"
"            onProviderChange(false);\n"
"            onSttToggle();\n"
"          }\n"
"        } catch (e) { console.error(e); }\n"
"      }\n"

"      // Prompt textareas load separately, only on the initial page load, so they are\n"
"      // never overwritten by a settings/key save.\n"
"      async function loadPrompts() {\n"
"        try {\n"
"          var p = await fetch('/api/ai_keyboard_prompt');\n"
"          if (p.ok) {\n"
"            var jp = await p.json();\n"
"            document.getElementById('ai_keyboard_prompt').value = jp.prompt || '';\n"
"          }\n"
"        } catch (e) { console.error(e); }\n"

"        try {\n"
"          var pr = await fetch('/api/pkt_analysis_prompt');\n"
"          if (pr.ok) {\n"
"            var jpr = await pr.json();\n"
"            document.getElementById('pkt_analysis_prompt').value = jpr.prompt || '';\n"
"          }\n"
"        } catch (e) { console.error(e); }\n"
"      }\n"

"      // Full initial page load: settings + prompts together\n"
"      async function load() { await loadSettings(); await loadPrompts(); }\n"

"      // -------------------------------\n"
"      // Save handlers\n"
"      // -------------------------------\n"
"      // Everything (provider + model + keys) goes in ONE request so the device never ends up\n"
"      // with a new key applied against the old provider.\n"
"      function buildBody() {\n"
"        return {\n"
"          chat_prov: parseInt(document.getElementById('provider').value, 10),\n"
"          model: document.getElementById('model').value.trim(),\n"
"          custom_url: document.getElementById('cust_url').value.trim(),\n"
"          stt_sep: document.getElementById('stt_sep').checked ? 1 : 0,\n"
"          stt_prov: parseInt(document.getElementById('stt_prov').value, 10),\n"
"          stt_model: document.getElementById('stt_model').value.trim()\n"
"        };\n"
"      }\n"

"      // Mirror the firmware's custom-provider checks so we never POST a request we know fails\n"
"      // (case-sensitive scheme match, same as the firmware's strncmp)\n"
"      function preflight(msg) {\n"
"        if (document.getElementById('provider').value === '5') {\n"
"          var u = document.getElementById('cust_url').value.trim();\n"
"          if (!/^https?:\\/\\//.test(u)) {\n"
"            setErr(msg, 'Custom URL must start with http:// or https://');\n"
"            return false;\n"
"          }\n"
"          if (!document.getElementById('model').value.trim()) {\n"
"            setErr(msg, 'Model is required for a custom provider');\n"
"            return false;\n"
"          }\n"
"        }\n"
"        return true;\n"
"      }\n"

"      // clearOnly: an erase action - update just the affected key field so the user's\n"
"      // pending form edits (provider/model/typed keys) are left untouched\n"
"      async function postSettings(body, msg, okText, clearOnly) {\n"
"        try {\n"
"          var r = await fetch('/api/provider', {\n"
"            method: 'POST',\n"
"            headers: { 'Content-Type': 'application/json' },\n"
"            body: JSON.stringify(body)\n"
"          });\n"
"          if (r.ok) {\n"
"            if (clearOnly) {\n"
"              if (body.clear_key) {\n"
"                var k = document.getElementById('key');\n"
"                k.value = '';\n"
"                k.placeholder = 'xai-... / sk-... (leave blank for keyless local)';\n"
"                HAS_KEY = false;\n"
"              }\n"
"              if (body.clear_stt_key) {\n"
"                var s = document.getElementById('stt_key');\n"
"                s.value = '';\n"
"                s.placeholder = 'key for the STT provider';\n"
"              }\n"
"              setOk(msg, okText);\n"
"              return;\n"
"            }\n"
"            document.getElementById('key').value = '';\n"
"            document.getElementById('stt_key').value = '';\n"
"            setOk(msg, okText);\n"
"            await loadSettings();\n"
"          } else {\n"
"            var t = '';\n"
"            try { t = await r.text(); } catch (e) {}\n"
"            setErr(msg, 'Save failed' + (t ? (': ' + t) : ''));\n"
"          }\n"
"        } catch (e) {\n"
"          setErr(msg, 'Save failed: no response from the device');\n"
"        }\n"
"      }\n"

"      async function saveAiSettings() {\n"
"        var msg = document.getElementById('msg_provider');\n"
"        if (!preflight(msg)) { return; }\n"
"        setOk(msg, 'Saving...');\n"
"        var body = buildBody();\n"
"        var k = document.getElementById('key').value.trim();\n"
"        if (k) { body.api_key = k; }\n"
"        // Only send the STT key when separate STT is enabled - a value typed and then\n"
"        // abandoned behind the unchecked box must not be saved\n"
"        if (document.getElementById('stt_sep').checked) {\n"
"          var sk = document.getElementById('stt_key').value.trim();\n"
"          if (sk) { body.stt_key = sk; }\n"
"        }\n"
"        var notes = [];\n"
"        if (NO_STT[body.chat_prov] && !body.stt_sep) {\n"
"          notes.push('this provider has no speech-to-text, so voice dictation stays off until you enable a separate STT provider above');\n"
"        }\n"
"        if (!body.api_key && !HAS_KEY && body.chat_prov !== 5) {\n"
"          notes.push('no API key is saved yet - paste one above and save again');\n"
"        }\n"
"        var okText = notes.length ? ('Saved! Note: ' + notes.join('. Also, ') + '.') : 'Saved!';\n"
"        await postSettings(body, msg, okText);\n"
"      }\n"

"      // The erase links send minimal clear-only bodies: pending form edits are neither\n"
"      // validated (an invalid custom URL must not block erasing a key) nor saved\n"
"      async function clearKey() {\n"
"        var msg = document.getElementById('msg_provider');\n"
"        if (!confirm('Erase the saved API key from the device?')) { return; }\n"
"        setOk(msg, 'Clearing...');\n"
"        await postSettings({ clear_key: 1 }, msg, 'API key cleared', true);\n"
"      }\n"

"      async function clearSttKey() {\n"
"        var msg = document.getElementById('msg_provider');\n"
"        if (!confirm('Erase the saved STT key from the device?')) { return; }\n"
"        setOk(msg, 'Clearing...');\n"
"        var okText = 'STT key cleared';\n"
"        if (document.getElementById('stt_sep').checked &&\n"
"            document.getElementById('stt_prov').value !== document.getElementById('provider').value) {\n"
"          okText = 'STT key cleared - voice dictation needs a new key for the separate STT provider';\n"
"        }\n"
"        await postSettings({ clear_stt_key: 1 }, msg, okText, true);\n"
"      }\n"

"      async function saveAiKeyboardPrompt() {\n"
"        var prompt = document.getElementById('ai_keyboard_prompt').value;\n"
"        var msg = document.getElementById('msg_prompt');\n"

"        try {\n"
"          var r = await fetch('/api/ai_keyboard_prompt', {\n"
"            method: 'POST',\n"
"            headers: { 'Content-Type': 'application/json' },\n"
"            body: JSON.stringify({ prompt: prompt })\n"
"          });\n"
"          if (r.ok) { setOk(msg, 'Saved!'); } else { setErr(msg, 'Save failed'); }\n"
"        } catch (e) {\n"
"          setErr(msg, 'Save failed: no response from the device');\n"
"        }\n"
"      }\n"

"      async function savePktAnalysisPrompt() {\n"
"        var prompt = document.getElementById('pkt_analysis_prompt').value;\n"
"        var msg = document.getElementById('msg_pkt_analysis_prompt');\n"

"        try {\n"
"          var r = await fetch('/api/pkt_analysis_prompt', {\n"
"            method: 'POST',\n"
"            headers: { 'Content-Type': 'application/json' },\n"
"            body: JSON.stringify({ prompt: prompt })\n"
"          });\n"
"          if (r.ok) { setOk(msg, 'Saved!'); } else { setErr(msg, 'Save failed'); }\n"
"        } catch (e) {\n"
"          setErr(msg, 'Save failed: no response from the device');\n"
"        }\n"
"      }\n"

"      // -------------------------------\n"
"      // Event wiring\n"
"      // -------------------------------\n"
"      document.getElementById('provider').addEventListener('change', function () { onProviderChange(true); });\n"
"      document.getElementById('stt_sep').addEventListener('change', onSttToggle);\n"
"      document.getElementById('stt_prov').addEventListener('change', function () { onSttProvChange(true); });\n"
"      document.getElementById('save_provider').addEventListener('click', saveAiSettings);\n"
"      document.getElementById('clear_key').addEventListener('click', function (ev) { ev.preventDefault(); clearKey(); });\n"
"      document.getElementById('clear_stt_key').addEventListener('click', function (ev) { ev.preventDefault(); clearSttKey(); });\n"
"      document.getElementById('save_ai_keyboard_prompt').addEventListener('click', saveAiKeyboardPrompt);\n"
"      document.getElementById('save_prompt_pkt_analysis').addEventListener('click', savePktAnalysisPrompt);\n"
"      load();\n"
"    </script>\n"
"  </body>\n"
"</html>\n"
;
