// Meshtastic web portal HTML (single page)
// Meshy / techy LoRa theme: animated mesh-node network, radio-wave pulses, cobalt-blue glow
//
// The portal is purely a text-entry surface: the browser POSTs the raw message
// text to /api/send and polls /api/messages for the running conversation. The
// device does all the real Meshtastic framing/transmit on its built-in LoRa radio.
// The page fills the viewport so the chat log is the only thing that scrolls.
const char *LORA_MESHTASTIC_PORTAL_HTML =
"<!doctype html>\n"
"<html lang=\"en\">\n"
"  <head>\n"
"    <meta charset=\"utf-8\" />\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1, viewport-fit=cover\" />\n"
"    <meta name=\"theme-color\" content=\"#0a1730\" />\n"
"    <title>PolyCast5 &middot; Meshtastic</title>\n"
"    <style>\n"
"      :root {\n"
"        --bg: #060b18;\n"
"        --bg-2: #0a1730;\n"
"        --panel: rgba(12, 21, 40, 0.78);\n"
"        --border: #1a3068;\n"
"        --accent: #5ba3f5;\n"
"        --accent-2: #3b82f6;\n"
"        --accent-dim: #0047ab;\n"
"        --glow: rgba(59, 130, 246, 0.35);\n"
"        --text: #d6dff0;\n"
"        --text-bright: #f0f4fa;\n"
"        --muted: #7488ac;\n"
"        --good: #46d17a;\n"
"      }\n"
"      * { box-sizing: border-box; }\n"
"      html, body { margin: 0; background: #0a1730; overscroll-behavior: none; }\n"
"      body {\n"
"        font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif;\n"
"        color: var(--text); min-height: 100dvh; background-color: #0a1730;\n"
"        -webkit-font-smoothing: antialiased;\n"
"      }\n"
"      body::before {\n"
"        content: \"\"; position: fixed; inset: 0; z-index: -1; pointer-events: none;\n"
"        background: radial-gradient(1100px 560px at 50% 30%, rgba(0,71,171,0.12), transparent 70%);\n"
"      }\n"
"      .wrap { max-width: 560px; width: 100%; margin: 0 auto; min-height: 100dvh; display: flex; flex-direction: column; }\n"
"      .topbar { position: sticky; top: 0; z-index: 3; background: #0a1730; padding: calc(env(safe-area-inset-top) + 4px) 14px 8px; box-shadow: 0 10px 20px -8px rgba(4,9,20,0.7); }\n"
"      .hero { position: relative; flex: 0 0 auto; height: 80px; margin: 2px 0 10px; }\n"
"      .net { position: absolute; inset: 0; width: 100%; height: 100%; }\n"
"      .net .links line { stroke: rgba(91,163,245,0.22); stroke-width: 0.5; }\n"
"      .net .halo { fill: none; stroke: var(--accent); stroke-width: 0.7; opacity: 0.28; animation: haloBreath 4.5s ease-in-out infinite; }\n"
"      .net .node { fill: #e6f0ff; filter: drop-shadow(0 0 2.5px rgba(91,163,245,0.8)); animation: nodeBreath 4.5s ease-in-out infinite; }\n"
"      .net .halos circle:nth-child(2n), .net .nodes circle:nth-child(2n) { animation-delay: -2.2s; }\n"
"      .net .pkt { fill: #cfe4ff; filter: drop-shadow(0 0 2px var(--accent)); }\n"
"      @keyframes nodeBreath { 0%,100% { opacity: 0.72; } 50% { opacity: 1; } }\n"
"      @keyframes haloBreath { 0%,100% { opacity: 0.16; } 50% { opacity: 0.42; } }\n"
"      @media (prefers-reduced-motion: reduce) { .net .node, .net .halo { animation: none; } .net .pkt { display: none; } }\n"
"      .composer { position: sticky; bottom: 0; z-index: 3; background: #0a1730; padding: 8px 14px calc(env(safe-area-inset-bottom) + 10px); box-shadow: 0 -10px 20px -8px rgba(4,9,20,0.7); }\n"
"      .head { flex: 0 0 auto; display: flex; align-items: baseline; justify-content: space-between; gap: 10px; margin-bottom: 10px; }\n"
"      h1 { margin: 0; font-size: 1.15rem; color: var(--text-bright); letter-spacing: -0.01em; }\n"
"      h1 span { color: var(--accent); }\n"
"      .sub { font: 600 10px/1 ui-monospace, Menlo, monospace; letter-spacing: 0.14em; text-transform: uppercase; color: var(--muted); white-space: nowrap; }\n"
"      .sub b { color: var(--accent); font-weight: 700; }\n"
"      .netinfo { margin: 7px 0 0; font: 600 10px/1.4 ui-monospace, Menlo, monospace; letter-spacing: 0.05em; color: var(--muted); word-spacing: 0.05em; }\n"
"      .warn { margin: 5px 0 0; font-size: 0.72rem; line-height: 1.35; color: #e6b45e; opacity: 0.92; }\n"
"      .pill { flex: 0 0 auto; background: rgba(59,130,246,0.14); border: 1px solid var(--accent-dim); color: var(--accent); font: 700 11px/1 ui-monospace, Menlo, monospace; padding: 6px 11px; border-radius: 999px; cursor: pointer; white-space: nowrap; }\n"
"      .pill.on { background: var(--accent); color: #041022; border-color: var(--accent); }\n"
"      .headr { display: flex; align-items: center; gap: 10px; }\n"
"      #nodes { display: none; }\n"
"      #nodes.open { display: block; max-height: 42vh; overflow-y: auto; -webkit-overflow-scrolling: touch; padding: 4px 14px 10px; background: rgba(4,9,20,0.55); border-bottom: 1px solid var(--border); }\n"
"      .node { display: flex; align-items: center; gap: 10px; padding: 8px 2px; border-bottom: 1px solid rgba(26,48,104,0.4); }\n"
"      .node:last-child { border-bottom: 0; }\n"
"      .nbadge { flex: 0 0 auto; width: 40px; height: 40px; border-radius: 10px; display: grid; place-items: center; background: rgba(59,130,246,0.16); border: 1px solid var(--accent-dim); color: var(--accent); font: 700 12px/1 ui-monospace, Menlo, monospace; overflow: hidden; }\n"
"      .ninfo { flex: 1; min-width: 0; }\n"
"      .nname { color: var(--text-bright); font-size: 0.92rem; font-weight: 600; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }\n"
"      .nmeta { font: 600 10px/1.3 ui-monospace, Menlo, monospace; color: var(--muted); margin-top: 2px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }\n"
"      .nempty { color: var(--muted); font-size: 0.85rem; text-align: center; padding: 16px 8px; }\n"
"      .log {\n"
"        flex: 1; display: flex; flex-direction: column; justify-content: flex-end; gap: 8px;\n"
"        padding: 14px;\n"
"      }\n"
"      .empty { margin: auto; color: var(--muted); font-size: 0.9rem; text-align: center; padding: 0 16px; }\n"
"      .bubble { max-width: 84%; padding: 7px 11px; border-radius: 12px; line-height: 1.4; }\n"
"      .bubble .meta {\n"
"        font: 600 10px/1.3 ui-monospace, Menlo, monospace; letter-spacing: 0.03em;\n"
"        text-transform: uppercase; color: var(--muted); margin-bottom: 3px;\n"
"      }\n"
"      .bubble .txt { color: var(--text-bright); word-wrap: break-word; overflow-wrap: anywhere; white-space: pre-wrap; }\n"
"      .bubble.in { align-self: flex-start; background: rgba(26,48,104,0.5); border: 1px solid var(--border); }\n"
"      .bubble.out { align-self: flex-end; background: rgba(59,130,246,0.16); border: 1px solid var(--accent-dim); }\n"
"      .bubble.out .meta { text-align: right; }\n"
"      .bubble .meta .age { opacity: 0.8; }\n"
"      .row { flex: 0 0 auto; display: flex; gap: 8px; }\n"
"      #msg {\n"
"        flex: 1; min-width: 0; padding: 11px 12px; border-radius: 12px; color: var(--text-bright);\n"
"        background: rgba(4,9,20,0.7); border: 1px solid var(--border); font-size: 1rem; outline: none;\n"
"      }\n"
"      #msg:focus { border-color: var(--accent); box-shadow: 0 0 0 2px var(--glow); }\n"
"      #send {\n"
"        padding: 0 18px; border: 0; border-radius: 12px; color: #041022; font-weight: 700; cursor: pointer;\n"
"        background: linear-gradient(160deg, var(--accent), var(--accent-2)); font-size: 0.95rem;\n"
"      }\n"
"      #send:disabled { opacity: 0.5; cursor: default; }\n"
"      .status { flex: 0 0 auto; min-height: 8px; margin: 4px 2px 0; font-size: 0.78rem; color: var(--muted); }\n"
"      .status.err { color: #f2757a; }\n"
"      .note { flex: 0 0 auto; margin: 6px 2px 0; font-size: 0.72rem; line-height: 1.35; color: var(--muted); opacity: 0.8; }\n"
"      .hint { flex: 0 0 auto; margin: 5px 2px 0; font-size: 0.72rem; color: var(--muted); opacity: 0.75; font-style: italic; }\n"
"    </style>\n"
"  </head>\n"
"  <body>\n"
"    <div class=\"wrap\">\n"
"      <div class=\"topbar\">\n"
"      <div class=\"hero\">\n"
"        <svg class=\"net\" viewBox=\"0 0 300 54\" preserveAspectRatio=\"xMidYMid slice\">\n"
"          <g class=\"links\">\n"
"            <line x1=\"30\" y1=\"20\" x2=\"150\" y2=\"12\" />\n"
"            <line x1=\"150\" y1=\"12\" x2=\"272\" y2=\"19\" />\n"
"            <line x1=\"30\" y1=\"20\" x2=\"92\" y2=\"42\" />\n"
"            <line x1=\"92\" y1=\"42\" x2=\"212\" y2=\"43\" />\n"
"            <line x1=\"212\" y1=\"43\" x2=\"272\" y2=\"19\" />\n"
"            <line x1=\"150\" y1=\"12\" x2=\"92\" y2=\"42\" />\n"
"            <line x1=\"150\" y1=\"12\" x2=\"212\" y2=\"43\" />\n"
"          </g>\n"
"          <circle class=\"pkt\" r=\"1.5\"><animateMotion dur=\"2.6s\" begin=\"0s\" repeatCount=\"indefinite\" path=\"M30,20 L150,12\" /><animate attributeName=\"opacity\" dur=\"2.6s\" begin=\"0s\" repeatCount=\"indefinite\" values=\"0;1;1;0\" keyTimes=\"0;0.25;0.75;1\" /></circle>\n"
"          <circle class=\"pkt\" r=\"1.5\"><animateMotion dur=\"2.2s\" begin=\"0.7s\" repeatCount=\"indefinite\" path=\"M150,12 L272,19\" /><animate attributeName=\"opacity\" dur=\"2.2s\" begin=\"0.7s\" repeatCount=\"indefinite\" values=\"0;1;1;0\" keyTimes=\"0;0.25;0.75;1\" /></circle>\n"
"          <circle class=\"pkt\" r=\"1.5\"><animateMotion dur=\"2.8s\" begin=\"1.2s\" repeatCount=\"indefinite\" path=\"M92,42 L212,43\" /><animate attributeName=\"opacity\" dur=\"2.8s\" begin=\"1.2s\" repeatCount=\"indefinite\" values=\"0;1;1;0\" keyTimes=\"0;0.25;0.75;1\" /></circle>\n"
"          <circle class=\"pkt\" r=\"1.5\"><animateMotion dur=\"2.4s\" begin=\"1.8s\" repeatCount=\"indefinite\" path=\"M212,43 L272,19\" /><animate attributeName=\"opacity\" dur=\"2.4s\" begin=\"1.8s\" repeatCount=\"indefinite\" values=\"0;1;1;0\" keyTimes=\"0;0.25;0.75;1\" /></circle>\n"
"          <circle class=\"pkt\" r=\"1.5\"><animateMotion dur=\"3s\" begin=\"0.4s\" repeatCount=\"indefinite\" path=\"M150,12 L92,42\" /><animate attributeName=\"opacity\" dur=\"3s\" begin=\"0.4s\" repeatCount=\"indefinite\" values=\"0;1;1;0\" keyTimes=\"0;0.25;0.75;1\" /></circle>\n"
"          <g class=\"halos\">\n"
"            <circle class=\"halo\" cx=\"30\" cy=\"20\" r=\"4\" />\n"
"            <circle class=\"halo\" cx=\"150\" cy=\"12\" r=\"4.6\" />\n"
"            <circle class=\"halo\" cx=\"272\" cy=\"19\" r=\"4\" />\n"
"            <circle class=\"halo\" cx=\"92\" cy=\"42\" r=\"3.6\" />\n"
"            <circle class=\"halo\" cx=\"212\" cy=\"43\" r=\"3.8\" />\n"
"          </g>\n"
"          <g class=\"nodes\">\n"
"            <circle class=\"node\" cx=\"30\" cy=\"20\" r=\"2.2\" />\n"
"            <circle class=\"node\" cx=\"150\" cy=\"12\" r=\"2.6\" />\n"
"            <circle class=\"node\" cx=\"272\" cy=\"19\" r=\"2.2\" />\n"
"            <circle class=\"node\" cx=\"92\" cy=\"42\" r=\"2\" />\n"
"            <circle class=\"node\" cx=\"212\" cy=\"43\" r=\"2.1\" />\n"
"          </g>\n"
"        </svg>\n"
"      </div>\n"
"        <div class=\"head\">\n"
"          <h1>PolyCast5 <span>Meshtastic</span></h1>\n"
"          <div class=\"headr\">\n"
"            <div class=\"sub\">Node <b id=\"node\">&hellip;</b></div>\n"
"            <button id=\"nodesBtn\" class=\"pill\" type=\"button\">Nodes <b id=\"nodesN\">0</b></button>\n"
"          </div>\n"
"        </div>\n"
;

// The RF-info banner (region-dependent frequency) sits between HEAD and TAIL and
// is emitted at runtime by root_get() in lora_meshtastic_portal.c, so the served
// frequency tracks the active LoRa region (US 906.875 MHz / EU_868 869.525 MHz).
const char *LORA_MESHTASTIC_PORTAL_HTML_TAIL =
"        <div class=\"netinfo\">Using default PSK: 1PG7OiApB1nwvP+rz05pAQ==</div>\n"
"      </div>\n"
"      <div class=\"nodes\" id=\"nodes\"></div>\n"
"      <div class=\"log\" id=\"log\">\n"
"        <div class=\"empty\" id=\"empty\">No messages yet. Say hello to the mesh below.</div>\n"
"      </div>\n"
"      <div class=\"composer\">\n"
"        <div class=\"row\">\n"
"          <input id=\"msg\" type=\"text\" maxlength=\"200\" autocomplete=\"off\"\n"
"                 placeholder=\"Type a message for the mesh...\" />\n"
"          <button id=\"send\">Send</button>\n"
"        </div>\n"
"        <div class=\"hint\">*There may not be any other nodes nearby.</div>\n"
"        <div class=\"status\" id=\"status\"></div>\n"
"        <div class=\"note\">Note: This device is only used for user input. All messages are sent and received through the LoRa radio on your PolyCast5.</div>\n"
"      </div>\n"
"    </div>\n"
"    <script>\n"
"      var since = 0;\n"
"      var seen = {};\n"
"      var log = document.getElementById('log');\n"
"      var empty = document.getElementById('empty');\n"
"      var input = document.getElementById('msg');\n"
"      var btn = document.getElementById('send');\n"
"      var nodeEl = document.getElementById('node');\n"
"      var statusEl = document.getElementById('status');\n"
"      var nodesBtn = document.getElementById('nodesBtn');\n"
"      var nodesN = document.getElementById('nodesN');\n"
"      var nodesPanel = document.getElementById('nodes');\n"
"      var nodesOpen = false;\n"
"      var pendingSend = 0;\n"
"      var sending = false;\n"
"\n"
"      function setStatus(t, isErr) {\n"
"        statusEl.textContent = t || '';\n"
"        statusEl.className = 'status' + (isErr ? ' err' : '');\n"
"      }\n"
"\n"
"      function atBottom() {\n"
"        return (window.innerHeight + window.scrollY) >= (document.documentElement.scrollHeight - 60);\n"
"      }\n"
"\n"
"      // Blend red -> yellow -> green. lo maps to red, hi maps to green.\n"
"      function sigColor(v, lo, hi) {\n"
"        var t = (v - lo) / (hi - lo);\n"
"        t = t < 0 ? 0 : (t > 1 ? 1 : t);\n"
"        return 'hsl(' + Math.round(t * 120) + ', 80%, 58%)';\n"
"      }\n"
"\n"
"      // Relative time since we first saw the message (no node RTC available).\n"
"      function relTime(t) {\n"
"        var s = Math.floor((Date.now() - t) / 1000);\n"
"        if (s < 45) return 'just now';\n"
"        var mn = Math.floor(s / 60);\n"
"        if (mn < 60) return mn + 'm ago';\n"
"        var h = Math.floor(mn / 60);\n"
"        if (h < 24) return h + 'h ago';\n"
"        return Math.floor(h / 24) + 'd ago';\n"
"      }\n"
"\n"
"      // Node last-heard age arrives from the device in whole seconds.\n"
"      function fmtAge(sec) {\n"
"        if (sec < 45) return 'just now';\n"
"        var m = Math.floor(sec / 60);\n"
"        if (m < 60) return m + 'm ago';\n"
"        var h = Math.floor(m / 60);\n"
"        if (h < 24) return h + 'h ago';\n"
"        return Math.floor(h / 24) + 'd ago';\n"
"      }\n"
"\n"
"      // Key on (sender, id) like the Meshtastic firmware dedups, not id alone.\n"
"      function keyOf(m) { return m.id ? ('i' + m.from + '_' + m.id) : ('s' + m.seq); }\n"
"\n"
"      function fillMeta(meta, m) {\n"
"        meta.textContent = '';\n"
"        var t = (meta.parentNode && meta.parentNode._t) || Date.now();\n"
"        if (m.out) {\n"
"          var you = document.createElement('span');\n"
"          you.textContent = 'You  ';\n"
"          you.style.color = 'var(--accent)';\n"
"          meta.appendChild(you);\n"
"          var st = document.createElement('span');\n"
"          st.textContent = m.failed ? 'Not sent' : (m.acked ? 'Delivered' : 'Sent');\n"
"          st.style.color = m.failed ? '#f2757a' : (m.acked ? 'var(--good)' : 'var(--muted)');\n"
"          st.style.fontWeight = '700';\n"
"          meta.appendChild(st);\n"
"        } else {\n"
"          var who = document.createElement('span');\n"
"          who.textContent = m.from + '  ';\n"
"          meta.appendChild(who);\n"
"          var r = document.createElement('span');\n"
"          r.textContent = m.rssi + 'dBm';\n"
"          r.style.color = sigColor(m.rssi, -120, -55);\n"
"          meta.appendChild(r);\n"
"          var sep = document.createElement('span');\n"
"          sep.textContent = ' / ';\n"
"          meta.appendChild(sep);\n"
"          var s = document.createElement('span');\n"
"          s.textContent = m.snr + 'dB';\n"
"          s.style.color = sigColor(m.snr, -17, 10);\n"
"          meta.appendChild(s);\n"
"          var hop = document.createElement('span');\n"
"          hop.textContent = ' \\u00b7 ' + (m.hops ? (m.hops + (m.hops === 1 ? ' hop' : ' hops')) : 'direct');\n"
"          meta.appendChild(hop);\n"
"        }\n"
"        var age = document.createElement('span');\n"
"        age.className = 'age';\n"
"        age.textContent = ' \\u00b7 ' + relTime(t);\n"
"        meta.appendChild(age);\n"
"      }\n"
"\n"
"      function renderMsg(m) {\n"
"        var k = keyOf(m);\n"
"        var existing = seen[k];\n"
"        if (existing) { fillMeta(existing.firstChild, m); return; } // status/signal update in place\n"
"        if (empty) { empty.remove(); empty = null; }\n"
"        var wrap = document.createElement('div');\n"
"        wrap.className = 'bubble ' + (m.out ? 'out' : 'in');\n"
"        wrap._t = Date.now();   // first-seen time for the relative clock\n"
"        var meta = document.createElement('div');\n"
"        meta.className = 'meta';\n"
"        var body = document.createElement('div');\n"
"        body.className = 'txt';\n"
"        body.textContent = m.text;\n"
"        wrap.appendChild(meta);\n"
"        wrap.appendChild(body);\n"
"        fillMeta(meta, m);\n"
"        log.appendChild(wrap);\n"
"        seen[k] = wrap;\n"
"        if (m.out && pendingSend > 0) { pendingSend--; if (pendingSend === 0) setStatus(''); }\n"
"      }\n"
"\n"
"      async function poll() {\n"
"        try {\n"
"          var r = await fetch('/api/messages?since=' + since, { cache: 'no-store' });\n"
"          if (!r.ok) return;\n"
"          var d = await r.json();\n"
"          if (d.node && nodeEl.textContent !== d.node) nodeEl.textContent = d.node;\n"
"          if (typeof d.nodes === 'number') nodesN.textContent = d.nodes;\n"
"          var stick = atBottom();\n"
"          if (d.msgs) { for (var i = 0; i < d.msgs.length; i++) renderMsg(d.msgs[i]); }\n"
"          if (typeof d.newest === 'number') since = d.newest;   // follow the server so the cursor re-syncs after a device reboot\n"
"          if (stick) window.scrollTo(0, document.documentElement.scrollHeight);\n"
"        } catch (e) { /* transient; try again next tick */ }\n"
"      }\n"
"\n"
"      async function send() {\n"
"        if (sending) return;\n"
"        var text = input.value.trim();\n"
"        if (!text) return;\n"
"        // The radio caps a message at MESHTASTIC_RX_TEXT_MAX (200) BYTES, not characters;\n"
"        // block over-limit multibyte text here instead of letting the device silently truncate it.\n"
"        var bytes = new TextEncoder().encode(text).length;\n"
"        if (bytes > 200) { setStatus('Message too long (' + bytes + '/200 bytes).', true); return; }\n"
"        sending = true;\n"
"        btn.disabled = true;\n"
"        input.value = '';\n"
"        setStatus('Sending...');\n"
"        try {\n"
"          var r = await fetch('/api/send', { method: 'POST', body: text });\n"
"          var d = {};\n"
"          try { d = await r.json(); } catch (e) { d = { ok: r.ok }; }\n"
"          if (d && d.ok) {\n"
"            pendingSend++;           // 'Sending...' clears when the bubble lands as 'Sent'\n"
"            await poll();\n"
"            setTimeout(poll, 500);   // catch the radio-confirmed echo quickly\n"
"            setTimeout(function () { if (pendingSend > 0) { pendingSend = 0; setStatus(''); } }, 4000);\n"
"            window.scrollTo(0, document.documentElement.scrollHeight);\n"
"          } else if (r.status === 400) {\n"
"            input.value = text;\n"
"            setStatus('Message too long.', true);\n"
"          } else {\n"
"            input.value = text;\n"
"            setStatus('Not sent - radio busy, try again.', true);\n"
"          }\n"
"        } catch (e) {\n"
"          input.value = text;\n"
"          setStatus('Network error - message not sent.', true);\n"
"        }\n"
"        sending = false;\n"
"        btn.disabled = false;\n"
"        input.focus();\n"
"      }\n"
"\n"
"      btn.addEventListener('click', send);\n"
"      input.addEventListener('keydown', function (e) { if (e.key === 'Enter') { e.preventDefault(); send(); } });\n"
"\n"
"      // Refresh the relative timestamps in place as time passes.\n"
"      function tick() {\n"
"        for (var k in seen) {\n"
"          var age = seen[k].querySelector('.age');\n"
"          if (age) age.textContent = ' \\u00b7 ' + relTime(seen[k]._t);\n"
"        }\n"
"      }\n"
"\n"
"      // Nodes-heard roster (collapsible panel).\n"
"      function renderNodes(list) {\n"
"        var st = nodesPanel.scrollTop;\n"
"        list.sort(function (a, b) { return a.age - b.age; });   // most recently heard first\n"
"        nodesPanel.textContent = '';\n"
"        if (!list.length) {\n"
"          var e = document.createElement('div');\n"
"          e.className = 'nempty';\n"
"          e.textContent = 'No nodes heard yet. They appear here as they transmit nearby.';\n"
"          nodesPanel.appendChild(e);\n"
"          return;\n"
"        }\n"
"        for (var i = 0; i < list.length; i++) {\n"
"          var nd = list[i];\n"
"          var row = document.createElement('div'); row.className = 'node';\n"
"          var badge = document.createElement('div'); badge.className = 'nbadge';\n"
"          badge.textContent = nd.short || nd.id.slice(-4);\n"
"          row.appendChild(badge);\n"
"          var info = document.createElement('div'); info.className = 'ninfo';\n"
"          var name = document.createElement('div'); name.className = 'nname';\n"
"          name.textContent = nd.long || nd.id;\n"
"          info.appendChild(name);\n"
"          var meta = document.createElement('div'); meta.className = 'nmeta';\n"
"          meta.appendChild(document.createTextNode(nd.id + '  '));\n"
"          var hop = document.createElement('span');\n"
"          hop.textContent = (nd.hops ? (nd.hops + (nd.hops === 1 ? ' hop' : ' hops')) : 'direct') + '  ';\n"
"          meta.appendChild(hop);\n"
"          var rs = document.createElement('span');\n"
"          rs.textContent = nd.rssi + 'dBm';\n"
"          rs.style.color = sigColor(nd.rssi, -120, -55);\n"
"          meta.appendChild(rs);\n"
"          meta.appendChild(document.createTextNode('/'));\n"
"          var sr = document.createElement('span');\n"
"          sr.textContent = nd.snr + 'dB';\n"
"          sr.style.color = sigColor(nd.snr, -17, 10);\n"
"          meta.appendChild(sr);\n"
"          meta.appendChild(document.createTextNode('  ' + fmtAge(nd.age)));\n"
"          info.appendChild(meta);\n"
"          row.appendChild(info);\n"
"          nodesPanel.appendChild(row);\n"
"        }\n"
"        nodesPanel.scrollTop = st;\n"
"      }\n"
"\n"
"      async function fetchNodes() {\n"
"        try {\n"
"          var r = await fetch('/api/nodes', { cache: 'no-store' });\n"
"          if (!r.ok) return;\n"
"          var d = await r.json();\n"
"          renderNodes((d && d.nodes) || []);\n"
"        } catch (e) { /* transient */ }\n"
"      }\n"
"\n"
"      nodesBtn.addEventListener('click', function () {\n"
"        nodesOpen = !nodesOpen;\n"
"        nodesPanel.className = 'nodes' + (nodesOpen ? ' open' : '');\n"
"        nodesBtn.className = 'pill' + (nodesOpen ? ' on' : '');\n"
"        if (nodesOpen) fetchNodes();\n"
"      });\n"
"\n"
"      poll();\n"
"      setInterval(poll, 2000);\n"
"      setInterval(tick, 30000);\n"
"      setInterval(function () { if (nodesOpen) fetchNodes(); }, 5000);\n"
"    </script>\n"
"  </body>\n"
"</html>";
