// Meshtastic web portal HTML (single page)
// Meshy / techy LoRa theme: animated mesh-node network, radio-wave pulses, cobalt-blue glow
const char *LORA_MESHTASTIC_PORTAL_HTML =
"<!doctype html>\n"
"<html lang=\"en\">\n"
"  <head>\n"
"    <meta charset=\"utf-8\" />\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
"    <title>PolyCast5 &middot; Meshtastic</title>\n"
"    <style>\n"
"      :root {\n"
"        --bg: #060b18;\n"
"        --bg-2: #0a1730;\n"
"        --panel: rgba(12, 21, 40, 0.78);\n"
"        --border: #1a3068;\n"
"        --accent: #5ba3f5;\n"
"        --accent-2: #3b82f6;\n"
"        --accent-dim: #0047ab;\n"
"        --glow: rgba(59, 130, 246, 0.35);\n"
"        --text: #d6dff0;\n"
"        --text-bright: #f0f4fa;\n"
"        --muted: #7488ac;\n"
"      }\n"
"      * { box-sizing: border-box; }\n"
"      html, body { margin: 0; min-height: 100%; }\n"
"      body {\n"
"        font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif;\n"
"        color: var(--text);\n"
"        background:\n"
"          radial-gradient(1100px 520px at 50% -12%, rgba(0,71,171,0.22), transparent 60%),\n"
"          radial-gradient(circle at 1px 1px, rgba(91,163,245,0.14) 1px, transparent 0) 0 0 / 34px 34px,\n"
"          linear-gradient(160deg, var(--bg-2), var(--bg));\n"
"        background-position: 0 0, 0 0, 0 0;\n"
"        animation: drift 26s linear infinite;\n"
"        padding: 30px 18px 44px;\n"
"        -webkit-font-smoothing: antialiased;\n"
"      }\n"
"      @keyframes drift { to { background-position: 0 0, 34px 34px, 0 0; } }\n"
"      .wrap { max-width: 560px; margin: 0 auto; }\n"
"      .hero { position: relative; height: 190px; margin: 8px 0 26px; display: grid; place-items: center; }\n"
"      .mesh { position: absolute; inset: 0; width: 100%; height: 100%; opacity: 0.6; }\n"
"      .mesh line { stroke: var(--accent-dim); stroke-width: 1; stroke-dasharray: 3 5; animation: flow 3s linear infinite; }\n"
"      @keyframes flow { to { stroke-dashoffset: -16; } }\n"
"      .mesh circle { fill: var(--accent-2); }\n"
"      .mesh .n { animation: nodePulse 2.8s ease-in-out infinite; }\n"
"      .mesh .n2 { animation: nodePulse 2.8s ease-in-out infinite 0.9s; }\n"
"      .mesh .n3 { animation: nodePulse 2.8s ease-in-out infinite 1.8s; }\n"
"      @keyframes nodePulse { 0%,100% { opacity: 0.4; } 50% { opacity: 1; } }\n"
"      .core { position: relative; z-index: 2; width: 56px; height: 56px; }\n"
"      .ring {\n"
"        position: absolute; inset: 0; margin: auto; width: 56px; height: 56px;\n"
"        border: 1.5px solid var(--accent); border-radius: 50%; opacity: 0;\n"
"        animation: ping 3s ease-out infinite;\n"
"      }\n"
"      .ring:nth-child(2) { animation-delay: 1s; }\n"
"      .ring:nth-child(3) { animation-delay: 2s; }\n"
"      @keyframes ping { 0% { transform: scale(0.5); opacity: 0.85; } 100% { transform: scale(3.4); opacity: 0; } }\n"
"      .chip {\n"
"        position: absolute; inset: 0; margin: auto; width: 56px; height: 56px; border-radius: 16px;\n"
"        background: linear-gradient(145deg, #122544, #060b18); border: 1px solid var(--accent-dim);\n"
"        display: grid; place-items: center;\n"
"        box-shadow: 0 0 26px var(--glow), inset 0 0 12px rgba(59,130,246,0.12);\n"
"      }\n"
"      .chip svg { width: 30px; height: 30px; }\n"
"      .card {\n"
"        background: var(--panel); border: 1px solid var(--border); border-radius: 16px;\n"
"        padding: 22px 20px; backdrop-filter: blur(6px); box-shadow: 0 18px 40px rgba(0,0,0,0.45);\n"
"      }\n"
"      h1 { margin: 0 0 4px; font-size: 1.5rem; color: var(--text-bright); letter-spacing: -0.01em; }\n"
"      h1 span { color: var(--accent); }\n"
"      .sub {\n"
"        margin: 0 0 18px; font: 600 12px/1 ui-monospace, Menlo, monospace;\n"
"        letter-spacing: 0.2em; text-transform: uppercase; color: var(--muted);\n"
"      }\n"
"      p { line-height: 1.6; margin: 0 0 14px; }\n"
"      .hl { color: var(--accent); font-weight: 600; }\n"
"      .note {\n"
"        display: flex; gap: 10px; align-items: flex-start; margin-top: 18px; padding: 12px 14px;\n"
"        border-radius: 12px; background: rgba(59,130,246,0.06); border: 1px solid var(--border);\n"
"        font-size: 0.92rem; color: var(--text-bright);\n"
"      }\n"
"      .note svg { flex: 0 0 auto; margin-top: 1px; }\n"
"    </style>\n"
"  </head>\n"
"  <body>\n"
"    <div class=\"wrap\">\n"
"      <div class=\"hero\">\n"
"        <svg class=\"mesh\" viewBox=\"0 0 300 190\" preserveAspectRatio=\"xMidYMid slice\">\n"
"          <line x1=\"150\" y1=\"95\" x2=\"48\" y2=\"38\" />\n"
"          <line x1=\"150\" y1=\"95\" x2=\"252\" y2=\"44\" />\n"
"          <line x1=\"150\" y1=\"95\" x2=\"42\" y2=\"152\" />\n"
"          <line x1=\"150\" y1=\"95\" x2=\"258\" y2=\"148\" />\n"
"          <line x1=\"150\" y1=\"95\" x2=\"150\" y2=\"18\" />\n"
"          <line x1=\"150\" y1=\"95\" x2=\"150\" y2=\"174\" />\n"
"          <line x1=\"48\" y1=\"38\" x2=\"150\" y2=\"18\" />\n"
"          <line x1=\"252\" y1=\"44\" x2=\"150\" y2=\"18\" />\n"
"          <line x1=\"42\" y1=\"152\" x2=\"150\" y2=\"174\" />\n"
"          <line x1=\"258\" y1=\"148\" x2=\"150\" y2=\"174\" />\n"
"          <circle class=\"n\"  cx=\"48\"  cy=\"38\"  r=\"3\" />\n"
"          <circle class=\"n2\" cx=\"252\" cy=\"44\"  r=\"3\" />\n"
"          <circle class=\"n3\" cx=\"42\"  cy=\"152\" r=\"3\" />\n"
"          <circle class=\"n\"  cx=\"258\" cy=\"148\" r=\"3\" />\n"
"          <circle class=\"n2\" cx=\"150\" cy=\"18\"  r=\"3\" />\n"
"          <circle class=\"n3\" cx=\"150\" cy=\"174\" r=\"3\" />\n"
"        </svg>\n"
"        <div class=\"core\">\n"
"          <span class=\"ring\"></span><span class=\"ring\"></span><span class=\"ring\"></span>\n"
"          <span class=\"chip\">\n"
"            <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#5ba3f5\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\">\n"
"              <rect x=\"7\" y=\"7\" width=\"10\" height=\"10\" rx=\"2\" />\n"
"              <path d=\"M10 3v3M14 3v3M10 18v3M14 18v3M3 10h3M3 14h3M18 10h3M18 14h3\" />\n"
"            </svg>\n"
"          </span>\n"
"        </div>\n"
"      </div>\n"
"      <div class=\"card\">\n"
"        <h1>PolyCast5 <span>Meshtastic</span> Portal</h1>\n"
"        <div class=\"sub\">LoRa Mesh Network</div>\n"
"        <p>You&rsquo;re connected to your PolyCast5.</p>\n"
"        <p><span class=\"hl\">Meshtastic</span> is an open-source, long-range mesh network that lets"
"           devices trade text and location over LoRa radio &mdash; no cell signal or internet"
"           required. Every node relays for the others, so coverage grows with the mesh.</p>\n"
"        <p>Meshtastic configuration for this device will live right here.</p>\n"
"        <div class=\"note\">\n"
"          <svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"#5ba3f5\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"9\" /><path d=\"M12 16v-4M12 8h.01\" /></svg>\n"
"          <span>Keep the <b>Meshtastic</b> page open on your PolyCast5 while you&rsquo;re connected.</span>\n"
"        </div>\n"
"      </div>\n"
"    </div>\n"
"  </body>\n"
"</html>";
