#ifndef POLYCAST5_FONTS_H
#define POLYCAST5_FONTS_H

// A custom font example for those who are interested.
// To enable this example, you must define POLYCAST5_USE_BORN2BSPORTYFS_FONT in lv_conf.h (currently commented out).
// Example uses Born2bSportyFS but you can change the files in lcd/fonts/src to whatever you want. 
// Font converter: https://lvgl.io/tools/fontconverter | Range: 0x20-0x7F | Fallback: lv_font_montserrat_14 | Bpp: 4

// Note: After regenerating fonts from lvgl.io/tools/fontconverter, delete the .static_bitmap = 0, line from each .c
// file (the converter targets a newer LVGL than this project's v9.2.2).

#include "lvgl.h" // Pulls lv_conf.h, which sets POLYCAST5_USE_BORN2BSPORTYFS_FONT (or not).

#ifdef POLYCAST5_USE_BORN2BSPORTYFS_FONT

/* Custom Born2bSporty font sizes generated by lvgl.io/tools/fontconverter.
 * Each falls back to lv_font_montserrat_14 for LV_SYMBOL_* icons. */
LV_FONT_DECLARE(born2bsportyfs_12)
LV_FONT_DECLARE(born2bsportyfs_14)
LV_FONT_DECLARE(born2bsportyfs_16)
LV_FONT_DECLARE(born2bsportyfs_18)
LV_FONT_DECLARE(born2bsportyfs_20)
LV_FONT_DECLARE(born2bsportyfs_22)
LV_FONT_DECLARE(born2bsportyfs_24)
LV_FONT_DECLARE(born2bsportyfs_30)

/* Preprocessor aliases so existing &lv_font_montserrat_NN references render
 * as Born2bSporty without touching every call site. Do NOT include this
 * header from the born2bsportyfs_*.c files — their .fallback fields
 * reference lv_font_montserrat_14 by its real name. */
#define lv_font_montserrat_12 born2bsportyfs_12
#define lv_font_montserrat_14 born2bsportyfs_14
#define lv_font_montserrat_16 born2bsportyfs_16
#define lv_font_montserrat_18 born2bsportyfs_18
#define lv_font_montserrat_20 born2bsportyfs_20
#define lv_font_montserrat_22 born2bsportyfs_22
#define lv_font_montserrat_24 born2bsportyfs_24
#define lv_font_montserrat_30 born2bsportyfs_30

#endif /* POLYCAST5_USE_BORN2BSPORTYFS_FONT */

#endif /* POLYCAST5_FONTS_H */
