
idf_component_register(

    SRCS
        "src/fontx.c"
        "src/lcd_ir_funcs.c"
        "src/lcd_lora_funcs.c"
        "src/lcd_espnow_funcs.c"
        "src/lcd_wifi_funcs.c"
        "src/lcd_funcs.c"
        "src/lcd_task.c"
        "src/st7789.c"
        
        "media/qr/src/qr_esp_rx_example.c"
        "media/qr/src/qr_esp_enc_rx_example.c"
        
        "media/other/src/img_ir_save_new_remote.c"
        
        "media/city/src/anim_city_1.c"
        "media/city/src/anim_city_2.c"
        "media/city/src/anim_city_3.c"
        "media/city/src/anim_city_4.c"
        "media/city/src/anim_city_5.c"
        "media/city/src/anim_city_6.c"
        "media/city/src/anim_city_7.c"
        "media/city/src/anim_city_8.c"
        "media/city/src/anim_city_9.c"
        "media/city/src/anim_city_10.c"
        "media/city/src/anim_city_11.c"
        "media/city/src/anim_city_12.c"
        "media/city/src/anim_city_13.c"
        "media/city/src/anim_city_14.c"
        "media/city/src/anim_city_15.c"
        "media/city/src/anim_city_16.c"
        "media/city/src/anim_city_17.c"
        "media/city/src/anim_city_18.c"
        "media/city/src/anim_city_19.c"
        "media/city/src/anim_city_20.c"
		"media/city/src/anim_city_18.c"
		"media/city/src/anim_city_19.c"
		"media/city/src/anim_city_20.c"
		"media/city/src/anim_city_21.c"
		"media/city/src/anim_city_22.c"
		"media/city/src/anim_city_23.c"
		"media/city/src/anim_city_24.c"
		"media/city/src/anim_city_25.c"
		"media/city/src/anim_city_26.c"
		"media/city/src/anim_city_27.c"
		"media/city/src/anim_city_28.c"
		"media/city/src/anim_city_29.c"
		"media/city/src/anim_city_30.c"
		"media/city/src/anim_city_31.c"
		"media/city/src/anim_city_32.c"
		"media/city/src/anim_city_33.c"
		"media/city/src/anim_city_34.c"
		"media/city/src/anim_city_35.c"
		"media/city/src/anim_city_36.c"
		"media/city/src/anim_city_37.c"
		"media/city/src/anim_city_38.c"
		"media/city/src/anim_city_39.c"
		"media/city/src/anim_city_40.c"
		"media/city/src/anim_city_41.c"
		"media/city/src/anim_city_42.c"
		"media/city/src/anim_city_43.c"
		"media/city/src/anim_city_44.c"
		"media/city/src/anim_city_45.c"
		"media/city/src/anim_city_46.c"
		"media/city/src/anim_city_47.c"
		"media/city/src/anim_city_48.c"
		"media/city/src/anim_city_49.c"
		"media/city/src/anim_city_50.c"
		"media/city/src/anim_city_51.c"
		"media/city/src/anim_city_52.c"
		"media/city/src/anim_city_53.c"
		"media/city/src/anim_city_54.c"
		"media/city/src/anim_city_55.c"
		"media/city/src/anim_city_56.c"
		"media/city/src/anim_city_57.c"
		"media/city/src/anim_city_58.c"
		"media/city/src/anim_city_59.c"
		"media/city/src/anim_city_60.c"
		
		"media/black_hole/src/anim_black_hole_1.c"
		"media/black_hole/src/anim_black_hole_2.c"
		"media/black_hole/src/anim_black_hole_3.c"
		"media/black_hole/src/anim_black_hole_4.c"
		"media/black_hole/src/anim_black_hole_5.c"
		"media/black_hole/src/anim_black_hole_6.c"
		"media/black_hole/src/anim_black_hole_7.c"
		"media/black_hole/src/anim_black_hole_8.c"
		"media/black_hole/src/anim_black_hole_9.c"
		"media/black_hole/src/anim_black_hole_10.c"
		"media/black_hole/src/anim_black_hole_11.c"
		"media/black_hole/src/anim_black_hole_12.c"
		"media/black_hole/src/anim_black_hole_13.c"
		"media/black_hole/src/anim_black_hole_14.c"
		"media/black_hole/src/anim_black_hole_15.c"
		"media/black_hole/src/anim_black_hole_16.c"
		"media/black_hole/src/anim_black_hole_17.c"
		"media/black_hole/src/anim_black_hole_18.c"
        
    INCLUDE_DIRS 
    	"include"
    	"media/qr/include"
    	"media/city/include"
    	"media/black_hole/include"
    	"media/other/include"
    
    REQUIRES
    	driver freertos lvgl sx126x common
    
    PRIV_REQUIRES
    	gpio sx126x infrared espnow lora wifi
)
