// BTC web portal HTML (single page)
const char *WIFI_BTC_PORTAL_HTML =
"<!doctype html>\n"
"<html lang=\"en\">\n"
"  <head>\n"
"    <meta charset=\"utf-8\" />\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
"    <title>PolyCast5 BTC Portal</title>\n"

"    <style>\n"
"      :root {\n"
"        --bg: #060b18;\n"
"        --bg-panel: #0c1528;\n"
"        --border: #1a3068;\n"
"        --accent: #5ba3f5;\n"
"        --accent-dim: #0047ab;\n"
"        --accent-glow: rgba(0,71,171,0.25);\n"
"        --text: #d6dff0;\n"
"        --text-bright: #f0f4fa;\n"
"        --success: #3ddc84;\n"
"        --page-padding: 20px;\n"
"        --label-gap-top: 12px;\n"
"        --label-gap-bottom: 5px;\n"
"        --radius: 4px;\n"
"      }\n"

"      *, *::before, *::after { box-sizing: border-box; }\n"

"      body {\n"
"        font-family: 'Courier New', Courier, monospace;\n"
"        margin: 0;\n"
"        padding: var(--page-padding);\n"
"        background: var(--bg);\n"
"        color: var(--text);\n"
"        line-height: 1.45;\n"
"        max-width: 640px;\n"
"        margin: 0 auto;\n"
"        position: relative;\n"
"      }\n"

"      body::after {\n"
"        content: '';\n"
"        position: fixed;\n"
"        inset: 0;\n"
"        background: repeating-linear-gradient(\n"
"          0deg,\n"
"          transparent,\n"
"          transparent 2px,\n"
"          rgba(0,0,0,0.08) 2px,\n"
"          rgba(0,0,0,0.08) 4px\n"
"        );\n"
"        pointer-events: none;\n"
"        z-index: 9999;\n"
"      }\n"

"      h2 {\n"
"        color: var(--accent);\n"
"        text-transform: uppercase;\n"
"        letter-spacing: 3px;\n"
"        font-size: 1.3em;\n"
"        border-bottom: 2px solid var(--accent-dim);\n"
"        padding-bottom: 10px;\n"
"        text-shadow: 0 0 10px rgba(91,163,245,0.4);\n"
"      }\n"

"      p {\n"
"        font-size: 0.85em;\n"
"        margin: 8px 0;\n"
"      }\n"

"      code {\n"
"        font-family: inherit;\n"
"        background: var(--bg-panel);\n"
"        color: var(--accent);\n"
"        border: 1px solid var(--border);\n"
"        border-radius: 3px;\n"
"        padding: 1px 6px;\n"
"        font-size: 0.95em;\n"
"      }\n"

"      label {\n"
"        display: block;\n"
"        margin: var(--label-gap-top) 0 var(--label-gap-bottom);\n"
"        font-weight: 600;\n"
"        color: var(--accent);\n"
"        text-transform: uppercase;\n"
"        font-size: 0.8em;\n"
"        letter-spacing: 1px;\n"
"      }\n"

"      input {\n"
"        width: 100%;\n"
"        font: inherit;\n"
"        font-size: 0.9em;\n"
"        background: var(--bg);\n"
"        color: var(--text-bright);\n"
"        border: 1px solid var(--border);\n"
"        border-radius: var(--radius);\n"
"        padding: 8px 10px;\n"
"        outline: none;\n"
"        transition: border-color 0.2s, box-shadow 0.2s;\n"
"      }\n"

"      input:focus {\n"
"        border-color: var(--accent);\n"
"        box-shadow: 0 0 8px var(--accent-glow), inset 0 0 4px var(--accent-glow);\n"
"      }\n"

"      button {\n"
"        font: inherit;\n"
"        font-size: 0.85em;\n"
"        text-transform: uppercase;\n"
"        letter-spacing: 1px;\n"
"        background: var(--bg-panel);\n"
"        color: var(--accent);\n"
"        border: 1px solid var(--accent-dim);\n"
"        border-radius: var(--radius);\n"
"        padding: 8px 16px;\n"
"        cursor: pointer;\n"
"        transition: all 0.15s;\n"
"      }\n"

"      button:hover {\n"
"        background: var(--accent-dim);\n"
"        color: var(--bg);\n"
"        box-shadow: 0 0 12px var(--accent-glow);\n"
"      }\n"

"      button:active {\n"
"        transform: scale(0.97);\n"
"      }\n"

"      .status {\n"
"        margin-left: 6px;\n"
"        font-weight: 600;\n"
"        color: var(--success);\n"
"        font-size: 0.85em;\n"
"        text-shadow: 0 0 6px rgba(61,220,132,0.3);\n"
"      }\n"

"      ::selection {\n"
"        background: var(--accent);\n"
"        color: var(--bg);\n"
"      }\n"

"      ::-webkit-scrollbar { width: 6px; height: 6px; }\n"
"      ::-webkit-scrollbar-track { background: var(--bg); }\n"
"      ::-webkit-scrollbar-thumb { background: var(--accent-dim); border-radius: 3px; }\n"
"    </style>\n"
"  </head>\n"

"  <body>\n"
"    <h2>PolyCast5 BTC Portal</h2>\n"
"    <p>\n"
"      Paste in your <strong>public</strong> Bitcoin address below and click save.\n"
"      (e.g., <code>bc1q...</code> or <code>bc1p...</code>)\n"
"    </p>\n"
"    <p>PolyCast5 will then show it as a QR on-screen!</p>\n"

"    <div>\n"
"      <label for=\"addr\">Address</label>\n"
"      <input id=\"addr\" placeholder=\"bc1q...\" />\n"
"    </div>\n"
"    <p>\n"
"      <button id=\"save\" type=\"button\">Save</button>\n"
"      <span id=\"msg\" class=\"status\"></span>\n"
"    </p>\n"

"    <script>\n"
"      // -------------------------------\n"
"      // Load existing address\n"
"      // -------------------------------\n"
"      async function load() {\n"
"        try {\n"
"          var r = await fetch('/api/address');\n"
"          if (!r.ok) return;\n"
"          var j = await r.json();\n"
"          document.getElementById('addr').value = j.address || '';\n"
"        } catch (e) {\n"
"          console.error(e);\n"
"        }\n"
"      }\n"

"      // -------------------------------\n"
"      // Save address\n"
"      // -------------------------------\n"
"      async function save() {\n"
"        var address = document.getElementById('addr').value.trim();\n"
"        var msg = document.getElementById('msg');\n"

"        try {\n"
"          var r = await fetch('/api/address', {\n"
"            method: 'POST',\n"
"            headers: { 'Content-Type': 'application/json' },\n"
"            body: JSON.stringify({ address: address })\n"
"          });\n"
"          msg.textContent = r.ok ? 'Saved!' : 'Save failed';\n"
"        } catch (e) {\n"
"          msg.textContent = 'Save failed';\n"
"        }\n"
"      }\n"

"      // -------------------------------\n"
"      // Event wiring\n"
"      // -------------------------------\n"
"      document.getElementById('save').addEventListener('click', save);\n"
"      load();\n"
"    </script>\n"
"  </body>\n"
"</html>\n"
;
