// Bluetooth web portal HTML (single page)
const char *BLUETOOTH_WEB_PORTAL_HTML =
"<!doctype html>\n"
"<html lang=\"en\">\n"
"  <head>\n"
"    <meta charset=\"utf-8\" />\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
"    <title>PolyCast5 BT Portal</title>\n"

"    <style>\n"
"      :root {\n"
"        --bg: #060b18;\n"
"        --bg-panel: #0c1528;\n"
"        --border: #1a3068;\n"
"        --accent: #5ba3f5;\n"
"        --accent-dim: #0047ab;\n"
"        --accent-glow: rgba(0,71,171,0.25);\n"
"        --text: #d6dff0;\n"
"        --text-bright: #f0f4fa;\n"
"        --danger: #e04060;\n"
"        --success: #3ddc84;\n"
"        --page-padding: 20px;\n"
"        --block-gap: 12px;\n"
"        --label-gap-top: 12px;\n"
"        --label-gap-bottom: 5px;\n"
"        --radius: 4px;\n"
"      }\n"

"      *, *::before, *::after { box-sizing: border-box; }\n"

"      body {\n"
"        font-family: 'Courier New', Courier, monospace;\n"
"        margin: 0;\n"
"        padding: var(--page-padding);\n"
"        background: var(--bg);\n"
"        color: var(--text);\n"
"        line-height: 1.45;\n"
"        max-width: 640px;\n"
"        margin: 0 auto;\n"
"        position: relative;\n"
"      }\n"

"      body::after {\n"
"        content: '';\n"
"        position: fixed;\n"
"        inset: 0;\n"
"        background: repeating-linear-gradient(\n"
"          0deg,\n"
"          transparent,\n"
"          transparent 2px,\n"
"          rgba(0,0,0,0.08) 2px,\n"
"          rgba(0,0,0,0.08) 4px\n"
"        );\n"
"        pointer-events: none;\n"
"        z-index: 9999;\n"
"      }\n"

"      h2 {\n"
"        color: var(--accent);\n"
"        text-transform: uppercase;\n"
"        letter-spacing: 3px;\n"
"        font-size: 1.3em;\n"
"        border-bottom: 2px solid var(--accent-dim);\n"
"        padding-bottom: 10px;\n"
"        text-shadow: 0 0 10px rgba(91,163,245,0.4);\n"
"      }\n"

"      h3 {\n"
"        color: var(--accent);\n"
"        font-size: 1em;\n"
"        text-transform: uppercase;\n"
"        letter-spacing: 2px;\n"
"        margin-bottom: 6px;\n"
"        text-shadow: 0 0 8px rgba(91,163,245,0.3);\n"
"      }\n"

"      h3::before {\n"
"        content: '> ';\n"
"        color: var(--accent);\n"
"      }\n"

"      h4 {\n"
"        color: var(--text-bright);\n"
"        font-size: 0.9em;\n"
"        text-transform: uppercase;\n"
"        letter-spacing: 1px;\n"
"        margin-top: 16px;\n"
"        margin-bottom: 8px;\n"
"      }\n"

"      hr {\n"
"        border: none;\n"
"        border-top: 1px solid var(--border);\n"
"        margin: 22px 0;\n"
"        box-shadow: 0 1px 0 var(--accent-glow);\n"
"      }\n"

"      p {\n"
"        font-size: 0.85em;\n"
"        margin: 8px 0;\n"
"      }\n"

"      label {\n"
"        display: block;\n"
"        margin: var(--label-gap-top) 0 var(--label-gap-bottom);\n"
"        font-weight: 600;\n"
"        color: var(--accent);\n"
"        text-transform: uppercase;\n"
"        font-size: 0.8em;\n"
"        letter-spacing: 1px;\n"
"      }\n"

"      input, textarea, select {\n"
"        width: 100%;\n"
"        font: inherit;\n"
"        font-size: 0.9em;\n"
"        background: var(--bg);\n"
"        color: var(--text-bright);\n"
"        border: 1px solid var(--border);\n"
"        border-radius: var(--radius);\n"
"        padding: 8px 10px;\n"
"        outline: none;\n"
"        transition: border-color 0.2s, box-shadow 0.2s;\n"
"      }\n"

"      input:focus, textarea:focus, select:focus {\n"
"        border-color: var(--accent);\n"
"        box-shadow: 0 0 8px var(--accent-glow), inset 0 0 4px var(--accent-glow);\n"
"      }\n"

"      textarea {\n"
"        height: 180px;\n"
"        resize: vertical;\n"
"      }\n"

"      button {\n"
"        font: inherit;\n"
"        font-size: 0.85em;\n"
"        text-transform: uppercase;\n"
"        letter-spacing: 1px;\n"
"        background: var(--bg-panel);\n"
"        color: var(--accent);\n"
"        border: 1px solid var(--accent-dim);\n"
"        border-radius: var(--radius);\n"
"        padding: 8px 16px;\n"
"        cursor: pointer;\n"
"        transition: all 0.15s;\n"
"      }\n"

"      button:hover {\n"
"        background: var(--accent-dim);\n"
"        color: var(--bg);\n"
"        box-shadow: 0 0 12px var(--accent-glow);\n"
"      }\n"

"      button:active {\n"
"        transform: scale(0.97);\n"
"      }\n"

"      .row {\n"
"        display: flex;\n"
"        gap: 10px;\n"
"        align-items: center;\n"
"      }\n"

"      .row > * {\n"
"        flex: 1;\n"
"      }\n"

"      .row .fit {\n"
"        flex: 0 0 auto;\n"
"        width: auto;\n"
"      }\n"

"      .buttons {\n"
"        display: flex;\n"
"        gap: 10px;\n"
"        flex-wrap: wrap;\n"
"        margin-top: var(--block-gap);\n"
"      }\n"

"      .buttons button {\n"
"        width: auto;\n"
"      }\n"

"      .status {\n"
"        margin-left: 6px;\n"
"        font-weight: 600;\n"
"        color: var(--success);\n"
"        font-size: 0.85em;\n"
"        text-shadow: 0 0 6px rgba(61,220,132,0.3);\n"
"      }\n"

"      .small-note {\n"
"        opacity: 0.75;\n"
"        font-size: 0.8em;\n"
"      }\n"

"      .list {\n"
"        height: 160px;\n"
"        overflow-y: auto;\n"
"        border: 1px solid var(--border);\n"
"        border-radius: var(--radius);\n"
"        background: var(--bg);\n"
"      }\n"

"      .list-item {\n"
"        padding: 6px 10px;\n"
"        cursor: pointer;\n"
"        font-family: inherit;\n"
"        font-size: 0.9em;\n"
"        color: var(--text-bright);\n"
"      }\n"

"      .list-item:hover {\n"
"        background: var(--accent-glow);\n"
"      }\n"

"      .list-item:active {\n"
"        background: var(--accent-dim);\n"
"        color: var(--bg);\n"
"      }\n"

"      select option {\n"
"        padding: 4px 6px;\n"
"      }\n"

"      code.inline {\n"
"        font-family: inherit;\n"
"        background: var(--bg-panel);\n"
"        color: var(--accent);\n"
"        border: 1px solid var(--border);\n"
"        border-radius: 3px;\n"
"        padding: 1px 6px;\n"
"        font-size: 0.95em;\n"
"      }\n"

"      a {\n"
"        color: var(--accent);\n"
"        text-decoration: none;\n"
"        border-bottom: 1px dashed var(--accent-dim);\n"
"        word-wrap: break-word;\n"
"        overflow-wrap: break-word;\n"
"        transition: color 0.15s;\n"
"      }\n"

"      a:hover {\n"
"        color: var(--text-bright);\n"
"      }\n"

"      ::selection {\n"
"        background: var(--accent);\n"
"        color: var(--bg);\n"
"      }\n"

"      ::-webkit-scrollbar {\n"
"        width: 6px;\n"
"        height: 6px;\n"
"      }\n"

"      ::-webkit-scrollbar-track {\n"
"        background: var(--bg);\n"
"      }\n"

"      ::-webkit-scrollbar-thumb {\n"
"        background: var(--accent-dim);\n"
"        border-radius: 3px;\n"
"      }\n"
"    </style>\n"
"  </head>\n"

"  <body>\n"
"    <h2>PolyCast5 BT Portal</h2>\n"

"    <hr />\n"
"    <h3>Manage Categories</h3>\n"
"    <p>Bluetooth scripts are organized into categories to help make finding them easier.</p>\n"
"    <p>\n"
"      For example, if you want all your passwords in one place, create a category named\n"
"      <code class=\"inline\">Passwords</code> and save them under that.\n"
"    </p>\n"
"    <p class=\"small-note\">Category indexes are 0-based (0, 1, 2, ...).</p>\n"
"    <p>\n"
"      A tutorial is also available here:\n"
"      <a href=\"https://polycast5.com/blogs/docs/bluetooth-auto-keyboard/\" target=\"_blank\" rel=\"noopener noreferrer\">polycast5.com/blogs/docs/bluetooth-auto-keyboard</a>\n"
"    </p>\n"

"    <div>\n"
"      <label for=\"category_index_input\">Category index</label>\n"
"      <div class=\"row\">\n"
"        <input id=\"category_index_input\" type=\"number\" min=\"0\" value=\"0\" />\n"
"        <button id=\"category_load_button\" class=\"fit\" type=\"button\">Load</button>\n"
"      </div>\n"
"    </div>\n"

"    <div>\n"
"      <label for=\"category_name_input\">Category name</label>\n"
"      <input id=\"category_name_input\" maxlength=\"32\" placeholder=\"Group name\" />\n"
"    </div>\n"

"    <div class=\"buttons\">\n"
"      <button id=\"category_save_button\" type=\"button\">Save (add/edit)</button>\n"
"      <button id=\"category_delete_button\" type=\"button\">Delete</button>\n"
"      <span id=\"category_status_text\" class=\"status\"></span>\n"
"    </div>\n"

"    <h4>Existing Categories</h4>\n"
"    <div id=\"category_existing_list\" class=\"list\"></div>\n"
"    <div class=\"buttons\">\n"
"      <button id=\"category_add_new_button\" type=\"button\">+ Add New</button>\n"
"    </div>\n"

"    <hr />\n"
"    <h3>Existing Scripts</h3>\n"
"    <p class=\"small-note\">\n"
"      Select a category to browse its scripts. Click one to load it for editing.\n"
"    </p>\n"
"    <div>\n"
"      <label for=\"script_browse_category_select\">Category</label>\n"
"      <select id=\"script_browse_category_select\"></select>\n"
"    </div>\n"
"    <div id=\"script_existing_list\" class=\"list\" style=\"margin-top:8px\"></div>\n"
"    <div class=\"buttons\">\n"
"      <button id=\"script_add_new_button\" type=\"button\">+ Add New</button>\n"
"    </div>\n"

"    <hr />\n"
"    <h3>Edit Script</h3>\n"
"    <p>Pick a category below to save specific scripts to.</p>\n"
"    <p class=\"small-note\">Script indexes are also 0-based (0, 1, 2, ...).</p>\n"

"    <div>\n"
"      <label for=\"script_category_select\">Category</label>\n"
"      <select id=\"script_category_select\"></select>\n"
"    </div>\n"

"    <div>\n"
"      <label for=\"script_local_index_input\">Script index (local)</label>\n"
"      <div class=\"row\">\n"
"        <input id=\"script_local_index_input\" type=\"number\" min=\"0\" max=\"254\" value=\"0\" />\n"
"        <button id=\"script_load_button\" class=\"fit\" type=\"button\">Load</button>\n"
"      </div>\n"
"    </div>\n"

"    <div>\n"
"      <label for=\"script_name_input\">Name</label>\n"
"      <input id=\"script_name_input\" maxlength=\"32\" placeholder=\"Short label for device menu\" />\n"
"    </div>\n"

"    <div>\n"
"      <label for=\"script_payload_textarea\">Payload</label>\n"
"      <textarea id=\"script_payload_textarea\" placeholder=\"What the device should type\u2026\"></textarea>\n"
"    </div>\n"

"    <div class=\"buttons\">\n"
"      <button id=\"script_save_button\" type=\"button\">Save (add/edit)</button>\n"
"      <button id=\"script_delete_button\" type=\"button\">Delete</button>\n"
"      <span id=\"script_status_text\" class=\"status\"></span>\n"
"    </div>\n"

"    <p>Here are some additional commands so you can do more than just type text:</p>\n"
"    <p class=\"small-note\">\n"
"      &lt;delay=x&gt; - Wait for x milliseconds<br />\n"
"      &lt;hold:c=x&gt; - Hold c for x milliseconds<br />\n"
"      &lt;enter&gt; - Enter<br />\n"
"      &lt;tab&gt; - Tab<br />\n"
"      &lt;esc&gt; - Escape<br />\n"
"      &lt;ctrl&gt; - Ctrl<br />\n"
"      &lt;shift&gt; - Shift<br />\n"
"      &lt;alt&gt; - Alt/Option<br />\n"
"      &lt;win&gt; - Windows/Cmd<br />\n"
"      &lt;space&gt; - Space<br />\n"
"      &lt;bs&gt; - Backspace<br />\n"
"      &lt;del&gt; - Forward delete<br />\n"
"      &lt;up&gt; - Up arrow<br />\n"
"      &lt;down&gt; - Down arrow<br />\n"
"      &lt;left&gt; - Left arrow<br />\n"
"      &lt;right&gt; - Right arrow<br />\n"
"      &lt;home&gt; - Home<br />\n"
"      &lt;pgup&gt; - Page up<br />\n"
"      &lt;pgdn&gt; - Page down<br />\n"
"      &lt;fx&gt; - Function x (e.g. f1, f2, etc.)<br />\n"
"      &lt;select_prior&gt; - Selects all text typed before it<br />\n"
"      &lt;down:c&gt; - Hold c down until &lt;up:c&gt; is called<br />\n"
"      &lt;up:c&gt; - Release c if &lt;down:c&gt; was called<br />\n"
"      <br />\n"
"      You can also combine commands like &lt;ctrl+shift+v&gt; or &lt;ctrl+c&gt;.<br />\n"
"      <br />\n"
"      Example: &lt;win+s&gt;&lt;delay=500&gt;browser&lt;enter&gt;&lt;delay=500&gt;https://youtu.be/dQw4w9WgXcQ&lt;enter&gt;<br />\n"
"      <br />\n"
"      More examples are available below:\n"
"      <a href=\"https://github.com/RoboticWorx/PolyCast5/tree/main/scripts/bluetooth_examples\" target=\"_blank\" rel=\"noopener noreferrer\">github.com/RoboticWorx/PolyCast5/tree/main/scripts/bluetooth_examples</a>\n"
"    </p>\n"

"    <script>\n"
"      // -------------------------------\n"
"      // DOM helpers\n"
"      // -------------------------------\n"
"      function getElementByIdSafe(elementId) {\n"
"        return document.getElementById(elementId);\n"
"      }\n"

"      function parseIntegerOrDefault(value, defaultValue) {\n"
"        const parsedValue = parseInt(String(value), 10);\n"
"        return Number.isFinite(parsedValue) ? parsedValue : defaultValue;\n"
"      }\n"

"      function setTextIfExists(element, text) {\n"
"        if (element) element.textContent = text;\n"
"      }\n"

"      // -------------------------------\n"
"      // API refreshers\n"
"      // -------------------------------\n"
"      var categoryCount = 0;\n"
"      var categoryScriptCounts = [];\n"

"      async function refreshScriptsForCategory(categoryIndex) {\n"
"        try {\n"
"          const list = getElementByIdSafe('script_existing_list');\n"
"          if (!list) return;\n"
"          list.innerHTML = '';\n"

"          for (let i = 0; ; i++) {\n"
"            try {\n"
"              const r = await fetch(`/api/script?index=${i}&cat=${categoryIndex}`);\n"
"              if (!r.ok) break;\n"
"              const j = await r.json();\n"
"              const item = document.createElement('div');\n"
"              item.className = 'list-item';\n"
"              item.dataset.value = String(i);\n"
"              item.textContent = `${i}: ${j.name || '(unnamed)'}`;\n"
"              list.appendChild(item);\n"
"            } catch (e) { break; }\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"
"      }\n"

"      function addNewScriptInBrowseCategory() {\n"
"        const browseCatSel = getElementByIdSafe('script_browse_category_select');\n"
"        const catIdx = parseIntegerOrDefault(browseCatSel ? browseCatSel.value : '0', 0);\n"
"        const nextIdx = (catIdx < categoryScriptCounts.length) ? categoryScriptCounts[catIdx] : 0;\n"

"        const scriptStatusText = getElementByIdSafe('script_status_text');\n"
"        if (nextIdx >= 255) {\n"
"          setTextIfExists(scriptStatusText, 'Max scripts reached');\n"
"          return;\n"
"        }\n"

"        const scriptCategorySelect = getElementByIdSafe('script_category_select');\n"
"        const scriptLocalIndexInput = getElementByIdSafe('script_local_index_input');\n"
"        const scriptNameInput = getElementByIdSafe('script_name_input');\n"
"        const scriptPayloadTextarea = getElementByIdSafe('script_payload_textarea');\n"

"        if (scriptCategorySelect) scriptCategorySelect.value = String(catIdx);\n"
"        if (scriptLocalIndexInput) scriptLocalIndexInput.value = String(nextIdx);\n"
"        if (scriptNameInput) { scriptNameInput.value = ''; scriptNameInput.focus(); }\n"
"        if (scriptPayloadTextarea) scriptPayloadTextarea.value = '';\n"
"        setTextIfExists(scriptStatusText, 'New script at index ' + nextIdx);\n"
"      }\n"

"      function addNewCategory() {\n"
"        const categoryStatusText = getElementByIdSafe('category_status_text');\n"
"        if (categoryCount >= 50) {\n"
"          setTextIfExists(categoryStatusText, 'Max categories reached (50)');\n"
"          return;\n"
"        }\n"

"        const categoryIndexInput = getElementByIdSafe('category_index_input');\n"
"        const categoryNameInput = getElementByIdSafe('category_name_input');\n"

"        if (categoryIndexInput) categoryIndexInput.value = String(categoryCount);\n"
"        if (categoryNameInput) { categoryNameInput.value = ''; categoryNameInput.focus(); }\n"
"        setTextIfExists(categoryStatusText, 'New category at index ' + categoryCount);\n"
"      }\n"

"      async function refreshCategoryLists() {\n"
"        try {\n"
"          const response = await fetch('/api/categories');\n"
"          if (!response.ok) return;\n"

"          const json = await response.json();\n"
"          categoryCount = json.count || 0;\n"
"          categoryScriptCounts = json.script_counts || [];\n"

"          const existingCategoriesListSelect = getElementByIdSafe('category_existing_list');\n"
"          const scriptCategorySelect = getElementByIdSafe('script_category_select');\n"
"          const browseCategorySelect = getElementByIdSafe('script_browse_category_select');\n"

"          const prevBrowse = browseCategorySelect ? browseCategorySelect.value : '0';\n"
"          const prevScriptCat = scriptCategorySelect ? scriptCategorySelect.value : '0';\n"

"          if (existingCategoriesListSelect) existingCategoriesListSelect.innerHTML = '';\n"
"          if (scriptCategorySelect) scriptCategorySelect.innerHTML = '';\n"
"          if (browseCategorySelect) browseCategorySelect.innerHTML = '';\n"

"          for (let categoryIndex = 0; categoryIndex < json.count; categoryIndex++) {\n"
"            const categoryName = json.names[categoryIndex] || '(unnamed)';\n"

"            if (existingCategoriesListSelect) {\n"
"              const item = document.createElement('div');\n"
"              item.className = 'list-item';\n"
"              item.dataset.value = String(categoryIndex);\n"
"              item.textContent = `${categoryIndex}: ${categoryName}`;\n"
"              existingCategoriesListSelect.appendChild(item);\n"
"            }\n"

"            if (scriptCategorySelect) {\n"
"              const selectOption = document.createElement('option');\n"
"              selectOption.value = String(categoryIndex);\n"
"              selectOption.textContent = categoryName;\n"
"              scriptCategorySelect.appendChild(selectOption);\n"
"            }\n"

"            if (browseCategorySelect) {\n"
"              const browseOption = document.createElement('option');\n"
"              browseOption.value = String(categoryIndex);\n"
"              browseOption.textContent = categoryName;\n"
"              browseCategorySelect.appendChild(browseOption);\n"
"            }\n"
"          }\n"

"          if (scriptCategorySelect) scriptCategorySelect.value = prevScriptCat;\n"
"          if (browseCategorySelect) {\n"
"            browseCategorySelect.value = prevBrowse;\n"
"            refreshScriptsForCategory(parseIntegerOrDefault(browseCategorySelect.value, 0));\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"
"      }\n"

"      // -------------------------------\n"
"      // Loaders\n"
"      // -------------------------------\n"
"      async function loadScriptByLocalIndex(localIndex, categoryIndex) {\n"
"        try {\n"
"          const response = await fetch(`/api/script?index=${localIndex}&cat=${categoryIndex}`);\n"
"          const scriptStatusText = getElementByIdSafe('script_status_text');\n"

"          if (!response.ok) {\n"
"            setTextIfExists(scriptStatusText, 'Not found');\n"
"            return;\n"
"          }\n"

"          const json = await response.json();\n"

"          const scriptCategorySelect = getElementByIdSafe('script_category_select');\n"
"          const scriptLocalIndexInput = getElementByIdSafe('script_local_index_input');\n"
"          const scriptNameInput = getElementByIdSafe('script_name_input');\n"
"          const scriptPayloadTextarea = getElementByIdSafe('script_payload_textarea');\n"

"          if (scriptCategorySelect) scriptCategorySelect.value = String(categoryIndex);\n"
"          if (scriptLocalIndexInput) scriptLocalIndexInput.value = String(localIndex);\n"
"          if (scriptNameInput) scriptNameInput.value = json.name || '';\n"
"          if (scriptPayloadTextarea) scriptPayloadTextarea.value = json.body || '';\n"

"          setTextIfExists(scriptStatusText, '');\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"
"      }\n"

"      async function loadCategoryByIndex(categoryIndex) {\n"
"        try {\n"
"          const response = await fetch(`/api/category?index=${categoryIndex}`);\n"
"          const categoryStatusText = getElementByIdSafe('category_status_text');\n"

"          if (!response.ok) {\n"
"            setTextIfExists(categoryStatusText, 'Not found');\n"
"            return;\n"
"          }\n"

"          const json = await response.json();\n"

"          const categoryIndexInput = getElementByIdSafe('category_index_input');\n"
"          const categoryNameInput = getElementByIdSafe('category_name_input');\n"

"          if (categoryIndexInput) categoryIndexInput.value = String(json.index);\n"
"          if (categoryNameInput) categoryNameInput.value = json.name || '';\n"

"          setTextIfExists(categoryStatusText, '');\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"
"      }\n"

"      // -------------------------------\n"
"      // Actions (save/delete)\n"
"      // -------------------------------\n"
"      async function saveScript() {\n"
"        const scriptStatusText = getElementByIdSafe('script_status_text');\n"

"        const scriptCategorySelect = getElementByIdSafe('script_category_select');\n"
"        const scriptLocalIndexInput = getElementByIdSafe('script_local_index_input');\n"
"        const scriptNameInput = getElementByIdSafe('script_name_input');\n"
"        const scriptPayloadTextarea = getElementByIdSafe('script_payload_textarea');\n"

"        const categoryIndex = parseIntegerOrDefault(scriptCategorySelect ? scriptCategorySelect.value : '0', 0);\n"
"        const localIndex = parseIntegerOrDefault(scriptLocalIndexInput ? scriptLocalIndexInput.value : '0', 0);\n"
"        const payload = scriptPayloadTextarea ? scriptPayloadTextarea.value : '';\n"

"        if (!payload.trim()) {\n"
"          setTextIfExists(scriptStatusText, 'Payload cannot be empty');\n"
"          return;\n"
"        }\n"

"        const requestBody = {\n"
"          index: localIndex,\n"
"          cat: categoryIndex,\n"
"          name: scriptNameInput ? scriptNameInput.value : '',\n"
"          body: payload\n"
"        };\n"

"        try {\n"
"          const response = await fetch('/api/script', {\n"
"            method: 'POST',\n"
"            headers: { 'Content-Type': 'application/json' },\n"
"            body: JSON.stringify(requestBody)\n"
"          });\n"

"          if (response.ok) {\n"
"            setTextIfExists(scriptStatusText, 'Saved');\n"
"            refreshCategoryLists();\n"
"          } else {\n"
"            setTextIfExists(scriptStatusText, 'Error');\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"
"      }\n"

"      async function deleteScript() {\n"
"        const scriptStatusText = getElementByIdSafe('script_status_text');\n"

"        const scriptCategorySelect = getElementByIdSafe('script_category_select');\n"
"        const scriptLocalIndexInput = getElementByIdSafe('script_local_index_input');\n"

"        const categoryIndex = parseIntegerOrDefault(scriptCategorySelect ? scriptCategorySelect.value : '0', 0);\n"
"        const localIndex = parseIntegerOrDefault(scriptLocalIndexInput ? scriptLocalIndexInput.value : '0', 0);\n"

"        try {\n"
"          const response = await fetch(`/api/script?index=${localIndex}&cat=${categoryIndex}`, { method: 'DELETE' });\n"

"          if (response.ok) {\n"
"            setTextIfExists(scriptStatusText, 'Deleted');\n"
"            const scriptNameInput = getElementByIdSafe('script_name_input');\n"
"            const scriptPayloadTextarea = getElementByIdSafe('script_payload_textarea');\n"
"            if (scriptNameInput) scriptNameInput.value = '';\n"
"            if (scriptPayloadTextarea) scriptPayloadTextarea.value = '';\n"
"            refreshCategoryLists();\n"
"          } else {\n"
"            setTextIfExists(scriptStatusText, 'Error');\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"
"      }\n"

"      async function saveCategory() {\n"
"        const categoryStatusText = getElementByIdSafe('category_status_text');\n"

"        const categoryIndexInput = getElementByIdSafe('category_index_input');\n"
"        const categoryNameInput = getElementByIdSafe('category_name_input');\n"

"        const categoryIndex = parseIntegerOrDefault(categoryIndexInput ? categoryIndexInput.value : '0', 0);\n"
"        const categoryName = categoryNameInput ? categoryNameInput.value : '';\n"

"        const requestBody = { index: categoryIndex, name: categoryName };\n"

"        try {\n"
"          const response = await fetch('/api/category', {\n"
"            method: 'POST',\n"
"            headers: { 'Content-Type': 'application/json' },\n"
"            body: JSON.stringify(requestBody)\n"
"          });\n"

"          if (response.ok) {\n"
"            setTextIfExists(categoryStatusText, 'Saved');\n"
"            refreshCategoryLists();\n"
"          } else {\n"
"            setTextIfExists(categoryStatusText, 'Error');\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"
"      }\n"

"      async function deleteCategory() {\n"
"        const categoryStatusText = getElementByIdSafe('category_status_text');\n"

"        const categoryIndexInput = getElementByIdSafe('category_index_input');\n"
"        const categoryNameInput = getElementByIdSafe('category_name_input');\n"

"        const categoryIndex = parseIntegerOrDefault(categoryIndexInput ? categoryIndexInput.value : '0', 0);\n"

"        try {\n"
"          const response = await fetch(`/api/category?index=${categoryIndex}`, { method: 'DELETE' });\n"

"          if (response.ok) {\n"
"            setTextIfExists(categoryStatusText, 'Deleted');\n"
"            if (categoryNameInput) categoryNameInput.value = '';\n"
"            refreshCategoryLists();\n"
"          } else {\n"
"            setTextIfExists(categoryStatusText, 'Error');\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"
"      }\n"

"      // -------------------------------\n"
"      // Event wiring\n"
"      // -------------------------------\n"
"      window.addEventListener('load', () => {\n"
"        try {\n"
"          const scriptLoadButton = getElementByIdSafe('script_load_button');\n"
"          if (scriptLoadButton) {\n"
"            scriptLoadButton.addEventListener('click', () => {\n"
"              const scriptCategorySelect = getElementByIdSafe('script_category_select');\n"
"              const scriptLocalIndexInput = getElementByIdSafe('script_local_index_input');\n"

"              const categoryIndex = parseIntegerOrDefault(scriptCategorySelect ? scriptCategorySelect.value : '0', 0);\n"
"              const localIndex = parseIntegerOrDefault(scriptLocalIndexInput ? scriptLocalIndexInput.value : '0', 0);\n"

"              loadScriptByLocalIndex(localIndex, categoryIndex);\n"
"            });\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const browseCategorySelect = getElementByIdSafe('script_browse_category_select');\n"
"          if (browseCategorySelect) {\n"
"            browseCategorySelect.addEventListener('change', (event) => {\n"
"              refreshScriptsForCategory(parseIntegerOrDefault(event.target.value, 0));\n"
"            });\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const scriptExistingList = getElementByIdSafe('script_existing_list');\n"
"          if (scriptExistingList) {\n"
"            scriptExistingList.addEventListener('click', (event) => {\n"
"              const item = event.target.closest('.list-item');\n"
"              if (!item) return;\n"
"              const browseCatSel = getElementByIdSafe('script_browse_category_select');\n"
"              const catIdx = parseIntegerOrDefault(browseCatSel ? browseCatSel.value : '0', 0);\n"
"              const localIdx = parseIntegerOrDefault(item.dataset.value, 0);\n"
"              loadScriptByLocalIndex(localIdx, catIdx);\n"
"            });\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const addNewButton = getElementByIdSafe('script_add_new_button');\n"
"          if (addNewButton) addNewButton.addEventListener('click', addNewScriptInBrowseCategory);\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const scriptSaveButton = getElementByIdSafe('script_save_button');\n"
"          if (scriptSaveButton) scriptSaveButton.addEventListener('click', saveScript);\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const scriptDeleteButton = getElementByIdSafe('script_delete_button');\n"
"          if (scriptDeleteButton) scriptDeleteButton.addEventListener('click', deleteScript);\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const categoryLoadButton = getElementByIdSafe('category_load_button');\n"
"          if (categoryLoadButton) {\n"
"            categoryLoadButton.addEventListener('click', () => {\n"
"              const categoryIndexInput = getElementByIdSafe('category_index_input');\n"
"              const categoryIndex = parseIntegerOrDefault(categoryIndexInput ? categoryIndexInput.value : '0', 0);\n"
"              loadCategoryByIndex(categoryIndex);\n"
"            });\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const existingCategoriesListSelect = getElementByIdSafe('category_existing_list');\n"
"          if (existingCategoriesListSelect) {\n"
"            existingCategoriesListSelect.addEventListener('click', (event) => {\n"
"              const item = event.target.closest('.list-item');\n"
"              if (!item) return;\n"
"              const selectedCategoryIndex = parseIntegerOrDefault(item.dataset.value, 0);\n"
"              loadCategoryByIndex(selectedCategoryIndex);\n"
"            });\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const categorySaveButton = getElementByIdSafe('category_save_button');\n"
"          if (categorySaveButton) categorySaveButton.addEventListener('click', saveCategory);\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const categoryDeleteButton = getElementByIdSafe('category_delete_button');\n"
"          if (categoryDeleteButton) categoryDeleteButton.addEventListener('click', deleteCategory);\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const categoryAddNewButton = getElementByIdSafe('category_add_new_button');\n"
"          if (categoryAddNewButton) categoryAddNewButton.addEventListener('click', addNewCategory);\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          refreshCategoryLists();\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"
"      });\n"
"    </script>\n"
"  </body>\n"
"</html>\n"
;