// Bluetooth web portal HTML (single page)
const char *BLUETOOTH_WEB_PORTAL_HTML =
"<!doctype html>\n"
"<html lang=\"en\">\n"
"  <head>\n"
"    <meta charset=\"utf-8\" />\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
"    <title>PolyCast5 BT Portal</title>\n"

"    <style>\n"
"      :root {\n"
"        --page-padding: 16px;\n"
"        --block-gap: 12px;\n"
"        --label-gap-top: 10px;\n"
"        --label-gap-bottom: 6px;\n"
"      }\n"

"      body {\n"
"        font-family: system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif;\n"
"        margin: var(--page-padding);\n"
"        line-height: 1.35;\n"
"      }\n"

"      hr {\n"
"        margin: 18px 0;\n"
"      }\n"

"      label {\n"
"        display: block;\n"
"        margin: var(--label-gap-top) 0 var(--label-gap-bottom);\n"
"        font-weight: 600;\n"
"      }\n"

"      input, textarea, select, button {\n"
"        width: 100%;\n"
"        box-sizing: border-box;\n"
"        font: inherit;\n"
"      }\n"

"      textarea {\n"
"        height: 180px;\n"
"        resize: vertical;\n"
"      }\n"

"      .row {\n"
"        display: flex;\n"
"        gap: 10px;\n"
"        align-items: center;\n"
"      }\n"

"      .row > * {\n"
"        flex: 1;\n"
"      }\n"

"      .row .fit {\n"
"        flex: 0 0 auto;\n"
"        width: auto;\n"
"        padding: 8px 12px;\n"
"      }\n"

"      .buttons {\n"
"        display: flex;\n"
"        gap: 10px;\n"
"        flex-wrap: wrap;\n"
"        margin-top: var(--block-gap);\n"
"      }\n"

"      .buttons button {\n"
"        width: auto;\n"
"        padding: 8px 12px;\n"
"      }\n"

"      .status {\n"
"        margin-left: 6px;\n"
"        font-weight: 600;\n"
"      }\n"

"      .small-note {\n"
"        opacity: 0.85;\n"
"      }\n"

"      .list {\n"
"        height: 160px;\n"
"      }\n"

"      code.inline {\n"
"        font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
"        font-size: 0.95em;\n"
"      }\n"
"    </style>\n"
"  </head>\n"

"  <body>\n"
"    <h2>PolyCast5 BT Portal</h2>\n"

"    <hr />\n"
"    <h3>Manage Categories</h3>\n"
"    <p>Bluetooth scripts are organized into categories to help make finding them easier.</p>\n"
"    <p>\n"
"      For example, if you want all your passwords in one place, create a category named\n"
"      <code class=\"inline\">Passwords</code> and save them under that.\n"
"    </p>\n"
"    <p class=\"small-note\">Category indexes are 0-based (0, 1, 2, ...).</p>\n"
"    <p>\n"
"      A tutorial is also available here:\n"
"      <span class=\"small-note\">https://polycast5.com/blogs/docs/using-the-bluetooth-auto-keyboard/</span>\n"
"    </p>\n"

"    <div>\n"
"      <label for=\"category_index_input\">Category index</label>\n"
"      <div class=\"row\">\n"
"        <input id=\"category_index_input\" type=\"number\" min=\"0\" value=\"0\" />\n"
"        <button id=\"category_load_button\" class=\"fit\" type=\"button\">Load</button>\n"
"      </div>\n"
"    </div>\n"

"    <div>\n"
"      <label for=\"category_name_input\">Category name</label>\n"
"      <input id=\"category_name_input\" maxlength=\"32\" placeholder=\"Group name\" />\n"
"    </div>\n"

"    <div class=\"buttons\">\n"
"      <button id=\"category_save_button\" type=\"button\">Save (add/edit)</button>\n"
"      <button id=\"category_delete_button\" type=\"button\">Delete</button>\n"
"      <span id=\"category_status_text\" class=\"status\"></span>\n"
"    </div>\n"

"    <h4>Existing Categories</h4>\n"
"    <select id=\"category_existing_list\" class=\"list\" size=\"6\"></select>\n"

"    <hr />\n"
"    <h3>Edit Script (by category)</h3>\n"
"    <p>Pick a category below to save specific scripts to.</p>\n"
"    <p class=\"small-note\">Script indexes are also 0-based (0, 1, 2, ...).</p>\n"

"    <div>\n"
"      <label for=\"script_category_select\">Category</label>\n"
"      <select id=\"script_category_select\"></select>\n"
"    </div>\n"

"    <div>\n"
"      <label for=\"script_local_index_input\">Script index (local)</label>\n"
"      <div class=\"row\">\n"
"        <input id=\"script_local_index_input\" type=\"number\" min=\"0\" max=\"15\" value=\"0\" />\n"
"        <button id=\"script_load_button\" class=\"fit\" type=\"button\">Load</button>\n"
"      </div>\n"
"    </div>\n"

"    <div>\n"
"      <label for=\"script_name_input\">Name</label>\n"
"      <input id=\"script_name_input\" maxlength=\"32\" placeholder=\"Short label for device menu\" />\n"
"    </div>\n"

"    <div>\n"
"      <label for=\"script_payload_textarea\">Payload</label>\n"
"      <textarea id=\"script_payload_textarea\" placeholder=\"What the device should type\u2026\"></textarea>\n"
"    </div>\n"

"    <div class=\"buttons\">\n"
"      <button id=\"script_save_button\" type=\"button\">Save (add/edit)</button>\n"
"      <button id=\"script_delete_button\" type=\"button\">Delete</button>\n"
"      <span id=\"script_status_text\" class=\"status\"></span>\n"
"    </div>\n"

"    <p>Here are some additional commands so you can do more than just type text:</p>\n"
"    <p class=\"small-note\">\n"
"      &lt;delay=x&gt; - Wait for x milliseconds<br />\n"
"      &lt;hold:c=x&gt; - Hold c for x milliseconds<br />\n"
"      &lt;enter&gt; - Enter<br />\n"
"      &lt;tab&gt; - Tab<br />\n"
"      &lt;esc&gt; - Escape<br />\n"
"      &lt;ctrl&gt; - Ctrl<br />\n"
"      &lt;shift&gt; - Shift<br />\n"
"      &lt;alt&gt; - Alt/Option<br />\n"
"      &lt;win&gt; - Windows/Cmd<br />\n"
"      &lt;space&gt; - Space<br />\n"
"      &lt;bs&gt; - Backspace<br />\n"
"      &lt;del&gt; - Forward delete<br />\n"
"      &lt;up&gt; - Up arrow<br />\n"
"      &lt;down&gt; - Down arrow<br />\n"
"      &lt;left&gt; - Left arrow<br />\n"
"      &lt;right&gt; - Right arrow<br />\n"
"      &lt;home&gt; - Home<br />\n"
"      &lt;pgup&gt; - Page up<br />\n"
"      &lt;pgdn&gt; - Page down<br />\n"
"      &lt;fx&gt; - Function x (e.g. f1, f2, etc.)<br />\n"
"      &lt;down:c&gt; - Hold c down until &lt;up:c&gt; is called<br />\n"
"      &lt;up:c&gt; - Release c if &lt;down:c&gt; was called<br />\n"
"      <br />\n"
"      You can also combine commands like &lt;ctrl+shift+v&gt; or &lt;ctrl+c&gt;.<br />\n"
"      <br />\n"
"      Example: &lt;win+s&gt;&lt;delay=500&gt;browser&lt;enter&gt;&lt;delay=500&gt;https://youtu.be/dQw4w9WgXcQ&lt;enter&gt;<br />\n"
"      <br />\n"
"      More examples: github.com/RoboticWorx/PolyCast5/tree/main/scripts/bluetooth_examples\n"
"    </p>\n"

"    <hr />\n"
"    <h3>Existing Scripts (global order)</h3>\n"
"    <p class=\"small-note\">\n"
"      Selecting here loads by global index (you may need to adjust the local index). Fields will show that script\u2019s category.\n"
"    </p>\n"
"    <select id=\"script_existing_global_list\" class=\"list\" size=\"6\"></select>\n"

"    <script>\n"
"      // -------------------------------\n"
"      // DOM helpers\n"
"      // -------------------------------\n"
"      function getElementByIdSafe(elementId) {\n"
"        return document.getElementById(elementId);\n"
"      }\n"

"      function parseIntegerOrDefault(value, defaultValue) {\n"
"        const parsedValue = parseInt(String(value), 10);\n"
"        return Number.isFinite(parsedValue) ? parsedValue : defaultValue;\n"
"      }\n"

"      function setTextIfExists(element, text) {\n"
"        if (element) element.textContent = text;\n"
"      }\n"

"      // -------------------------------\n"
"      // API refreshers\n"
"      // -------------------------------\n"
"      async function refreshGlobalScriptList() {\n"
"        try {\n"
"          const response = await fetch('/api/scripts');\n"
"          if (!response.ok) return;\n"

"          const json = await response.json();\n"
"          const globalScriptListSelect = getElementByIdSafe('script_existing_global_list');\n"
"          if (!globalScriptListSelect) return;\n"

"          globalScriptListSelect.innerHTML = '';\n"

"          for (let globalIndex = 0; globalIndex < json.count; globalIndex++) {\n"
"            const option = document.createElement('option');\n"
"            option.value = String(globalIndex);\n"
"            option.textContent = `${globalIndex}: ${json.labels[globalIndex] || '(unnamed)'}`;\n"
"            globalScriptListSelect.appendChild(option);\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"
"      }\n"

"      async function refreshCategoryLists() {\n"
"        try {\n"
"          const response = await fetch('/api/categories');\n"
"          if (!response.ok) return;\n"

"          const json = await response.json();\n"

"          const existingCategoriesListSelect = getElementByIdSafe('category_existing_list');\n"
"          const scriptCategorySelect = getElementByIdSafe('script_category_select');\n"

"          if (existingCategoriesListSelect) existingCategoriesListSelect.innerHTML = '';\n"
"          if (scriptCategorySelect) scriptCategorySelect.innerHTML = '';\n"

"          for (let categoryIndex = 0; categoryIndex < json.count; categoryIndex++) {\n"
"            const categoryName = json.names[categoryIndex] || '(unnamed)';\n"

"            if (existingCategoriesListSelect) {\n"
"              const listOption = document.createElement('option');\n"
"              listOption.value = String(categoryIndex);\n"
"              listOption.textContent = `${categoryIndex}: ${categoryName}`;\n"
"              existingCategoriesListSelect.appendChild(listOption);\n"
"            }\n"

"            if (scriptCategorySelect) {\n"
"              const selectOption = document.createElement('option');\n"
"              selectOption.value = String(categoryIndex);\n"
"              selectOption.textContent = categoryName;\n"
"              scriptCategorySelect.appendChild(selectOption);\n"
"            }\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"
"      }\n"

"      // -------------------------------\n"
"      // Loaders\n"
"      // -------------------------------\n"
"      async function loadScriptByGlobalIndex(globalIndex) {\n"
"        try {\n"
"          const response = await fetch(`/api/script?index=${globalIndex}`);\n"
"          const scriptStatusText = getElementByIdSafe('script_status_text');\n"

"          if (!response.ok) {\n"
"            setTextIfExists(scriptStatusText, 'Not found');\n"
"            return;\n"
"          }\n"

"          const json = await response.json();\n"

"          const scriptCategorySelect = getElementByIdSafe('script_category_select');\n"
"          const scriptLocalIndexInput = getElementByIdSafe('script_local_index_input');\n"
"          const scriptNameInput = getElementByIdSafe('script_name_input');\n"
"          const scriptPayloadTextarea = getElementByIdSafe('script_payload_textarea');\n"

"          if (scriptCategorySelect) scriptCategorySelect.value = String(json.cat || 0);\n"
"          if (scriptLocalIndexInput) scriptLocalIndexInput.value = String(json.index);\n"
"          if (scriptNameInput) scriptNameInput.value = json.name || '';\n"
"          if (scriptPayloadTextarea) scriptPayloadTextarea.value = json.body || '';\n"

"          setTextIfExists(scriptStatusText, '');\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"
"      }\n"

"      async function loadScriptByLocalIndex(localIndex, categoryIndex) {\n"
"        try {\n"
"          const response = await fetch(`/api/script?index=${localIndex}&cat=${categoryIndex}`);\n"
"          const scriptStatusText = getElementByIdSafe('script_status_text');\n"

"          if (!response.ok) {\n"
"            setTextIfExists(scriptStatusText, 'Not found');\n"
"            return;\n"
"          }\n"

"          const json = await response.json();\n"

"          const scriptCategorySelect = getElementByIdSafe('script_category_select');\n"
"          const scriptLocalIndexInput = getElementByIdSafe('script_local_index_input');\n"
"          const scriptNameInput = getElementByIdSafe('script_name_input');\n"
"          const scriptPayloadTextarea = getElementByIdSafe('script_payload_textarea');\n"

"          if (scriptCategorySelect) scriptCategorySelect.value = String(categoryIndex);\n"
"          if (scriptLocalIndexInput) scriptLocalIndexInput.value = String(localIndex);\n"
"          if (scriptNameInput) scriptNameInput.value = json.name || '';\n"
"          if (scriptPayloadTextarea) scriptPayloadTextarea.value = json.body || '';\n"

"          setTextIfExists(scriptStatusText, '');\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"
"      }\n"

"      async function loadCategoryByIndex(categoryIndex) {\n"
"        try {\n"
"          const response = await fetch(`/api/category?index=${categoryIndex}`);\n"
"          const categoryStatusText = getElementByIdSafe('category_status_text');\n"

"          if (!response.ok) {\n"
"            setTextIfExists(categoryStatusText, 'Not found');\n"
"            return;\n"
"          }\n"

"          const json = await response.json();\n"

"          const categoryIndexInput = getElementByIdSafe('category_index_input');\n"
"          const categoryNameInput = getElementByIdSafe('category_name_input');\n"

"          if (categoryIndexInput) categoryIndexInput.value = String(json.index);\n"
"          if (categoryNameInput) categoryNameInput.value = json.name || '';\n"

"          setTextIfExists(categoryStatusText, '');\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"
"      }\n"

"      // -------------------------------\n"
"      // Actions (save/delete)\n"
"      // -------------------------------\n"
"      async function saveScript() {\n"
"        const scriptStatusText = getElementByIdSafe('script_status_text');\n"

"        const scriptCategorySelect = getElementByIdSafe('script_category_select');\n"
"        const scriptLocalIndexInput = getElementByIdSafe('script_local_index_input');\n"
"        const scriptNameInput = getElementByIdSafe('script_name_input');\n"
"        const scriptPayloadTextarea = getElementByIdSafe('script_payload_textarea');\n"

"        const categoryIndex = parseIntegerOrDefault(scriptCategorySelect ? scriptCategorySelect.value : '0', 0);\n"
"        const localIndex = parseIntegerOrDefault(scriptLocalIndexInput ? scriptLocalIndexInput.value : '0', 0);\n"

"        const requestBody = {\n"
"          index: localIndex,\n"
"          cat: categoryIndex,\n"
"          name: scriptNameInput ? scriptNameInput.value : '',\n"
"          body: scriptPayloadTextarea ? scriptPayloadTextarea.value : ''\n"
"        };\n"

"        try {\n"
"          const response = await fetch('/api/script', {\n"
"            method: 'POST',\n"
"            headers: { 'Content-Type': 'application/json' },\n"
"            body: JSON.stringify(requestBody)\n"
"          });\n"

"          if (response.ok) {\n"
"            setTextIfExists(scriptStatusText, 'Saved');\n"
"            refreshGlobalScriptList();\n"
"          } else {\n"
"            setTextIfExists(scriptStatusText, 'Error');\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"
"      }\n"

"      async function deleteScript() {\n"
"        const scriptStatusText = getElementByIdSafe('script_status_text');\n"

"        const scriptCategorySelect = getElementByIdSafe('script_category_select');\n"
"        const scriptLocalIndexInput = getElementByIdSafe('script_local_index_input');\n"

"        const categoryIndex = parseIntegerOrDefault(scriptCategorySelect ? scriptCategorySelect.value : '0', 0);\n"
"        const localIndex = parseIntegerOrDefault(scriptLocalIndexInput ? scriptLocalIndexInput.value : '0', 0);\n"

"        try {\n"
"          const response = await fetch(`/api/script?index=${localIndex}&cat=${categoryIndex}`, { method: 'DELETE' });\n"

"          if (response.ok) {\n"
"            setTextIfExists(scriptStatusText, 'Deleted');\n"
"            refreshGlobalScriptList();\n"
"          } else {\n"
"            setTextIfExists(scriptStatusText, 'Error');\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"
"      }\n"

"      async function saveCategory() {\n"
"        const categoryStatusText = getElementByIdSafe('category_status_text');\n"

"        const categoryIndexInput = getElementByIdSafe('category_index_input');\n"
"        const categoryNameInput = getElementByIdSafe('category_name_input');\n"

"        const categoryIndex = parseIntegerOrDefault(categoryIndexInput ? categoryIndexInput.value : '0', 0);\n"
"        const categoryName = categoryNameInput ? categoryNameInput.value : '';\n"

"        const requestBody = { index: categoryIndex, name: categoryName };\n"

"        try {\n"
"          const response = await fetch('/api/category', {\n"
"            method: 'POST',\n"
"            headers: { 'Content-Type': 'application/json' },\n"
"            body: JSON.stringify(requestBody)\n"
"          });\n"

"          if (response.ok) {\n"
"            setTextIfExists(categoryStatusText, 'Saved');\n"
"            refreshCategoryLists();\n"
"          } else {\n"
"            setTextIfExists(categoryStatusText, 'Error');\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"
"      }\n"

"      async function deleteCategory() {\n"
"        const categoryStatusText = getElementByIdSafe('category_status_text');\n"

"        const categoryIndexInput = getElementByIdSafe('category_index_input');\n"
"        const categoryNameInput = getElementByIdSafe('category_name_input');\n"

"        const categoryIndex = parseIntegerOrDefault(categoryIndexInput ? categoryIndexInput.value : '0', 0);\n"

"        try {\n"
"          const response = await fetch(`/api/category?index=${categoryIndex}`, { method: 'DELETE' });\n"

"          if (response.ok) {\n"
"            setTextIfExists(categoryStatusText, 'Deleted');\n"
"            if (categoryNameInput) categoryNameInput.value = '';\n"
"            refreshCategoryLists();\n"
"          } else {\n"
"            setTextIfExists(categoryStatusText, 'Error');\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"
"      }\n"

"      // -------------------------------\n"
"      // Event wiring\n"
"      // -------------------------------\n"
"      window.addEventListener('load', () => {\n"
"        try {\n"
"          const scriptLoadButton = getElementByIdSafe('script_load_button');\n"
"          if (scriptLoadButton) {\n"
"            scriptLoadButton.addEventListener('click', () => {\n"
"              const scriptCategorySelect = getElementByIdSafe('script_category_select');\n"
"              const scriptLocalIndexInput = getElementByIdSafe('script_local_index_input');\n"

"              const categoryIndex = parseIntegerOrDefault(scriptCategorySelect ? scriptCategorySelect.value : '0', 0);\n"
"              const localIndex = parseIntegerOrDefault(scriptLocalIndexInput ? scriptLocalIndexInput.value : '0', 0);\n"

"              loadScriptByLocalIndex(localIndex, categoryIndex);\n"
"            });\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const globalScriptListSelect = getElementByIdSafe('script_existing_global_list');\n"
"          if (globalScriptListSelect) {\n"
"            globalScriptListSelect.addEventListener('change', (event) => {\n"
"              const selectedGlobalIndex = parseIntegerOrDefault(event.target.value || '0', 0);\n"
"              loadScriptByGlobalIndex(selectedGlobalIndex);\n"
"            });\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const scriptSaveButton = getElementByIdSafe('script_save_button');\n"
"          if (scriptSaveButton) scriptSaveButton.addEventListener('click', saveScript);\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const scriptDeleteButton = getElementByIdSafe('script_delete_button');\n"
"          if (scriptDeleteButton) scriptDeleteButton.addEventListener('click', deleteScript);\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const categoryLoadButton = getElementByIdSafe('category_load_button');\n"
"          if (categoryLoadButton) {\n"
"            categoryLoadButton.addEventListener('click', () => {\n"
"              const categoryIndexInput = getElementByIdSafe('category_index_input');\n"
"              const categoryIndex = parseIntegerOrDefault(categoryIndexInput ? categoryIndexInput.value : '0', 0);\n"
"              loadCategoryByIndex(categoryIndex);\n"
"            });\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const existingCategoriesListSelect = getElementByIdSafe('category_existing_list');\n"
"          if (existingCategoriesListSelect) {\n"
"            existingCategoriesListSelect.addEventListener('change', (event) => {\n"
"              const selectedCategoryIndex = parseIntegerOrDefault(event.target.value || '0', 0);\n"
"              loadCategoryByIndex(selectedCategoryIndex);\n"
"            });\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const categorySaveButton = getElementByIdSafe('category_save_button');\n"
"          if (categorySaveButton) categorySaveButton.addEventListener('click', saveCategory);\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const categoryDeleteButton = getElementByIdSafe('category_delete_button');\n"
"          if (categoryDeleteButton) categoryDeleteButton.addEventListener('click', deleteCategory);\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          refreshCategoryLists();\n"
"          refreshGlobalScriptList();\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"
"      });\n"
"    </script>\n"
"  </body>\n"
"</html>\n"
;
