// Bluetooth web portal HTML (single page)
const char *BLUETOOTH_WEB_PORTAL_HTML =
"<!doctype html>\n"
"<html lang=\"en\">\n"
"  <head>\n"
"    <meta charset=\"utf-8\" />\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
"    <title>PolyCast5 BT Portal</title>\n"

"    <style>\n"
"      :root {\n"
"        --bg: #060b18;\n"
"        --bg-panel: #0c1528;\n"
"        --border: #1a3068;\n"
"        --accent: #5ba3f5;\n"
"        --accent-dim: #0047ab;\n"
"        --accent-glow: rgba(0,71,171,0.25);\n"
"        --text: #d6dff0;\n"
"        --text-bright: #f0f4fa;\n"
"        --danger: #e04060;\n"
"        --success: #3ddc84;\n"
"        --page-padding: 20px;\n"
"        --block-gap: 12px;\n"
"        --label-gap-top: 12px;\n"
"        --label-gap-bottom: 5px;\n"
"        --radius: 4px;\n"
"      }\n"

"      *, *::before, *::after { box-sizing: border-box; }\n"

"      body {\n"
"        font-family: 'Courier New', Courier, monospace;\n"
"        margin: 0;\n"
"        padding: var(--page-padding);\n"
"        background: var(--bg);\n"
"        color: var(--text);\n"
"        line-height: 1.45;\n"
"        max-width: 640px;\n"
"        margin: 0 auto;\n"
"        position: relative;\n"
"      }\n"

"      body::after {\n"
"        content: '';\n"
"        position: fixed;\n"
"        inset: 0;\n"
"        background: repeating-linear-gradient(\n"
"          0deg,\n"
"          transparent,\n"
"          transparent 2px,\n"
"          rgba(0,0,0,0.08) 2px,\n"
"          rgba(0,0,0,0.08) 4px\n"
"        );\n"
"        pointer-events: none;\n"
"        z-index: 9999;\n"
"      }\n"

"      h2 {\n"
"        color: var(--accent);\n"
"        text-transform: uppercase;\n"
"        letter-spacing: 3px;\n"
"        font-size: 1.3em;\n"
"        border-bottom: 2px solid var(--accent-dim);\n"
"        padding-bottom: 10px;\n"
"        text-shadow: 0 0 10px rgba(91,163,245,0.4);\n"
"      }\n"

"      h3 {\n"
"        color: var(--accent);\n"
"        font-size: 1em;\n"
"        text-transform: uppercase;\n"
"        letter-spacing: 2px;\n"
"        margin-bottom: 6px;\n"
"        text-shadow: 0 0 8px rgba(91,163,245,0.3);\n"
"      }\n"

"      h3::before {\n"
"        content: '> ';\n"
"        color: var(--accent);\n"
"      }\n"

"      h4 {\n"
"        color: var(--text-bright);\n"
"        font-size: 0.9em;\n"
"        text-transform: uppercase;\n"
"        letter-spacing: 1px;\n"
"        margin-top: 16px;\n"
"        margin-bottom: 8px;\n"
"      }\n"

"      hr {\n"
"        border: none;\n"
"        border-top: 1px solid var(--border);\n"
"        margin: 22px 0;\n"
"        box-shadow: 0 1px 0 var(--accent-glow);\n"
"      }\n"

"      p {\n"
"        font-size: 0.85em;\n"
"        margin: 8px 0;\n"
"      }\n"

"      ul {\n"
"        font-size: 0.85em;\n"
"        margin: 8px 0;\n"
"        padding-left: 20px;\n"
"      }\n"

"      li {\n"
"        margin: 4px 0;\n"
"      }\n"

"      label {\n"
"        display: block;\n"
"        margin: var(--label-gap-top) 0 var(--label-gap-bottom);\n"
"        font-weight: 600;\n"
"        color: var(--accent);\n"
"        text-transform: uppercase;\n"
"        font-size: 0.8em;\n"
"        letter-spacing: 1px;\n"
"      }\n"

"      input, textarea, select {\n"
"        width: 100%;\n"
"        font: inherit;\n"
"        font-size: 0.9em;\n"
"        background: var(--bg);\n"
"        color: var(--text-bright);\n"
"        border: 1px solid var(--border);\n"
"        border-radius: var(--radius);\n"
"        padding: 8px 10px;\n"
"        outline: none;\n"
"        transition: border-color 0.2s, box-shadow 0.2s;\n"
"      }\n"

"      input:focus, textarea:focus, select:focus {\n"
"        border-color: var(--accent);\n"
"        box-shadow: 0 0 8px var(--accent-glow), inset 0 0 4px var(--accent-glow);\n"
"      }\n"

"      textarea {\n"
"        height: 180px;\n"
"        resize: vertical;\n"
"      }\n"

"      button {\n"
"        font: inherit;\n"
"        font-size: 0.85em;\n"
"        text-transform: uppercase;\n"
"        letter-spacing: 1px;\n"
"        background: var(--bg-panel);\n"
"        color: var(--accent);\n"
"        border: 1px solid var(--accent-dim);\n"
"        border-radius: var(--radius);\n"
"        padding: 8px 16px;\n"
"        cursor: pointer;\n"
"        transition: all 0.15s;\n"
"      }\n"

"      button:hover {\n"
"        background: var(--accent-dim);\n"
"        color: var(--bg);\n"
"        box-shadow: 0 0 12px var(--accent-glow);\n"
"      }\n"

"      button:active {\n"
"        transform: scale(0.97);\n"
"      }\n"

"      .row {\n"
"        display: flex;\n"
"        gap: 10px;\n"
"        align-items: center;\n"
"      }\n"

"      .row > * {\n"
"        flex: 1;\n"
"      }\n"

"      .row .fit {\n"
"        flex: 0 0 auto;\n"
"        width: auto;\n"
"      }\n"

"      .buttons {\n"
"        display: flex;\n"
"        gap: 10px;\n"
"        flex-wrap: wrap;\n"
"        margin-top: var(--block-gap);\n"
"      }\n"

"      .buttons button {\n"
"        width: auto;\n"
"      }\n"

"      .status {\n"
"        margin-left: 6px;\n"
"        font-weight: 600;\n"
"        color: var(--success);\n"
"        font-size: 0.85em;\n"
"        text-shadow: 0 0 6px rgba(61,220,132,0.3);\n"
"      }\n"

"      .small-note {\n"
"        opacity: 0.75;\n"
"        font-size: 0.8em;\n"
"      }\n"

"      .list {\n"
"        height: 160px;\n"
"        overflow-y: auto;\n"
"        border: 1px solid var(--border);\n"
"        border-radius: var(--radius);\n"
"        background: var(--bg);\n"
"      }\n"

"      .list-item {\n"
"        padding: 6px 10px;\n"
"        cursor: pointer;\n"
"        font-family: inherit;\n"
"        font-size: 0.9em;\n"
"        color: var(--text-bright);\n"
"      }\n"

"      .list-item:hover {\n"
"        background: var(--accent-glow);\n"
"      }\n"

"      .list-item:active {\n"
"        background: var(--accent-dim);\n"
"        color: var(--bg);\n"
"      }\n"

"      select option {\n"
"        padding: 4px 6px;\n"
"      }\n"

"      code.inline {\n"
"        font-family: inherit;\n"
"        background: var(--bg-panel);\n"
"        color: var(--accent);\n"
"        border: 1px solid var(--border);\n"
"        border-radius: 3px;\n"
"        padding: 1px 6px;\n"
"        font-size: 0.95em;\n"
"      }\n"

"      a {\n"
"        color: var(--accent);\n"
"        text-decoration: none;\n"
"        border-bottom: 1px dashed var(--accent-dim);\n"
"        word-wrap: break-word;\n"
"        overflow-wrap: break-word;\n"
"        transition: color 0.15s;\n"
"      }\n"

"      a:hover {\n"
"        color: var(--text-bright);\n"
"      }\n"

"      ::selection {\n"
"        background: var(--accent);\n"
"        color: var(--bg);\n"
"      }\n"

"      ::-webkit-scrollbar {\n"
"        width: 6px;\n"
"        height: 6px;\n"
"      }\n"

"      ::-webkit-scrollbar-track {\n"
"        background: var(--bg);\n"
"      }\n"

"      ::-webkit-scrollbar-thumb {\n"
"        background: var(--accent-dim);\n"
"        border-radius: 3px;\n"
"      }\n"
"    </style>\n"
"  </head>\n"

"  <body>\n"
"    <h2>PolyCast5 BT Portal</h2>\n"

"    <p>\n"
"      <strong>Welcome to the Bluetooth Portal!</strong>\n"
"    </p>\n"
"    <p>\n"
"      This is a super capable feature that can do a lot, so some docs are available below should you need them.\n"
"    </p>\n"
"    <ul>\n"
"      <li>\n"
"        General insta-type use:\n"
"        <a href=\"https://polycast5.com/blogs/docs/bluetooth-auto-keyboard\" target=\"_blank\" rel=\"noopener noreferrer\">polycast5.com/blogs/docs/bluetooth-auto-keyboard</a>\n"
"      </li>\n"
"      <li>\n"
"        Password manager to instantly find/autofill passwords offline:\n"
"        <a href=\"https://polycast5.com/blogs/docs/offline-password-manager-ai-keyboard\" target=\"_blank\" rel=\"noopener noreferrer\">polycast5.com/blogs/docs/offline-password-manager-ai-keyboard</a>\n"
"      </li>\n"
"      <li>\n"
"        Execute custom scripts via speech for quick access:\n"
"        <a href=\"https://polycast5.com/blogs/docs/custom-autotype-commands-ai-keyboard\" target=\"_blank\" rel=\"noopener noreferrer\">polycast5.com/blogs/docs/custom-autotype-commands-ai-keyboard</a>\n"
"      </li>\n"
"    </ul>\n"
"    <p>\n"
"      <i>Note: You will need to reconnect to your actual Wi-Fi network first to access the website links.</i>\n"
"    </p>\n"

"    <hr />\n"
"    <h3>Manage Categories</h3>\n"
"    <p>Bluetooth scripts are organized into categories to help make finding them easier.</p>\n"
"    <p>\n"
"      For example, if you want all your passwords in one place, create a category named\n"
"      <code class=\"inline\">Passwords</code> and save them under that.\n"
"    </p>\n"
"    <p class=\"small-note\">Category indexes are 0-based (0, 1, 2, ...).</p>\n"
"    <p>\n"

"    <div>\n"
"      <label for=\"category_index_input\">Category index</label>\n"
"      <div class=\"row\">\n"
"        <input id=\"category_index_input\" type=\"number\" min=\"0\" value=\"0\" />\n"
"        <button id=\"category_load_button\" class=\"fit\" type=\"button\">Load</button>\n"
"      </div>\n"
"    </div>\n"

"    <div>\n"
"      <label for=\"category_name_input\">Category name</label>\n"
"      <input id=\"category_name_input\" maxlength=\"32\" placeholder=\"Group name\" />\n"
"    </div>\n"

"    <div class=\"buttons\">\n"
"      <button id=\"category_save_button\" type=\"button\">Save (add/edit)</button>\n"
"      <button id=\"category_delete_button\" type=\"button\">Delete</button>\n"
"      <span id=\"category_status_text\" class=\"status\"></span>\n"
"    </div>\n"

"    <h4>Existing Categories</h4>\n"
"    <div id=\"category_existing_list\" class=\"list\"></div>\n"
"    <div class=\"buttons\">\n"
"      <button id=\"category_add_new_button\" type=\"button\">+ Add New</button>\n"
"    </div>\n"

"    <hr />\n"
"    <h3>Existing Scripts</h3>\n"
"    <p class=\"small-note\">\n"
"      Select a category to browse its scripts. Click one to load it for editing.\n"
"    </p>\n"
"    <div>\n"
"      <label for=\"script_browse_category_select\">Category</label>\n"
"      <select id=\"script_browse_category_select\"></select>\n"
"    </div>\n"
"    <div id=\"script_existing_list\" class=\"list\" style=\"margin-top:8px\"></div>\n"
"    <div class=\"buttons\">\n"
"      <button id=\"script_add_new_button\" type=\"button\">+ Add New</button>\n"
"    </div>\n"

"    <hr />\n"
"    <h3>Edit Script</h3>\n"
"    <p>Pick a category below to save specific scripts to. Use + Add New above to start a new one.</p>\n"
"    <p class=\"small-note\">Script indexes are also 0-based (0, 1, 2, ...).</p>\n"

"    <div>\n"
"      <label for=\"script_category_select\">Category</label>\n"
"      <select id=\"script_category_select\"></select>\n"
"    </div>\n"

"    <div>\n"
"      <label for=\"script_local_index_input\">Script index (local)</label>\n"
"      <div class=\"row\">\n"
"        <input id=\"script_local_index_input\" type=\"number\" min=\"0\" max=\"997\" value=\"0\" />\n"
"        <button id=\"script_load_button\" class=\"fit\" type=\"button\">Load</button>\n"
"      </div>\n"
"    </div>\n"

"    <div>\n"
"      <label for=\"script_name_input\">Name</label>\n"
"      <input id=\"script_name_input\" maxlength=\"32\" placeholder=\"Short label for device menu\" />\n"
"    </div>\n"

"    <div>\n"
"      <label for=\"script_payload_textarea\">Payload</label>\n"
"      <textarea id=\"script_payload_textarea\" placeholder=\"What the device should type\u2026\"></textarea>\n"
"    </div>\n"

"    <div class=\"buttons\">\n"
"      <button id=\"script_save_button\" type=\"button\">Save (add/edit)</button>\n"
"      <button id=\"script_delete_button\" type=\"button\">Delete</button>\n"
"      <span id=\"script_status_text\" class=\"status\"></span>\n"
"    </div>\n"

"    <p>Here are some additional commands so you can do more than just type text:</p>\n"
"    <p class=\"small-note\">\n"
"      &lt;delay=x&gt; - Wait for x milliseconds<br />\n"
"      &lt;hold:c=x&gt; - Hold c for x milliseconds<br />\n"
"      &lt;enter&gt; - Enter<br />\n"
"      &lt;tab&gt; - Tab<br />\n"
"      &lt;esc&gt; - Escape<br />\n"
"      &lt;ctrl&gt; - Ctrl<br />\n"
"      &lt;shift&gt; - Shift<br />\n"
"      &lt;alt&gt; - Alt/Option<br />\n"
"      &lt;win&gt; - Windows/Cmd<br />\n"
"      &lt;space&gt; - Space<br />\n"
"      &lt;bs&gt; - Backspace<br />\n"
"      &lt;del&gt; - Forward delete<br />\n"
"      &lt;up&gt; - Up arrow<br />\n"
"      &lt;down&gt; - Down arrow<br />\n"
"      &lt;left&gt; - Left arrow<br />\n"
"      &lt;right&gt; - Right arrow<br />\n"
"      &lt;home&gt; - Home<br />\n"
"      &lt;pgup&gt; - Page up<br />\n"
"      &lt;pgdn&gt; - Page down<br />\n"
"      &lt;fx&gt; - Function x (e.g. f1, f2, etc.)<br />\n"
"      &lt;select_prior&gt; - Selects all text typed before it<br />\n"
"      &lt;down:c&gt; - Hold c down until &lt;up:c&gt; is called<br />\n"
"      &lt;up:c&gt; - Release c if &lt;down:c&gt; was called<br />\n"
"      <br />\n"
"      You can also combine commands like &lt;ctrl+shift+v&gt; or &lt;ctrl+c&gt;.<br />\n"
"      <br />\n"
"      Example: &lt;win+s&gt;&lt;delay=500&gt;browser&lt;enter&gt;&lt;delay=500&gt;https://youtu.be/dQw4w9WgXcQ&lt;enter&gt;<br />\n"
"      <br />\n"
"      More examples are available below:\n"
"      <a href=\"https://github.com/RoboticWorx/PolyCast5/tree/main/scripts/bluetooth_examples\" target=\"_blank\" rel=\"noopener noreferrer\">github.com/RoboticWorx/PolyCast5/tree/main/scripts/bluetooth_examples</a>\n"
"    </p>\n"

"    <hr />\n"
"    <h3>Backup &amp; Restore</h3>\n"
"    <p class=\"small-note\">\n"
"      Backup all scripts and categories to a file, or import to restore them. Keeping a safe backup of any passwords is highly recommended.\n"
"    </p>\n"
"    <div class=\"buttons\">\n"
"      <button id=\"export_button\" type=\"button\">Export</button>\n"
"      <button id=\"import_button\" type=\"button\">Import</button>\n"
"      <input id=\"import_file_input\" type=\"file\" accept=\".json,application/json\" hidden />\n"
"      <span id=\"backup_status_text\" class=\"status\"></span>\n"
"    </div>\n"

"    <script>\n"
"      // -------------------------------\n"
"      // DOM helpers\n"
"      // -------------------------------\n"
"      function getElementByIdSafe(elementId) {\n"
"        return document.getElementById(elementId);\n"
"      }\n"

"      function parseIntegerOrDefault(value, defaultValue) {\n"
"        const parsedValue = parseInt(String(value), 10);\n"
"        return Number.isFinite(parsedValue) ? parsedValue : defaultValue;\n"
"      }\n"

"      function setTextIfExists(element, text) {\n"
"        if (element) element.textContent = text;\n"
"      }\n"

"      // -------------------------------\n"
"      // API refreshers\n"
"      // -------------------------------\n"
"      var categoryCount = 0;\n"
"      var categoryScriptCounts = [];\n"
"      var categoryDeleteBusy = false;\n"

"      // Script the editor is bound to: null = new script, else {id, tag, cat, local} from its last load/save.\n"
"      // Save/Delete act on exactly that script (the device finds it by id even if it moved) and refuse (409) if it was changed or deleted since.\n"
"      var editingScript = null;\n"
"      var editorGeneration = 0;\n"
"      var scriptRequestBusy = false;\n"
"      var SCRIPT_STALE_MESSAGE = 'This script was changed or deleted since it was loaded. Copy your text if you need it, then reload the script.';\n"
"      var scriptLoadSeq = 0;\n"
"      var newestLoadPending = false;\n"
"      var newestLoadGeneration = 0;\n"
"      var indexBoxTyped = false;\n"

"      function bindScriptEditor(script) {\n"
"        editingScript = script;\n"
"        editorGeneration++;\n"
"      }\n"

"      function newScriptLocalIndex(catIdx) {\n"
"        return (catIdx < categoryScriptCounts.length) ? categoryScriptCounts[catIdx] : 0;\n"
"      }\n"

"      // New-script mode: the index box previews where Save will append in the selected category, unless the user typed an index to Load\n"
"      function showNewScriptIndex() {\n"
"        const scriptCategorySelect = getElementByIdSafe('script_category_select');\n"
"        const scriptLocalIndexInput = getElementByIdSafe('script_local_index_input');\n"
"        const catIdx = parseIntegerOrDefault(scriptCategorySelect ? scriptCategorySelect.value : '0', 0);\n"
"        if (scriptLocalIndexInput && !indexBoxTyped) scriptLocalIndexInput.value = String(newScriptLocalIndex(catIdx));\n"
"      }\n"

"      function setScriptIndexBox(value) {\n"
"        const scriptLocalIndexInput = getElementByIdSafe('script_local_index_input');\n"
"        if (scriptLocalIndexInput) scriptLocalIndexInput.value = String(value);\n"
"        indexBoxTyped = false;\n"
"      }\n"

"      // The label as the device stores it: first 32 UTF-8 bytes, then bytes <= ' ' trimmed (a cut multibyte char decodes as U+FFFD)\n"
"      function storedLabel(name) {\n"
"        const bytes = new TextEncoder().encode(name).slice(0, 32);\n"
"        let start = 0;\n"
"        let end = bytes.length;\n"
"        while (start < end && bytes[start] <= 32) start++;\n"
"        while (end > start && bytes[end - 1] <= 32) end--;\n"
"        return new TextDecoder().decode(bytes.slice(start, end));\n"
"      }\n"

"      // A 409 'unknown' means the ids changed (reboot, import), and 'stale' can be an earlier Save that landed without its reply.\n"
"      // Look for the script in its category (where it was loaded first) holding what was loaded or exactly what was sent, and\n"
"      // rebind to it so a retry goes through. For 'stale' the script still exists, so only under its own id\n"
"      async function rebindAfterStale(sentName, sentBody, sameId, destCat) {\n"
"        const bound = editingScript;\n"
"        if (!bound) return false;\n"
"        const generation = editorGeneration;\n"
"        const loadSeq = scriptLoadSeq;\n"
"        const movedOn = () => (generation !== editorGeneration) || (loadSeq !== scriptLoadSeq);\n"
"        const matches = (json) => {\n"
"          if (sameId && json.id !== bound.id) return false;\n"
"          const unchanged = (json.tag === bound.tag);\n"
"          const ours = (sentBody !== null) && (json.body === sentBody) && (json.name === storedLabel(sentName));\n"
"          return unchanged || ours;\n"
"        };\n"

"        // One GET: 'match' (sets found), 'mine' (the bound id without a match: ids are unique, so stop), 'end' past the category, else 'other'\n"
"        let found = null;\n"
"        let foundLocal = -1;\n"
"        const probe = async (cat, local) => {\n"
"          const response = await fetch(`/api/script?index=${local}&cat=${cat}`);\n"
"          if (!response.ok) return 'end';\n"
"          const json = await response.json();\n"
"          if (matches(json)) {\n"
"            found = json;\n"
"            foundLocal = local;\n"
"            return 'match';\n"
"          }\n"
"          return (json.id === bound.id) ? 'mine' : 'other';\n"
"        };\n"

"        try {\n"
"          // The loaded position first, then the rest of its category, then the category a lost-reply move went to\n"
"          let result = await probe(bound.cat, bound.local);\n"
"          for (let i = 0; result !== 'match' && result !== 'mine'; i++) {\n"
"            if (movedOn()) return false;\n"
"            if (i === bound.local) continue;\n"
"            result = await probe(bound.cat, i);\n"
"            if (result === 'end') break;\n"
"          }\n"
"          if (result !== 'match' && result !== 'mine' && sameId && destCat !== undefined && destCat !== bound.cat) {\n"
"            for (let i = 0; ; i++) {\n"
"              if (movedOn()) return false;\n"
"              result = await probe(destCat, i);\n"
"              if (result !== 'other') break;\n"
"            }\n"
"          }\n"
"          if (result !== 'match' || movedOn()) return false;\n"
"          bindScriptEditor({ id: found.id, tag: found.tag, cat: found.cat, local: foundLocal });\n"
"          setScriptIndexBox(foundLocal);\n"
"          return true;\n"
"        } catch (error) {\n"
"          return false;\n"
"        }\n"
"      }\n"

"      async function refreshScriptsForCategory(categoryIndex) {\n"
"        try {\n"
"          const list = getElementByIdSafe('script_existing_list');\n"
"          if (!list) return;\n"
"          list.innerHTML = '';\n"

"          for (let i = 0; ; i++) {\n"
"            try {\n"
"              const r = await fetch(`/api/script?index=${i}&cat=${categoryIndex}`);\n"
"              if (!r.ok) break;\n"
"              const j = await r.json();\n"
"              const item = document.createElement('div');\n"
"              item.className = 'list-item';\n"
"              item.dataset.value = String(i);\n"
"              item.dataset.id = j.id || '';\n"
"              item.textContent = `${i}: ${j.name || ('Script ' + (i + 1) + ' (unnamed)')}`;\n"
"              list.appendChild(item);\n"
"            } catch (e) { break; }\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"
"      }\n"

"      function addNewScriptInBrowseCategory() {\n"
"        const browseCatSel = getElementByIdSafe('script_browse_category_select');\n"
"        const catIdx = parseIntegerOrDefault(browseCatSel ? browseCatSel.value : '0', 0);\n"
"        const nextIdx = (catIdx < categoryScriptCounts.length) ? categoryScriptCounts[catIdx] : 0;\n"

"        const scriptStatusText = getElementByIdSafe('script_status_text');\n"
"        if (nextIdx >= 998) {\n"
"          setTextIfExists(scriptStatusText, 'Max scripts reached');\n"
"          return;\n"
"        }\n"

"        const scriptCategorySelect = getElementByIdSafe('script_category_select');\n"
"        const scriptLocalIndexInput = getElementByIdSafe('script_local_index_input');\n"
"        const scriptNameInput = getElementByIdSafe('script_name_input');\n"
"        const scriptPayloadTextarea = getElementByIdSafe('script_payload_textarea');\n"

"        bindScriptEditor(null);\n"
"        if (scriptCategorySelect) scriptCategorySelect.value = String(catIdx);\n"
"        setScriptIndexBox(nextIdx);\n"
"        if (scriptNameInput) { scriptNameInput.value = ''; scriptNameInput.focus(); }\n"
"        if (scriptPayloadTextarea) scriptPayloadTextarea.value = '';\n"
"        setTextIfExists(scriptStatusText, 'New script at index ' + nextIdx);\n"
"      }\n"

"      function addNewCategory() {\n"
"        const categoryStatusText = getElementByIdSafe('category_status_text');\n"
"        if (categoryCount >= 50) {\n"
"          setTextIfExists(categoryStatusText, 'Max categories reached (50)');\n"
"          return;\n"
"        }\n"

"        const categoryIndexInput = getElementByIdSafe('category_index_input');\n"
"        const categoryNameInput = getElementByIdSafe('category_name_input');\n"

"        if (categoryIndexInput) categoryIndexInput.value = String(categoryCount);\n"
"        if (categoryNameInput) { categoryNameInput.value = ''; categoryNameInput.focus(); }\n"
"        setTextIfExists(categoryStatusText, 'New category at index ' + categoryCount);\n"
"      }\n"

"      async function refreshCategoryLists() {\n"
"        try {\n"
"          const response = await fetch('/api/categories');\n"
"          if (!response.ok) return;\n"

"          const json = await response.json();\n"
"          categoryCount = json.count || 0;\n"
"          categoryScriptCounts = json.script_counts || [];\n"

"          const existingCategoriesListSelect = getElementByIdSafe('category_existing_list');\n"
"          const scriptCategorySelect = getElementByIdSafe('script_category_select');\n"
"          const browseCategorySelect = getElementByIdSafe('script_browse_category_select');\n"

"          const prevBrowse = browseCategorySelect ? browseCategorySelect.value : '0';\n"
"          const prevScriptCat = scriptCategorySelect ? scriptCategorySelect.value : '0';\n"

"          if (existingCategoriesListSelect) existingCategoriesListSelect.innerHTML = '';\n"
"          if (scriptCategorySelect) scriptCategorySelect.innerHTML = '';\n"
"          if (browseCategorySelect) browseCategorySelect.innerHTML = '';\n"

"          for (let categoryIndex = 0; categoryIndex < json.count; categoryIndex++) {\n"
"            const categoryName = json.names[categoryIndex] || '(unnamed)';\n"

"            if (existingCategoriesListSelect) {\n"
"              const item = document.createElement('div');\n"
"              item.className = 'list-item';\n"
"              item.dataset.value = String(categoryIndex);\n"
"              item.textContent = `${categoryIndex}: ${categoryName}`;\n"
"              existingCategoriesListSelect.appendChild(item);\n"
"            }\n"

"            if (scriptCategorySelect) {\n"
"              const selectOption = document.createElement('option');\n"
"              selectOption.value = String(categoryIndex);\n"
"              selectOption.textContent = categoryName;\n"
"              scriptCategorySelect.appendChild(selectOption);\n"
"            }\n"

"            if (browseCategorySelect) {\n"
"              const browseOption = document.createElement('option');\n"
"              browseOption.value = String(categoryIndex);\n"
"              browseOption.textContent = categoryName;\n"
"              browseCategorySelect.appendChild(browseOption);\n"
"            }\n"
"          }\n"

"          // A value with no matching option (first load, deleted category) leaves a select blank; fall back to the first\n"
"          if (scriptCategorySelect) {\n"
"            scriptCategorySelect.value = prevScriptCat;\n"
"            if (scriptCategorySelect.selectedIndex < 0 && scriptCategorySelect.options.length > 0) scriptCategorySelect.selectedIndex = 0;\n"
"          }\n"
"          if (editingScript === null) showNewScriptIndex();\n"
"          if (browseCategorySelect) {\n"
"            browseCategorySelect.value = prevBrowse;\n"
"            if (browseCategorySelect.selectedIndex < 0 && browseCategorySelect.options.length > 0) browseCategorySelect.selectedIndex = 0;\n"
"            refreshScriptsForCategory(parseIntegerOrDefault(browseCategorySelect.value, 0));\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"
"      }\n"

"      // -------------------------------\n"
"      // Loaders\n"
"      // -------------------------------\n"
"      async function loadScriptByLocalIndex(localIndex, categoryIndex, expectedId) {\n"
"        // Only the newest load fills the editor, and not once the editor was rebound meanwhile (+ Add New, import, category delete)\n"
"        const seq = ++scriptLoadSeq;\n"
"        const generation = editorGeneration;\n"
"        const scriptStatusText = getElementByIdSafe('script_status_text');\n"
"        newestLoadPending = true;\n"
"        newestLoadGeneration = generation;\n"
"        try {\n"
"          const response = await fetch(`/api/script?index=${localIndex}&cat=${categoryIndex}`);\n"
"          if (seq !== scriptLoadSeq || generation !== editorGeneration) return;\n"

"          if (!response.ok) {\n"
"            // A list click on a script that is gone means the list is stale\n"
"            if (expectedId) {\n"
"              setTextIfExists(scriptStatusText, 'The list was out of date and has been refreshed.');\n"
"              refreshCategoryLists();\n"
"            } else {\n"
"              setTextIfExists(scriptStatusText, 'Not found');\n"
"            }\n"
"            return;\n"
"          }\n"

"          const json = await response.json();\n"
"          if (seq !== scriptLoadSeq || generation !== editorGeneration) return;\n"

"          // A list click carries the id it was listed with; another script at that position means the list is stale\n"
"          if (expectedId && json.id !== expectedId) {\n"
"            setTextIfExists(scriptStatusText, 'The list was out of date and has been refreshed. Click the script again.');\n"
"            refreshCategoryLists();\n"
"            return;\n"
"          }\n"

"          const scriptCategorySelect = getElementByIdSafe('script_category_select');\n"
"          const scriptNameInput = getElementByIdSafe('script_name_input');\n"
"          const scriptPayloadTextarea = getElementByIdSafe('script_payload_textarea');\n"

"          if (scriptCategorySelect) scriptCategorySelect.value = String(categoryIndex);\n"
"          setScriptIndexBox(localIndex);\n"
"          if (scriptNameInput) scriptNameInput.value = json.name || '';\n"
"          if (scriptPayloadTextarea) scriptPayloadTextarea.value = json.body || '';\n"
"          bindScriptEditor({ id: json.id, tag: json.tag, cat: json.cat, local: localIndex });\n"

"          setTextIfExists(scriptStatusText, '');\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        } finally {\n"
"          // A Save/Delete refused while this load was pending left 'Loading...'; clear it\n"
"          if (seq === scriptLoadSeq) {\n"
"            newestLoadPending = false;\n"
"            if (scriptStatusText && scriptStatusText.textContent === 'Loading...') setTextIfExists(scriptStatusText, '');\n"
"          }\n"
"        }\n"
"      }\n"

"      async function loadCategoryByIndex(categoryIndex) {\n"
"        try {\n"
"          const response = await fetch(`/api/category?index=${categoryIndex}`);\n"
"          const categoryStatusText = getElementByIdSafe('category_status_text');\n"

"          if (!response.ok) {\n"
"            setTextIfExists(categoryStatusText, 'Not found');\n"
"            return;\n"
"          }\n"

"          const json = await response.json();\n"

"          const categoryIndexInput = getElementByIdSafe('category_index_input');\n"
"          const categoryNameInput = getElementByIdSafe('category_name_input');\n"

"          if (categoryIndexInput) categoryIndexInput.value = String(json.index);\n"
"          if (categoryNameInput) categoryNameInput.value = json.name || '';\n"

"          setTextIfExists(categoryStatusText, '');\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"
"      }\n"

"      // -------------------------------\n"
"      // Actions (save/delete)\n"
"      // -------------------------------\n"
"      async function saveScript() {\n"
"        const scriptStatusText = getElementByIdSafe('script_status_text');\n"
"        if (scriptRequestBusy) return;\n"
"        if (newestLoadPending && newestLoadGeneration === editorGeneration) {\n"
"          setTextIfExists(scriptStatusText, 'Loading...');\n"
"          return;\n"
"        }\n"

"        const scriptCategorySelect = getElementByIdSafe('script_category_select');\n"
"        const scriptLocalIndexInput = getElementByIdSafe('script_local_index_input');\n"
"        const scriptNameInput = getElementByIdSafe('script_name_input');\n"
"        const scriptPayloadTextarea = getElementByIdSafe('script_payload_textarea');\n"

"        const payload = scriptPayloadTextarea ? scriptPayloadTextarea.value : '';\n"

"        if (!payload.trim()) {\n"
"          setTextIfExists(scriptStatusText, 'Payload cannot be empty');\n"
"          return;\n"
"        }\n"
"        if (!scriptCategorySelect || scriptCategorySelect.value === '') {\n"
"          setTextIfExists(scriptStatusText, 'Create a category first');\n"
"          return;\n"
"        }\n"

"        // The index box must show what Save writes: the loaded script, or the next free index for a new one\n"
"        const categoryIndex = parseIntegerOrDefault(scriptCategorySelect.value, 0);\n"
"        const boxIndex = parseIntegerOrDefault(scriptLocalIndexInput ? scriptLocalIndexInput.value : '', -1);\n"
"        if (editingScript && boxIndex !== editingScript.local) {\n"
"          setTextIfExists(scriptStatusText, (boxIndex >= 0 ? 'Press Load to open script ' + boxIndex : 'Press Load to open a script') + ', or + Add New for a new script');\n"
"          return;\n"
"        }\n"
"        if (!editingScript && boxIndex >= 0 && boxIndex < newScriptLocalIndex(categoryIndex)) {\n"
"          setTextIfExists(scriptStatusText, 'Script ' + boxIndex + ' already exists: press Load to edit it');\n"
"          return;\n"
"        }\n"

"        // Edit the bound script (a changed category moves it), or append a new one\n"
"        const name = scriptNameInput ? scriptNameInput.value : '';\n"
"        const requestBody = editingScript\n"
"          ? { id: editingScript.id, tag: editingScript.tag, from_cat: editingScript.cat, cat: categoryIndex, name: name, body: payload }\n"
"          : { new: true, cat: categoryIndex, name: name, body: payload };\n"
"        const generation = editorGeneration;\n"
"        const loadSeq = scriptLoadSeq;\n"

"        scriptRequestBusy = true;\n"
"        setTextIfExists(scriptStatusText, 'Saving...');\n"
"        try {\n"
"          const response = await fetch('/api/script', {\n"
"            method: 'POST',\n"
"            headers: { 'Content-Type': 'application/json' },\n"
"            body: JSON.stringify(requestBody)\n"
"          });\n"
"          let json = {};\n"
"          try { json = await response.json(); } catch (jsonError) {}\n"
"          // Only touch the editor if it was not rebound or reloaded meanwhile\n"
"          const current = (generation === editorGeneration) && (loadSeq === scriptLoadSeq);\n"

"          if (response.ok) {\n"
"            // Stay bound to the saved script; keep anything edited during the request\n"
"            if (current) {\n"
"              bindScriptEditor(json.tag ? { id: json.id, tag: json.tag, cat: json.cat, local: json.local } : null);\n"
"              if (json.tag) {\n"
"                setScriptIndexBox(json.local);\n"
"                if (scriptNameInput && scriptNameInput.value === name) scriptNameInput.value = json.name || '';\n"
"              }\n"
"            } else if (generation === editorGeneration && json.tag && (editingScript ? (editingScript.id === json.id) : requestBody.new)) {\n"
"              // A load is pending: update the binding in place (no generation bump) so that load can still land\n"
"              editingScript = { id: json.id, tag: json.tag, cat: json.cat, local: json.local };\n"
"              setScriptIndexBox(json.local);\n"
"            }\n"
"            const moveHint = current && (scriptCategorySelect.value !== String(categoryIndex));\n"
"            setTextIfExists(scriptStatusText, moveHint ? 'Saved. Save again to move it to the selected category' : 'Saved');\n"
"          } else if (response.status === 409) {\n"
"            // deleted: gone for good. unknown: ids changed (reboot, import), so look where it was loaded. stale: changed or moved\n"
"            if (json.error === 'deleted' && current) {\n"
"              // Keep the text so Save can store it again\n"
"              bindScriptEditor(null);\n"
"              indexBoxTyped = false;\n"
"              setTextIfExists(scriptStatusText, 'This script was deleted elsewhere. Save will add it as a new script.');\n"
"            } else if (json.error !== 'deleted' && current && await rebindAfterStale(name, payload, json.error === 'stale', categoryIndex)) {\n"
"              setTextIfExists(scriptStatusText, 'Reconnected to this script. Press Save again.');\n"
"            } else if (generation === editorGeneration) {\n"
"              // Not once another script loaded; a load still pending overwrites it when it lands\n"
"              setTextIfExists(scriptStatusText, SCRIPT_STALE_MESSAGE);\n"
"            }\n"
"          } else {\n"
"            // A failed write can leave an edit half-applied: take the slot's current tag so the retry still lands\n"
"            if (generation === editorGeneration && editingScript && json.tag) editingScript.tag = json.tag;\n"
"            setTextIfExists(scriptStatusText, (json.error === 'nvs') ? 'Error: device storage may be full' : 'Error');\n"
"          }\n"
"          refreshCategoryLists();\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"          // A new script may have been stored even though its reply was lost\n"
"          setTextIfExists(scriptStatusText, requestBody.new ? 'Connection lost: the script may have been saved. Check the list before saving again.' : 'Error');\n"
"          refreshCategoryLists();\n"
"        } finally {\n"
"          scriptRequestBusy = false;\n"
"        }\n"
"      }\n"

"      async function deleteScript() {\n"
"        const scriptStatusText = getElementByIdSafe('script_status_text');\n"
"        if (scriptRequestBusy) return;\n"
"        if (newestLoadPending && newestLoadGeneration === editorGeneration) {\n"
"          setTextIfExists(scriptStatusText, 'Loading...');\n"
"          return;\n"
"        }\n"

"        if (!editingScript) {\n"
"          setTextIfExists(scriptStatusText, 'Load a script to delete it');\n"
"          return;\n"
"        }\n"

"        // Delete only what the category and index box show: the loaded script\n"
"        const scriptCategorySelect = getElementByIdSafe('script_category_select');\n"
"        const scriptLocalIndexInput = getElementByIdSafe('script_local_index_input');\n"
"        const categoryIndex = parseIntegerOrDefault(scriptCategorySelect ? scriptCategorySelect.value : '', -1);\n"
"        const boxIndex = parseIntegerOrDefault(scriptLocalIndexInput ? scriptLocalIndexInput.value : '', -1);\n"
"        if (categoryIndex !== editingScript.cat || boxIndex !== editingScript.local) {\n"
"          setTextIfExists(scriptStatusText, 'Press Load to open the script you want to delete');\n"
"          return;\n"
"        }\n"
"        const generation = editorGeneration;\n"
"        const loadSeq = scriptLoadSeq;\n"

"        scriptRequestBusy = true;\n"
"        setTextIfExists(scriptStatusText, 'Deleting...');\n"
"        try {\n"
"          const response = await fetch(`/api/script?id=${encodeURIComponent(editingScript.id)}&tag=${encodeURIComponent(editingScript.tag)}&cat=${editingScript.cat}`, { method: 'DELETE' });\n"
"          const current = (generation === editorGeneration) && (loadSeq === scriptLoadSeq);\n"

"          if (response.ok) {\n"
"            setTextIfExists(scriptStatusText, 'Deleted');\n"
"            // Back to a new script. If only a load started meanwhile, drop the binding without a generation bump so that load can still land\n"
"            if (generation === editorGeneration) {\n"
"              if (current) bindScriptEditor(null);\n"
"              else editingScript = null;\n"
"              const scriptNameInput = getElementByIdSafe('script_name_input');\n"
"              const scriptPayloadTextarea = getElementByIdSafe('script_payload_textarea');\n"
"              if (scriptNameInput) scriptNameInput.value = '';\n"
"              if (scriptPayloadTextarea) scriptPayloadTextarea.value = '';\n"
"              indexBoxTyped = false;\n"
"            }\n"
"          } else if (response.status === 409) {\n"
"            let json = {};\n"
"            try { json = await response.json(); } catch (jsonError) {}\n"
"            const fresh = (generation === editorGeneration) && (loadSeq === scriptLoadSeq);\n"
"            if (json.error === 'deleted' && fresh) {\n"
"              // Already deleted (elsewhere, or by an earlier Delete whose reply was lost): same end state as a successful Delete\n"
"              bindScriptEditor(null);\n"
"              const scriptNameInput = getElementByIdSafe('script_name_input');\n"
"              const scriptPayloadTextarea = getElementByIdSafe('script_payload_textarea');\n"
"              if (scriptNameInput) scriptNameInput.value = '';\n"
"              if (scriptPayloadTextarea) scriptPayloadTextarea.value = '';\n"
"              indexBoxTyped = false;\n"
"              setTextIfExists(scriptStatusText, 'This script is already deleted.');\n"
"            } else if (json.error !== 'deleted' && fresh && await rebindAfterStale(null, null, json.error === 'stale')) {\n"
"              setTextIfExists(scriptStatusText, 'Reconnected to this script. Press Delete again.');\n"
"            } else if (generation === editorGeneration) {\n"
"              // Not once another script loaded; a load still pending overwrites it when it lands\n"
"              setTextIfExists(scriptStatusText, SCRIPT_STALE_MESSAGE);\n"
"            }\n"
"          } else {\n"
"            setTextIfExists(scriptStatusText, 'Error');\n"
"          }\n"
"          refreshCategoryLists();\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"          setTextIfExists(scriptStatusText, 'Error');\n"
"          refreshCategoryLists();\n"
"        } finally {\n"
"          scriptRequestBusy = false;\n"
"        }\n"
"      }\n"

"      async function saveCategory() {\n"
"        const categoryStatusText = getElementByIdSafe('category_status_text');\n"

"        const categoryIndexInput = getElementByIdSafe('category_index_input');\n"
"        const categoryNameInput = getElementByIdSafe('category_name_input');\n"

"        const categoryIndex = parseIntegerOrDefault(categoryIndexInput ? categoryIndexInput.value : '0', 0);\n"
"        const categoryName = categoryNameInput ? categoryNameInput.value : '';\n"

"        const requestBody = { index: categoryIndex, name: categoryName };\n"

"        try {\n"
"          const response = await fetch('/api/category', {\n"
"            method: 'POST',\n"
"            headers: { 'Content-Type': 'application/json' },\n"
"            body: JSON.stringify(requestBody)\n"
"          });\n"

"          if (response.ok) {\n"
"            setTextIfExists(categoryStatusText, 'Saved');\n"
"            refreshCategoryLists();\n"
"          } else {\n"
"            setTextIfExists(categoryStatusText, 'Error');\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"
"      }\n"

"      // Category ids above a deleted one shift down; keep the loaded script and the script selects on the same category\n"
"      function shiftCategorySelectsAfterDelete(deletedIndex) {\n"
"        const scriptStatusText = getElementByIdSafe('script_status_text');\n"
"        if (editingScript && editingScript.cat > deletedIndex) {\n"
"          editingScript.cat--;\n"
"        } else if (editingScript && editingScript.cat === deletedIndex) {\n"
"          // The loaded script went with its category; keep the text so Save can store it again\n"
"          bindScriptEditor(null);\n"
"          indexBoxTyped = false;\n"
"          setTextIfExists(scriptStatusText, 'The loaded script was deleted with its category. Save will add it as a new script.');\n"
"        }\n"

"        ['script_category_select', 'script_browse_category_select'].forEach((selectId) => {\n"
"          const select = getElementByIdSafe(selectId);\n"
"          if (!select || select.value === '') return;\n"
"          const selected = parseIntegerOrDefault(select.value, 0);\n"
"          if (selected > deletedIndex) {\n"
"            select.value = String(selected - 1);\n"
"          } else if (selected === deletedIndex) {\n"
"            if (selectId === 'script_category_select' && editingScript) {\n"
"              // A pending move into the deleted category is cancelled\n"
"              select.value = String(editingScript.cat);\n"
"              setTextIfExists(scriptStatusText, 'The category you were moving it to was deleted; the move was cancelled.');\n"
"            } else {\n"
"              select.selectedIndex = 0;\n"
"            }\n"
"          }\n"
"        });\n"
"      }\n"

"      async function deleteCategory() {\n"
"        if (categoryDeleteBusy) return;\n"
"        const categoryStatusText = getElementByIdSafe('category_status_text');\n"

"        const categoryIndexInput = getElementByIdSafe('category_index_input');\n"
"        const categoryNameInput = getElementByIdSafe('category_name_input');\n"

"        const categoryIndex = parseIntegerOrDefault(categoryIndexInput ? categoryIndexInput.value : '', -1);\n"

"        categoryDeleteBusy = true;\n"
"        try {\n"
"          // Name and script count come from the device, not the edit boxes, so the confirm names what is actually deleted\n"
"          const listResponse = await fetch('/api/categories');\n"
"          if (!listResponse.ok) {\n"
"            setTextIfExists(categoryStatusText, 'Error');\n"
"            return;\n"
"          }\n"
"          const list = await listResponse.json();\n"
"          if (categoryIndex < 0 || categoryIndex >= (list.count || 0)) {\n"
"            setTextIfExists(categoryStatusText, 'Not found');\n"
"            refreshCategoryLists();\n"
"            return;\n"
"          }\n"

"          const categoryName = (list.names && list.names[categoryIndex]) || '(unnamed)';\n"
"          const scriptCount = (list.script_counts && list.script_counts[categoryIndex]) || 0;\n"
"          const confirmText = (scriptCount > 0)\n"
"            ? 'Deleting category \"' + categoryName + '\" will also DELETE its ' + scriptCount + (scriptCount === 1 ? ' script' : ' scripts') + '. This cannot be undone. Continue?'\n"
"            : 'Delete category \"' + categoryName + '\"? It has no scripts. Continue?';\n"
"          if (!confirm(confirmText)) return;\n"

"          const response = await fetch(`/api/category?index=${categoryIndex}`, { method: 'DELETE' });\n"

"          if (response.ok) {\n"
"            setTextIfExists(categoryStatusText, 'Deleted');\n"
"            if (categoryNameInput) categoryNameInput.value = '';\n"
"            shiftCategorySelectsAfterDelete(categoryIndex);\n"
"            refreshCategoryLists();\n"
"          } else {\n"
"            setTextIfExists(categoryStatusText, 'Error');\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        } finally {\n"
"          categoryDeleteBusy = false;\n"
"        }\n"
"      }\n"

"      // Set the backup status line; isError paints it red, otherwise the default green.\n"
"      function setBackupStatus(message, isError) {\n"
"        const backupStatusText = getElementByIdSafe('backup_status_text');\n"
"        if (!backupStatusText) return;\n"
"        backupStatusText.textContent = message;\n"
"        backupStatusText.style.color = isError ? 'var(--danger)' : '';\n"
"      }\n"

"      // Reset the script editor to a new script so a stale binding/name/payload can't be Saved over a just-restored slot.\n"
"      function clearScriptEditor() {\n"
"        bindScriptEditor(null);\n"
"        indexBoxTyped = false;\n"
"        const scriptNameInput = getElementByIdSafe('script_name_input');\n"
"        const scriptPayloadTextarea = getElementByIdSafe('script_payload_textarea');\n"
"        if (scriptNameInput) scriptNameInput.value = '';\n"
"        if (scriptPayloadTextarea) scriptPayloadTextarea.value = '';\n"
"      }\n"

"      async function exportData() {\n"
"        try {\n"
"          const response = await fetch('/api/export');\n"
"          if (!response.ok) {\n"
"            setBackupStatus(response.status === 404 ? 'Nothing to export' : 'Export failed', response.status !== 404);\n"
"            return;\n"
"          }\n"
"          const blob = await response.blob();\n"
"          const url = URL.createObjectURL(blob);\n"
"          const anchor = document.createElement('a');\n"
"          anchor.href = url;\n"
"          anchor.download = 'polycast5-autotype.json';\n"
"          document.body.appendChild(anchor);\n"
"          anchor.click();\n"
"          document.body.removeChild(anchor);\n"
"          URL.revokeObjectURL(url);\n"
"          setBackupStatus('Exported', false);\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"          setBackupStatus('Export failed', true);\n"
"        }\n"
"      }\n"

"      var IMPORT_ERROR_MESSAGES = {\n"
"        bad_length: 'File is empty or too large.',\n"
"        oom: 'The device ran out of memory.',\n"
"        recv: 'The upload was interrupted.',\n"
"        bad_json: 'This is not a valid backup file.',\n"
"        bad_format: 'This is not a PolyCast5 autotype backup.',\n"
"        bad_version: 'This backup was made by an incompatible version.',\n"
"        bad_structure: 'The backup file is malformed.',\n"
"        bad_entry: 'The backup file has a damaged or malformed entry.',\n"
"        too_many: 'The file has more scripts or categories than the device allows.',\n"
"        script_too_large: 'A script in the file is larger than the 64KB limit.',\n"
"        wipe_failed: 'Could not prepare device storage.'\n"
"      };\n"

"      async function importData(file) {\n"
"        if (!file) return;\n"
"        if (!confirm('Importing will REPLACE all current scripts and categories. Continue?')) return;\n"
"        try {\n"
"          const text = await file.text();\n"
"          setBackupStatus('Importing...', false);\n"
"          const response = await fetch('/api/import', {\n"
"            method: 'POST',\n"
"            headers: { 'Content-Type': 'application/json' },\n"
"            body: text\n"
"          });\n"
"          let info = {};\n"
"          try { info = await response.json(); } catch (jsonError) {}\n"
"          if (response.ok && info.ok) {\n"
"            setBackupStatus('Imported ' + (info.scripts || 0) + ' scripts, ' + (info.categories || 0) + ' categories.', false);\n"
"            clearScriptEditor();\n"
"            refreshCategoryLists();\n"
"          } else if (info.error === 'nvs') {\n"
"            setBackupStatus('WARNING: storage filled up during import. Old data was erased and only ' + (info.scripts || 0) + ' scripts / ' + (info.categories || 0) + ' categories were restored - the rest is MISSING. Free space and re-import.', true);\n"
"            clearScriptEditor();\n"
"            refreshCategoryLists();\n"
"          } else {\n"
"            setBackupStatus((IMPORT_ERROR_MESSAGES[info.error] || 'Import failed.') + ' Your existing data was not changed.', true);\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"          setBackupStatus('Import failed.', true);\n"
"        }\n"
"      }\n"

"      // -------------------------------\n"
"      // Event wiring\n"
"      // -------------------------------\n"
"      window.addEventListener('load', () => {\n"
"        try {\n"
"          const scriptLoadButton = getElementByIdSafe('script_load_button');\n"
"          if (scriptLoadButton) {\n"
"            scriptLoadButton.addEventListener('click', () => {\n"
"              const scriptCategorySelect = getElementByIdSafe('script_category_select');\n"
"              const scriptLocalIndexInput = getElementByIdSafe('script_local_index_input');\n"

"              const categoryIndex = parseIntegerOrDefault(scriptCategorySelect ? scriptCategorySelect.value : '0', 0);\n"
"              const localIndex = parseIntegerOrDefault(scriptLocalIndexInput ? scriptLocalIndexInput.value : '0', 0);\n"

"              loadScriptByLocalIndex(localIndex, categoryIndex);\n"
"            });\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const scriptLocalIndexInput = getElementByIdSafe('script_local_index_input');\n"
"          if (scriptLocalIndexInput) scriptLocalIndexInput.addEventListener('input', () => { indexBoxTyped = true; });\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const scriptCategorySelect = getElementByIdSafe('script_category_select');\n"
"          if (scriptCategorySelect) {\n"
"            scriptCategorySelect.addEventListener('change', () => {\n"
"              const scriptStatusText = getElementByIdSafe('script_status_text');\n"
"              if (editingScript === null) showNewScriptIndex();\n"
"              else if (scriptCategorySelect.value === String(editingScript.cat)) setTextIfExists(scriptStatusText, '');\n"
"              else setTextIfExists(scriptStatusText, 'Save will move this script to the selected category');\n"
"            });\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const browseCategorySelect = getElementByIdSafe('script_browse_category_select');\n"
"          if (browseCategorySelect) {\n"
"            browseCategorySelect.addEventListener('change', (event) => {\n"
"              refreshScriptsForCategory(parseIntegerOrDefault(event.target.value, 0));\n"
"            });\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const scriptExistingList = getElementByIdSafe('script_existing_list');\n"
"          if (scriptExistingList) {\n"
"            scriptExistingList.addEventListener('click', (event) => {\n"
"              const item = event.target.closest('.list-item');\n"
"              if (!item) return;\n"
"              const browseCatSel = getElementByIdSafe('script_browse_category_select');\n"
"              const catIdx = parseIntegerOrDefault(browseCatSel ? browseCatSel.value : '0', 0);\n"
"              const localIdx = parseIntegerOrDefault(item.dataset.value, 0);\n"
"              loadScriptByLocalIndex(localIdx, catIdx, item.dataset.id);\n"
"            });\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const addNewButton = getElementByIdSafe('script_add_new_button');\n"
"          if (addNewButton) addNewButton.addEventListener('click', addNewScriptInBrowseCategory);\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const scriptSaveButton = getElementByIdSafe('script_save_button');\n"
"          if (scriptSaveButton) scriptSaveButton.addEventListener('click', saveScript);\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const scriptDeleteButton = getElementByIdSafe('script_delete_button');\n"
"          if (scriptDeleteButton) scriptDeleteButton.addEventListener('click', deleteScript);\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const categoryLoadButton = getElementByIdSafe('category_load_button');\n"
"          if (categoryLoadButton) {\n"
"            categoryLoadButton.addEventListener('click', () => {\n"
"              const categoryIndexInput = getElementByIdSafe('category_index_input');\n"
"              const categoryIndex = parseIntegerOrDefault(categoryIndexInput ? categoryIndexInput.value : '0', 0);\n"
"              loadCategoryByIndex(categoryIndex);\n"
"            });\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const existingCategoriesListSelect = getElementByIdSafe('category_existing_list');\n"
"          if (existingCategoriesListSelect) {\n"
"            existingCategoriesListSelect.addEventListener('click', (event) => {\n"
"              const item = event.target.closest('.list-item');\n"
"              if (!item) return;\n"
"              const selectedCategoryIndex = parseIntegerOrDefault(item.dataset.value, 0);\n"
"              loadCategoryByIndex(selectedCategoryIndex);\n"
"            });\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const categorySaveButton = getElementByIdSafe('category_save_button');\n"
"          if (categorySaveButton) categorySaveButton.addEventListener('click', saveCategory);\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const categoryDeleteButton = getElementByIdSafe('category_delete_button');\n"
"          if (categoryDeleteButton) categoryDeleteButton.addEventListener('click', deleteCategory);\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const categoryAddNewButton = getElementByIdSafe('category_add_new_button');\n"
"          if (categoryAddNewButton) categoryAddNewButton.addEventListener('click', addNewCategory);\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const exportButton = getElementByIdSafe('export_button');\n"
"          if (exportButton) exportButton.addEventListener('click', exportData);\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          const importButton = getElementByIdSafe('import_button');\n"
"          const importFileInput = getElementByIdSafe('import_file_input');\n"
"          if (importButton && importFileInput) {\n"
"            importButton.addEventListener('click', () => importFileInput.click());\n"
"            importFileInput.addEventListener('change', (event) => {\n"
"              const file = event.target.files && event.target.files[0];\n"
"              importData(file);\n"
"              event.target.value = '';\n"
"            });\n"
"          }\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"

"        try {\n"
"          refreshCategoryLists();\n"
"        } catch (error) {\n"
"          console.error(error);\n"
"        }\n"
"      });\n"
"    </script>\n"
"  </body>\n"
"</html>\n"
;