#ifndef LCD_ASSET_MACROS_H
#define LCD_ASSET_MACROS_H

#include "polycast5_macros.h"

/* ANIMATIONS START */

// City
#define ANIM_CITY_1  "A:/anim/city/anim_city_1.bin"
#define ANIM_CITY_2  "A:/anim/city/anim_city_2.bin"
#define ANIM_CITY_3  "A:/anim/city/anim_city_3.bin"
#define ANIM_CITY_4  "A:/anim/city/anim_city_4.bin"
#define ANIM_CITY_5  "A:/anim/city/anim_city_5.bin"
#define ANIM_CITY_6  "A:/anim/city/anim_city_6.bin"
#define ANIM_CITY_7  "A:/anim/city/anim_city_7.bin"
#define ANIM_CITY_8  "A:/anim/city/anim_city_8.bin"
#define ANIM_CITY_9  "A:/anim/city/anim_city_9.bin"
#define ANIM_CITY_10 "A:/anim/city/anim_city_10.bin"
#define ANIM_CITY_11 "A:/anim/city/anim_city_11.bin"
#define ANIM_CITY_12 "A:/anim/city/anim_city_12.bin"
#define ANIM_CITY_13 "A:/anim/city/anim_city_13.bin"
#define ANIM_CITY_14 "A:/anim/city/anim_city_14.bin"
#define ANIM_CITY_15 "A:/anim/city/anim_city_15.bin"
#define ANIM_CITY_16 "A:/anim/city/anim_city_16.bin"
#define ANIM_CITY_17 "A:/anim/city/anim_city_17.bin"
#define ANIM_CITY_18 "A:/anim/city/anim_city_18.bin"
#define ANIM_CITY_19 "A:/anim/city/anim_city_19.bin"
#define ANIM_CITY_20 "A:/anim/city/anim_city_20.bin"
#define ANIM_CITY_21 "A:/anim/city/anim_city_21.bin"
#define ANIM_CITY_22 "A:/anim/city/anim_city_22.bin"
#define ANIM_CITY_23 "A:/anim/city/anim_city_23.bin"
#define ANIM_CITY_24 "A:/anim/city/anim_city_24.bin"
#define ANIM_CITY_25 "A:/anim/city/anim_city_25.bin"
#define ANIM_CITY_26 "A:/anim/city/anim_city_26.bin"
#define ANIM_CITY_27 "A:/anim/city/anim_city_27.bin"
#define ANIM_CITY_28 "A:/anim/city/anim_city_28.bin"
#define ANIM_CITY_29 "A:/anim/city/anim_city_29.bin"
#define ANIM_CITY_30 "A:/anim/city/anim_city_30.bin"
#define ANIM_CITY_31 "A:/anim/city/anim_city_31.bin"
#define ANIM_CITY_32 "A:/anim/city/anim_city_32.bin"
#define ANIM_CITY_33 "A:/anim/city/anim_city_33.bin"
#define ANIM_CITY_34 "A:/anim/city/anim_city_34.bin"
#define ANIM_CITY_35 "A:/anim/city/anim_city_35.bin"
#define ANIM_CITY_36 "A:/anim/city/anim_city_36.bin"
#define ANIM_CITY_37 "A:/anim/city/anim_city_37.bin"
#define ANIM_CITY_38 "A:/anim/city/anim_city_38.bin"
#define ANIM_CITY_39 "A:/anim/city/anim_city_39.bin"
#define ANIM_CITY_40 "A:/anim/city/anim_city_40.bin"
#define ANIM_CITY_41 "A:/anim/city/anim_city_41.bin"
#define ANIM_CITY_42 "A:/anim/city/anim_city_42.bin"
#define ANIM_CITY_43 "A:/anim/city/anim_city_43.bin"
#define ANIM_CITY_44 "A:/anim/city/anim_city_44.bin"
#define ANIM_CITY_45 "A:/anim/city/anim_city_45.bin"
#define ANIM_CITY_46 "A:/anim/city/anim_city_46.bin"
#define ANIM_CITY_47 "A:/anim/city/anim_city_47.bin"
#define ANIM_CITY_48 "A:/anim/city/anim_city_48.bin"
#define ANIM_CITY_49 "A:/anim/city/anim_city_49.bin"
#define ANIM_CITY_50 "A:/anim/city/anim_city_50.bin"
#define ANIM_CITY_51 "A:/anim/city/anim_city_51.bin"
#define ANIM_CITY_52 "A:/anim/city/anim_city_52.bin"
#define ANIM_CITY_53 "A:/anim/city/anim_city_53.bin"
#define ANIM_CITY_54 "A:/anim/city/anim_city_54.bin"
#define ANIM_CITY_55 "A:/anim/city/anim_city_55.bin"
#define ANIM_CITY_56 "A:/anim/city/anim_city_56.bin"
#define ANIM_CITY_57 "A:/anim/city/anim_city_57.bin"
#define ANIM_CITY_58 "A:/anim/city/anim_city_58.bin"
#define ANIM_CITY_59 "A:/anim/city/anim_city_59.bin"
#define ANIM_CITY_60 "A:/anim/city/anim_city_60.bin"

// Black Hole
#define ANIM_BLACK_HOLE_1  "A:/anim/black_hole/anim_black_hole_1.bin"
#define ANIM_BLACK_HOLE_2  "A:/anim/black_hole/anim_black_hole_2.bin"
#define ANIM_BLACK_HOLE_3  "A:/anim/black_hole/anim_black_hole_3.bin"
#define ANIM_BLACK_HOLE_4  "A:/anim/black_hole/anim_black_hole_4.bin"
#define ANIM_BLACK_HOLE_5  "A:/anim/black_hole/anim_black_hole_5.bin"
#define ANIM_BLACK_HOLE_6  "A:/anim/black_hole/anim_black_hole_6.bin"
#define ANIM_BLACK_HOLE_7  "A:/anim/black_hole/anim_black_hole_7.bin"
#define ANIM_BLACK_HOLE_8  "A:/anim/black_hole/anim_black_hole_8.bin"
#define ANIM_BLACK_HOLE_9  "A:/anim/black_hole/anim_black_hole_9.bin"
#define ANIM_BLACK_HOLE_10 "A:/anim/black_hole/anim_black_hole_10.bin"
#define ANIM_BLACK_HOLE_11 "A:/anim/black_hole/anim_black_hole_11.bin"
#define ANIM_BLACK_HOLE_12 "A:/anim/black_hole/anim_black_hole_12.bin"
#define ANIM_BLACK_HOLE_13 "A:/anim/black_hole/anim_black_hole_13.bin"
#define ANIM_BLACK_HOLE_14 "A:/anim/black_hole/anim_black_hole_14.bin"
#define ANIM_BLACK_HOLE_15 "A:/anim/black_hole/anim_black_hole_15.bin"
#define ANIM_BLACK_HOLE_16 "A:/anim/black_hole/anim_black_hole_16.bin"
#define ANIM_BLACK_HOLE_17 "A:/anim/black_hole/anim_black_hole_17.bin"
#define ANIM_BLACK_HOLE_18 "A:/anim/black_hole/anim_black_hole_18.bin"

// Matrix Rain
#define ANIM_MATRIX_RAIN_1  "A:/anim/matrix_rain/anim_matrix_rain_1.bin"
#define ANIM_MATRIX_RAIN_2  "A:/anim/matrix_rain/anim_matrix_rain_2.bin"
#define ANIM_MATRIX_RAIN_3  "A:/anim/matrix_rain/anim_matrix_rain_3.bin"
#define ANIM_MATRIX_RAIN_4  "A:/anim/matrix_rain/anim_matrix_rain_4.bin"
#define ANIM_MATRIX_RAIN_5  "A:/anim/matrix_rain/anim_matrix_rain_5.bin"
#define ANIM_MATRIX_RAIN_6  "A:/anim/matrix_rain/anim_matrix_rain_6.bin"
#define ANIM_MATRIX_RAIN_7  "A:/anim/matrix_rain/anim_matrix_rain_7.bin"
#define ANIM_MATRIX_RAIN_8  "A:/anim/matrix_rain/anim_matrix_rain_8.bin"
#define ANIM_MATRIX_RAIN_9  "A:/anim/matrix_rain/anim_matrix_rain_9.bin"
#define ANIM_MATRIX_RAIN_10 "A:/anim/matrix_rain/anim_matrix_rain_10.bin"
#define ANIM_MATRIX_RAIN_11 "A:/anim/matrix_rain/anim_matrix_rain_11.bin"
#define ANIM_MATRIX_RAIN_12 "A:/anim/matrix_rain/anim_matrix_rain_12.bin"
#define ANIM_MATRIX_RAIN_13 "A:/anim/matrix_rain/anim_matrix_rain_13.bin"
#define ANIM_MATRIX_RAIN_14 "A:/anim/matrix_rain/anim_matrix_rain_14.bin"
#define ANIM_MATRIX_RAIN_15 "A:/anim/matrix_rain/anim_matrix_rain_15.bin"
#define ANIM_MATRIX_RAIN_16 "A:/anim/matrix_rain/anim_matrix_rain_16.bin"
#define ANIM_MATRIX_RAIN_17 "A:/anim/matrix_rain/anim_matrix_rain_17.bin"
#define ANIM_MATRIX_RAIN_18 "A:/anim/matrix_rain/anim_matrix_rain_18.bin"
#define ANIM_MATRIX_RAIN_19 "A:/anim/matrix_rain/anim_matrix_rain_19.bin"
#define ANIM_MATRIX_RAIN_20 "A:/anim/matrix_rain/anim_matrix_rain_20.bin"
#define ANIM_MATRIX_RAIN_21 "A:/anim/matrix_rain/anim_matrix_rain_21.bin"
#define ANIM_MATRIX_RAIN_22 "A:/anim/matrix_rain/anim_matrix_rain_22.bin"
#define ANIM_MATRIX_RAIN_23 "A:/anim/matrix_rain/anim_matrix_rain_23.bin"
#define ANIM_MATRIX_RAIN_24 "A:/anim/matrix_rain/anim_matrix_rain_24.bin"
#define ANIM_MATRIX_RAIN_25 "A:/anim/matrix_rain/anim_matrix_rain_25.bin"
#define ANIM_MATRIX_RAIN_26 "A:/anim/matrix_rain/anim_matrix_rain_26.bin"
#define ANIM_MATRIX_RAIN_27 "A:/anim/matrix_rain/anim_matrix_rain_27.bin"
#define ANIM_MATRIX_RAIN_28 "A:/anim/matrix_rain/anim_matrix_rain_28.bin"
#define ANIM_MATRIX_RAIN_29 "A:/anim/matrix_rain/anim_matrix_rain_29.bin"
#define ANIM_MATRIX_RAIN_30 "A:/anim/matrix_rain/anim_matrix_rain_30.bin"
#define ANIM_MATRIX_RAIN_31 "A:/anim/matrix_rain/anim_matrix_rain_31.bin"
#define ANIM_MATRIX_RAIN_32 "A:/anim/matrix_rain/anim_matrix_rain_32.bin"
#define ANIM_MATRIX_RAIN_33 "A:/anim/matrix_rain/anim_matrix_rain_33.bin"
#define ANIM_MATRIX_RAIN_34 "A:/anim/matrix_rain/anim_matrix_rain_34.bin"
#define ANIM_MATRIX_RAIN_35 "A:/anim/matrix_rain/anim_matrix_rain_35.bin"
#define ANIM_MATRIX_RAIN_36 "A:/anim/matrix_rain/anim_matrix_rain_36.bin"
#define ANIM_MATRIX_RAIN_37 "A:/anim/matrix_rain/anim_matrix_rain_37.bin"
#define ANIM_MATRIX_RAIN_38 "A:/anim/matrix_rain/anim_matrix_rain_38.bin"
#define ANIM_MATRIX_RAIN_39 "A:/anim/matrix_rain/anim_matrix_rain_39.bin"
#define ANIM_MATRIX_RAIN_40 "A:/anim/matrix_rain/anim_matrix_rain_40.bin"
#define ANIM_MATRIX_RAIN_41 "A:/anim/matrix_rain/anim_matrix_rain_41.bin"
#define ANIM_MATRIX_RAIN_42 "A:/anim/matrix_rain/anim_matrix_rain_42.bin"

// Pyramid
#ifdef POLYCAST5_EN_PYRAMID_ANIM
#define ANIM_PYRAMID_1  "A:/anim/pyramid/anim_pyramid_1.bin"
#define ANIM_PYRAMID_2  "A:/anim/pyramid/anim_pyramid_2.bin"
#define ANIM_PYRAMID_3  "A:/anim/pyramid/anim_pyramid_3.bin"
#define ANIM_PYRAMID_4  "A:/anim/pyramid/anim_pyramid_4.bin"
#define ANIM_PYRAMID_5  "A:/anim/pyramid/anim_pyramid_5.bin"
#define ANIM_PYRAMID_6  "A:/anim/pyramid/anim_pyramid_6.bin"
#define ANIM_PYRAMID_7  "A:/anim/pyramid/anim_pyramid_7.bin"
#define ANIM_PYRAMID_8  "A:/anim/pyramid/anim_pyramid_8.bin"
#define ANIM_PYRAMID_9  "A:/anim/pyramid/anim_pyramid_9.bin"
#define ANIM_PYRAMID_10 "A:/anim/pyramid/anim_pyramid_10.bin"
#define ANIM_PYRAMID_11 "A:/anim/pyramid/anim_pyramid_11.bin"
#define ANIM_PYRAMID_12 "A:/anim/pyramid/anim_pyramid_12.bin"
#define ANIM_PYRAMID_13 "A:/anim/pyramid/anim_pyramid_13.bin"
#define ANIM_PYRAMID_14 "A:/anim/pyramid/anim_pyramid_14.bin"
#define ANIM_PYRAMID_15 "A:/anim/pyramid/anim_pyramid_15.bin"
#define ANIM_PYRAMID_16 "A:/anim/pyramid/anim_pyramid_16.bin"
#define ANIM_PYRAMID_17 "A:/anim/pyramid/anim_pyramid_17.bin"
#define ANIM_PYRAMID_18 "A:/anim/pyramid/anim_pyramid_18.bin"
#define ANIM_PYRAMID_19 "A:/anim/pyramid/anim_pyramid_19.bin"
#define ANIM_PYRAMID_20 "A:/anim/pyramid/anim_pyramid_20.bin"
#define ANIM_PYRAMID_21 "A:/anim/pyramid/anim_pyramid_21.bin"
#define ANIM_PYRAMID_22 "A:/anim/pyramid/anim_pyramid_22.bin"
#define ANIM_PYRAMID_23 "A:/anim/pyramid/anim_pyramid_23.bin"
#define ANIM_PYRAMID_24 "A:/anim/pyramid/anim_pyramid_24.bin"
#define ANIM_PYRAMID_25 "A:/anim/pyramid/anim_pyramid_25.bin"
#define ANIM_PYRAMID_26 "A:/anim/pyramid/anim_pyramid_26.bin"
#define ANIM_PYRAMID_27 "A:/anim/pyramid/anim_pyramid_27.bin"
#define ANIM_PYRAMID_28 "A:/anim/pyramid/anim_pyramid_28.bin"
#define ANIM_PYRAMID_29 "A:/anim/pyramid/anim_pyramid_29.bin"
#define ANIM_PYRAMID_30 "A:/anim/pyramid/anim_pyramid_30.bin"
#define ANIM_PYRAMID_31 "A:/anim/pyramid/anim_pyramid_31.bin"
#define ANIM_PYRAMID_32 "A:/anim/pyramid/anim_pyramid_32.bin"
#define ANIM_PYRAMID_33 "A:/anim/pyramid/anim_pyramid_33.bin"
#define ANIM_PYRAMID_34 "A:/anim/pyramid/anim_pyramid_34.bin"
#define ANIM_PYRAMID_35 "A:/anim/pyramid/anim_pyramid_35.bin"
#define ANIM_PYRAMID_36 "A:/anim/pyramid/anim_pyramid_36.bin"
#define ANIM_PYRAMID_37 "A:/anim/pyramid/anim_pyramid_37.bin"
#define ANIM_PYRAMID_38 "A:/anim/pyramid/anim_pyramid_38.bin"
#define ANIM_PYRAMID_39 "A:/anim/pyramid/anim_pyramid_39.bin"
#define ANIM_PYRAMID_40 "A:/anim/pyramid/anim_pyramid_40.bin"
#define ANIM_PYRAMID_41 "A:/anim/pyramid/anim_pyramid_41.bin"
#define ANIM_PYRAMID_42 "A:/anim/pyramid/anim_pyramid_42.bin"
#define ANIM_PYRAMID_43 "A:/anim/pyramid/anim_pyramid_43.bin"
#define ANIM_PYRAMID_44 "A:/anim/pyramid/anim_pyramid_44.bin"
#define ANIM_PYRAMID_45 "A:/anim/pyramid/anim_pyramid_45.bin"
#define ANIM_PYRAMID_46 "A:/anim/pyramid/anim_pyramid_46.bin"
#define ANIM_PYRAMID_47 "A:/anim/pyramid/anim_pyramid_47.bin"
#define ANIM_PYRAMID_48 "A:/anim/pyramid/anim_pyramid_48.bin"
#define ANIM_PYRAMID_49 "A:/anim/pyramid/anim_pyramid_49.bin"
#define ANIM_PYRAMID_50 "A:/anim/pyramid/anim_pyramid_50.bin"
#define ANIM_PYRAMID_51 "A:/anim/pyramid/anim_pyramid_51.bin"
#define ANIM_PYRAMID_52 "A:/anim/pyramid/anim_pyramid_52.bin"
#define ANIM_PYRAMID_53 "A:/anim/pyramid/anim_pyramid_53.bin"
#define ANIM_PYRAMID_54 "A:/anim/pyramid/anim_pyramid_54.bin"
#define ANIM_PYRAMID_55 "A:/anim/pyramid/anim_pyramid_55.bin"
#define ANIM_PYRAMID_56 "A:/anim/pyramid/anim_pyramid_56.bin"
#endif


/* ANIMATIONS END */

// ------------------------- //

/* IMAGES START */

// Tools dice
#define IMG_DICE_1 "A:/img/img_dice_1.bin"
#define IMG_DICE_2 "A:/img/img_dice_2.bin"
#define IMG_DICE_3 "A:/img/img_dice_3.bin"
#define IMG_DICE_4 "A:/img/img_dice_4.bin"
#define IMG_DICE_5 "A:/img/img_dice_5.bin"
#define IMG_DICE_6 "A:/img/img_dice_6.bin"

/* IMAGES END */

// ------------------------- //

/* QRS START */

// ONLY BOOT QR: Others are now generated dynamically
#define QR_PC5_BOOT "A:/qr/qr_pc5_boot.bin"

/* QRS END */


#endif // LCD_ASSET_MACROS_H